### ISSUE TITLE
Requirements for new languages

### ISSUE THREAD

**Issue by Bubarinokk** [SWivid/F5-TTS#103]
What are the requirements for it to work in another language? How many hours of audio do I need?

**Comment by SWivid** [comment]
there are some discussions and pioneers in #57

**Comment by ZhikangNiu** [comment]
Same to https://github.com/SWivid/F5-TTS/issues/87

**Comment by Bubarinokk** [comment]
Thanks! ❤️ But how many hours of audio do I need on average? About 500 hours?

**Comment by ZhikangNiu** [comment]
> Thanks! ❤️ But how many hours of audio do I need on average? About 500 hours?

Not sure, I think you can finetune another language model by using 500 hours data and give us an answer. I will close this issue, if you have other questions, you can reopen this issue. Feel free to ask question : )
