### ISSUE TITLE
Mimic real human like conversation 

### ISSUE THREAD

**Issue by kentyler2** [SWivid/F5-TTS#104]
Include something like the following to mimic human like conversation like bark you can add the following to make conversations real, [laughter] [laughs] [sighs] [music] [gasps] [clears throat] — or ... for hesitations ♪ for song lyrics CAPITALIZATION for emphasis of a word

**Comment by jpgallegoar** [comment]
This is not possible without retraining or fine-tuning, so it's out of scope for now

**Comment by ZhikangNiu** [comment]
Our training data include this non-verbal token, eg:[laughter] [laughs] [sighs] [music] [gasps] [clears throat]. But you can annotate some data and finetune F5TTS

**Comment by sidharthrajaram** [comment]
When I include non-verbal tokens like that like "[laughter] The sky is indeed blue.", the generated audio produced sounds like "laughter, the sky is indeed blue". The non-verbal token is being spoken aloud. Any way to better avoid that?

Thanks

**Comment by SWivid** [comment]
> When I include non-verbal tokens like that like "[laughter] The sky is indeed blue.", the generated audio produced sounds like "laughter, the sky is indeed blue". The non-verbal token is being spoken aloud. Any way to better avoid that?
> 
> Thanks

we have not explicitly include non-verbal control in training, but there exists such acoustic features in dataset.
so it needs finetuning

**Comment by sidharthrajaram** [comment]
Ah, I see. thank you @SWivid

**Comment by ZhikangNiu** [comment]
I will close this issue. If you have other questions, you can reopen this issue.
