### ISSUE TITLE
Finetune a single voice?

### ISSUE THREAD

**Issue by gameveloster** [SWivid/F5-TTS#108]
Is it possible to finetune using voice samples from a single person?

If so, 

1. Will this finetuned model give much better quality than using the provided checkpoint with a few seconds of reference audio?
2. Will this finetuned model still require the reference audio and reference text?

Thank you for giving us F5-TTS

**Comment by ZhikangNiu** [comment]
you can check https://github.com/SWivid/F5-TTS/discussions/57
