### ISSUE TITLE
linearly estimated duration may have unstable generation

### ISSUE THREAD

**Issue by kunyao2015** [SWivid/F5-TTS#11]
fix_duration=None, speed=1.0 ，设置后，漏字重复问题很明显，如何解决这个问题呢

**Comment by SWivid** [comment]
有具体例子 比如使用的prompt吗
如果prompt的语速异常快或慢，或者开头结尾包含很长的静音，线性预估应该是不太行
最好的方式就是训练一个单独的时长预测器来提供全句时长，我们为了简单就没训；如果有计划训练欢迎PR ckpt

You may provide some specific examples of used prompt to locate the problem.
If the prompt is spoken at an unusually fast or slow rate, or if the (beginning/end of) prompt contains long silences, the linear estimate not work for sure.
The best approach is to train a separate duration predictor that provides the full sentence duration, which we left out for simplicity; Welcome to PR the ckpt if you plan to train such a dp model

**Comment by kunyao2015** [comment]
发现确实整体不超过30秒会好很多； 另一个问题， 跨语言的duration 如何合理预估，比如prompt是中文，需要合成英文，按test_infer_single中方式无需改动吗

**Comment by SWivid** [comment]
需要改的，因为训练中Emilia里遇到的顶多是code-switch，但是在inference里可能会用英文prompt来生成中文的
这两种语言语速是不同的，所以我们在注释写最好fix duration

如果要预估比较建议以不同语言的语速为基准，例如英文一个词是多少秒，中文一个词多少秒，然后算一下
此外因为两种语言分别扎堆，例如英文prompt+中文生成，可能会吞掉中文前几个字
这种情况可以通过在前面英文prompt对应的转录text加句号解决，因为模型其实并不“那么”在意转录对应文本，只需要让他知道前面有这么多字是prompt就行了（我们也试过把prompt对应的转录全换成等长的空格，其实也OK的）

**Comment by kunyao2015** [comment]
感谢回复， 很有帮助！
