### ISSUE TITLE
Offloading Whisper to CPU

### ISSUE THREAD

**Issue by athu16** [SWivid/F5-TTS#110]
I'm using the Gradio app on a laptop with 6 GB VRAM.

With the current settings, the model overflows into system RAM reducing generation speed significantly, but if I offload Whisper to CPU, it fits in about 5.2 GB. Can we have a cmdline swich / config file setting / in-app setting to do this automatically? Or perhaps unload Whisper when not in use?

The model itself is amazing by the way.

**Comment by SWivid** [comment]
Thanks for using. `inference-cli.py` may with your need

**Comment by athu16** [comment]
Thanks, just what I needed!
