### ISSUE TITLE
heads up.. should use a VENV or Minic Env

### ISSUE THREAD

**Issue by gjnave** [SWivid/F5-TTS#111]
Great project! Just a heads up that in the instructions you should point users to using a virtual environment so they dont inadvertently pollute their system.

Thanks for the repo!

**Comment by NemukaPrime** [comment]
Sorry for the beginner question, but how do you do that?

**Comment by gjnave** [comment]
> Sorry for the beginner question, but how do you do that?
No need to be sorry! 
You can use either miniconda or python
here is a tutorial I made on using python venv.
https://youtu.be/1KYoATkSlxE?si=oVaw7HIykrVyyPRm

In short: go you your directory and type:
python -m venv venv 
Then type:
call venv/scripts/activate 

Now you are in your virtual environment

**Comment by NemukaPrime** [comment]
Thank you for the instructions.
