### ISSUE TITLE
the emilia datasets location

### ISSUE THREAD

**Issue by gjnave** [SWivid/F5-TTS#112]
Hi there, am i missing something?
Trying to follow the directions but uncertain where the datasets are housed.
Thanks!

**Comment by SWivid** [comment]
the first lines in `prepare_emilia.py` points to the version of dataset we used
https://github.com/SWivid/F5-TTS/blob/ab78265b4d6e4c512374baaea56d7c46a35cb61b/scripts/prepare_emilia.py#L1-L2
thanks for using

**Comment by gjnave** [comment]
> the first lines in `prepare_emilia.py` points to the version of dataset we used
> 
> https://github.com/SWivid/F5-TTS/blob/ab78265b4d6e4c512374baaea56d7c46a35cb61b/scripts/prepare_emilia.py#L1-L2
> 
> 
> thanks for using

thank you

**Comment by Songjc0511** [comment]
> the first lines in `prepare_emilia.py` points to the version of dataset we used
> 
> https://github.com/SWivid/F5-TTS/blob/ab78265b4d6e4c512374baaea56d7c46a35cb61b/scripts/prepare_emilia.py#L1-L2
> 
> 
> thanks for using

Do I have to download the entire dataset? Because the ZH and EN together add up to nearly 2TB in size.

**Comment by SWivid** [comment]
> Do I have to download the entire dataset? Because the ZH and EN together add up to nearly 2TB in size.

@Songjc0511 how much you want how many you download.
It is not `have to` but the data amount you `want to`
