### ISSUE TITLE
HuggingFace App Problem

### ISSUE THREAD

**Issue by JohnFengNeumann** [SWivid/F5-TTS#114]
I tried the demo in your hugging face, but the result of F5 TTS can't speak the text in a right way, but E5 TTS can, may be the duration preditor and the text prompt part has some bugs to fix.

**Comment by SWivid** [comment]
maybe you could provide us some generated samples to figure out

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.
