### ISSUE TITLE
Problems In Fine Tuning

### ISSUE THREAD

**Issue by wen0320** [SWivid/F5-TTS#115]
Help, when fine-tuning, I have the following problems:

 RuntimeError: Error(s) in loading state_dict for EMA:
size mismatch for ema_model.transformer.text_embed.text_embed.weight:  copying a param with shape torch.Size([2546, 512]) from checkpoint, the shape in current model is torch.Size([259, 512])

**Comment by SWivid** [comment]
remember to reuse the `vocab.txt` compatible with pretrained model
you could simply get it at `data/Emilia_ZH_EN_pinyin/vocab.txt`

**Comment by wen0320** [comment]
Thanks
