### ISSUE TITLE
how to make it run faster

### ISSUE THREAD

**Issue by xwan07017** [SWivid/F5-TTS#120]
Inferring that 30 seconds of audio takes about 8 seconds, how to make it faster?

**Comment by lpscr** [comment]
hi @xwan07017 you can change setting inside to script **[inference-cli.py]** , **[gradio_app.py]**

**nfe_step** = **32**  # to **24**  or **16** see what best working for you

**Comment by CreepJoye** [comment]
> > why the F5-TTS base model has 22 layers
> 
> it is to scale total params ~335M, while E2 has 24 layers lol in order to have a fair comparison

I see，thank you very much！

**Comment by SWivid** [comment]
will close this issue, feel free to open if any questions.
