### ISSUE TITLE
效果问题

### ISSUE THREAD

**Issue by Thekey756** [SWivid/F5-TTS#121]
1、reference audio 如果超过20s ，生成的结果会胡言乱语
2、-gen_text中如果出现了 时间， 不能正确读出来

**Comment by SWivid** [comment]
在readme有说明，训练集只见过30秒
所以生成的时候只支持总时长<30s

没怎么做细致的文本正则，可以考虑自定义一个把时间做下预处理

**Comment by WalkingwithAI** [comment]
> 在readme有说明，训练集只见过30秒 所以生成的时候只支持总时长<30s
> 
> 没怎么做细致的文本正则，可以考虑自定义一个把时间做下预处理

朋友您好，感谢你们在这个项目的出色工作。针对这个项目，我测试了一些音色，包括马保国和星爷的，整体上感觉短音频的效果非常好，声音相似度和语气都非常不错，尤其是相似度。但是一旦稍微长点之后，音色就会非常不像，就是那种标准的剪映风格的音色，语气会稍微差一点儿，主要是音色不像了。
整体上还是优秀的，刚开始，祝后续能越来越好！
