### ISSUE TITLE
采用utf8每个字符一个时长的编码，必有深意

### ISSUE THREAD

**Issue by splinter21** [SWivid/F5-TTS#13]
如果简单地修改文本前端，是否会影响对齐效果？
我看你简单粗暴地将文本时长pad0到mel帧长，是不是因为每个字符一个时长的编码比较适合？

**Comment by SWivid** [comment]
不会的 既然简单粗暴pad0到mel帧长能work，就说明模型在别的上面也肯定work
这样搞是为了完全复刻E2 TTS的pipeline（突出一个什么都没有，embarrassingly easy）

完全可以用音素或者bpe，会更好训的

**Comment by splinter21** [comment]
> 不会的 既然简单粗暴纯用character pad0到mel帧长能work，就说明模型在别的上面也肯定work 这样搞是为了完全复刻E2 TTS的pipeline（突出一个什么附加的都没有，embarrassingly easy）
> 
> 完全可以用音素或者bpe，应该会更好训的

为什么diffusion能自己学会文本和mel的对齐呢，我不明白

**Comment by SWivid** [comment]
> 为什么diffusion能自己学会文本和mel的对齐呢，我不明白

这个逻辑可以参考文生图，虽然没有像TTS要求严格的对齐，但也是从prompt的风格和描述里做对齐
本身是让模型学习分布之间的关系，只是force-align之后学习难度更低一些
这是我粗浅的理解
