### ISSUE TITLE
Prepare the Emilia dataset python scripts/prepare_emilia.py correctly

### ISSUE THREAD

**Issue by Seeksy** [SWivid/F5-TTS#132]
can someone please make this more detailed? Where do I download the packages? I downloaded it from https://huggingface.co/datasets/amphion/Emilia-Dataset but there are no json files included that the python requires.

**Comment by ZhikangNiu** [comment]
> can someone please make this more detailed? Where do I download the packages? I downloaded it from https://huggingface.co/datasets/amphion/Emilia-Dataset but there are no json files included that the python requires.

Not the latest version Emilia-Dataset, you can download it from https://huggingface.co/datasets/amphion/Emilia-Dataset/tree/fc71e07

**Comment by ZhikangNiu** [comment]
I'll close this issue, if you have other questions you can reopen this issue. @Seeksy
