### ISSUE TITLE
The generated audio always produces an additional pronunciation

### ISSUE THREAD

**Issue by TheHonestBob** [SWivid/F5-TTS#133]
From the several test cases I tested, it always emits non-existent characters at the beginning of the audio
[zh_prompt.zip](https://github.com/user-attachments/files/17404857/zh_prompt.zip)
给定模型的存储路径时。我们给它保存anchors的路径；它必须是带有面部裁剪的图像。保证模型将加载此锚点并在找到匹配项时显示对应的名字。
or If you're having issues, try converting your reference audio to WAV or MP3, clipping it to 15s, and shortening your prompt.
both two models，when use gradio_app, Additionally, how can WAV make the model sound in uppercase letters

**Comment by SWivid** [comment]
are there generated samples apart from prompt?

**Comment by TheHonestBob** [comment]
> are there generated samples apart from prompt?

[audio_pre.zip](https://github.com/user-attachments/files/17405355/audio_pre.zip)
在开头的地方多发一个diao的音

**Comment by GordonDongZHAO** [comment]
I have encountered the same problem. There will be one or more sounds in the front (continuous). It seems to be related to the ref audio. Some have it, some don't.
遇到过同样问题，前面会多一个或几个音（是连续的）。似乎与ref音频有关，有的会，有的不会。

**Comment by SWivid** [comment]
> 在开头的地方多发一个diao的音

这个是ref最后的词。
确保ref_text以。结尾，最好ref_audio末尾有适当的空白silence

**Comment by TheHonestBob** [comment]
> > 在开头的地方多发一个diao的音
> 
> 这个是ref最后的词。 确保ref_text以。结尾，最好ref_audio末尾有适当的空白silence

ref_text 对,所以说你现在的话,这个账单的话,你既然说能处理,那你就想办法处理掉。. 
gen_text 0 经营微信小程序，主体是公司，资金到微信商户里，从商户里体现到对公账户需要交税吗？税务申报还可以是零申报吗？
这是后台日志，是有句号的，意思是我目前我的问题是ref_audio末尾静音片段太短了？

**Comment by SWivid** [comment]
嗯 留一些静音作间隔好一些

**Comment by ajkessel** [comment]
I believe I'm experiencing the same thing with some samples in English. Any ideas for how to troubleshoot/avoid?

**Comment by ajkessel** [comment]
I think I figured it out -- this happens when the reference audio is clipped arbitrarily in the middle of a syllable. Better, I think, to cut the reference audio at a silent point. So, for example, I've modified `process_voice` to clip at the first silence after 15 seconds. This needs to be refined if it doesn't find a sufficiently-long silence at first to search for shorter silences:
```
non_silent_segments = silence.split_on_silence(
    audio_clip, min_silence_len=1000, silence_thresh=-50, keep_silence=1000)
audio_clip = AudioSegment.silent(duration=0)
for non_silent_segment in non_silent_segments:
    audio_clip += non_silent_segment
    if len(audio_clip) > 15000:
        break

audio_duration = len(audio_clip)
if audio_duration > 20000:
    audio_clip = audio_clip[:20000]
audio_clip.export(f.name, format="wav")
ref_audio = f.name
```

**Comment by SWivid** [comment]
will close and a smoother clipper will be added
feel free to open if further questions

**Comment by pervrosen** [comment]
Can something like this work?

```python
def preprocess_ref_audio_text(ref_audio_orig, ref_text, show_info=print, device=device):
    show_info("Converting audio...")
    with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as f:
        aseg = AudioSegment.from_file(ref_audio_orig)

        audio_duration = None
        for cutoff in [-50,-40,-30,-20]:
            non_silent_segs = silence.split_on_silence(aseg, min_silence_len=1000, silence_thresh=cutoff, keep_silence=1000)
            non_silent_wave = AudioSegment.silent(duration=0)
            for non_silent_seg in non_silent_segs:
                non_silent_wave += non_silent_seg

            if len(non_silent_wave)<15000:
                aseg = non_silent_wave
                aseg.export(f.name, format="wav")
                ref_audio = f.name
                break

            audio_duration = len(aseg)

        if audio_duration > 15000:
            show_info("Audio is over 15s, clipping to only first 15s.")
            aseg = aseg[:15000]
            aseg.export(f.name, format="wav")
            ref_audio = f.name

    if not ref_text.strip():
        global asr_pipe
        if asr_pipe is None:
            initialize_asr_pipeline(device=device)
        show_info("No reference text provided, transcribing reference audio...")
        ref_text = asr_pipe(
            ref_audio,
            chunk_length_s=30,
            batch_size=128,
            generate_kwargs={"task": "transcribe"},
            return_timestamps=False,
        )["text"].strip()
        show_info("Finished transcription")
    else:
        show_info("Using custom reference text...")

    # Add the functionality to ensure it ends with ". "
    if not ref_text.endswith(". ") and not ref_text.endswith("。"):
        if ref_text.endswith("."):
            ref_text += " "
        else:
            ref_text += ". "

    return ref_audio, ref_text
```

**Comment by SWivid** [comment]
@pervrosen thanks for advice
but maybe need to check first the current code (already modified for a better cut)

the `silence_thresh` is for -dB w.r.t. definition of what is silence rather than a length
