### ISSUE TITLE
text_embed.weight mismatch after finetuning

### ISSUE THREAD

**Issue by justinjohn0306** [SWivid/F5-TTS#136]
I made sure to use the vocab.txt file that comes with the repo but I'm not sure why this error still occurs. I'm finetuning this on a single english speaker dataset.

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/d82895b8-4a6e-4fbc-a474-a8e10a6a5bfa">

**Comment by SWivid** [comment]
could you provide us the vocab.txt you use
thought you have used a wrong vocab.txt, check if the path is correctly pointing to correct vocab.txt

**Comment by justinjohn0306** [comment]
> could you provide us the vocab.txt you use thought you have used a wrong vocab.txt, check if the path is correctly pointing to correct vocab.txt

my bad, i was using a custom one - it works fine now

**Comment by justinjohn0306** [comment]
this ticket can be closed now :)
