### ISSUE TITLE
How many parameters in this model?

### ISSUE THREAD

**Issue by platform-kit** [SWivid/F5-TTS#14]
Just curious how it stacks up against existing TTS models. Truly great work on this, by the way, thanks for open sourcing.

**Comment by SWivid** [comment]
Sure, all configs are in our released paper.
The base model is of ~335M params. A detailed comparison of params and performance are in Tab.1 https://arxiv.org/abs/2410.06885
Thanks for using.

**Comment by ZhikangNiu** [comment]
I'll close this issue, if you have other questions you can reopen this issue. @platform-kit
