### ISSUE TITLE
Inference takes 45 minutes on a 2070 RTX GPU

### ISSUE THREAD

**Issue by EricasAccount** [SWivid/F5-TTS#140]
I've run TTS inference several times and it consistently takes about 45 minutes to generate output. This happens for both models, F5-TTS and E2-TTS. Is there a way to check if the app is running on CPU instead of GPU? My setup: Windows 10, NVidia RTX 2070, CUDA 11.8, torch==2.3.0.

**Comment by ZhikangNiu** [comment]
If you use inference-cli.py, you can check device https://github.com/SWivid/F5-TTS/blob/1a09b8048202232c30f32be5fbc4f0d5765bbbdd/inference-cli.py#L96

**Comment by EricasAccount** [comment]
Problem solved. I had  the CPU version of PyTorch installed. Thanks a lot.

**Comment by imunisasi** [comment]
@EricasAccount how to install GPU version of PyTorch ?
