### ISSUE TITLE
Shape mismatch error while fine tuning

### ISSUE THREAD

**Issue by rasheed-aidetic** [SWivid/F5-TTS#144]
Hi This project is incredible guys. Great work.

I am trying to finetune this model and facing an error on shape mismatch. Can anyone help?

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/F5-TTS/model/dataset.py", line 117, in __getitem__
    mel_spec = rearrange(mel_spec, '1 d t -> d t')
  File "/usr/local/lib/python3.10/dist-packages/einops/einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
  File "/usr/local/lib/python3.10/dist-packages/einops/einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "1 d t -> d t".
 Input tensor shape: torch.Size([2, 100, 1407]). Additional info: {}.
 Shape mismatch, 2 != 1`

I am trying to fine tune the model with my own voice model. I have created the dataset using the prepare_csv_wavs.py script. Please let me know if I need to make any changes in the input section of train.py

**Comment by lpscr** [comment]
i think the problem is to covert resample your audio to mono 24000 hz

run this script please first make back up because replace your original files !

```
import os
import glob
from pydub import AudioSegment

def convert_wav_to_mono(folder_path):
    wav_files = glob.glob(os.path.join(folder_path, '*.wav'))
    for file_path in wav_files:
        filename = os.path.basename(file_path)
        audio = AudioSegment.from_wav(file_path)
        mono_audio = audio.set_channels(1)
        mono_audio = mono_audio.set_frame_rate(24000)
        new_file_path = os.path.join(folder_path, f"mono_{filename}")
        mono_audio.export(new_file_path, format="wav")

folder_path = 'your_folder_path'
convert_wav_to_mono(folder_path)
```
