### ISSUE TITLE
I would like to add Uyghur language training. Is it supported?

### ISSUE THREAD

**Issue by mustapa0** [SWivid/F5-TTS#154]
I want to add a new data set for Uyghur language training model. I have the data set, but do you support it?
New Uyghur language format from right to left

**Comment by kunibald413** [comment]
Someone reported successfully training in Greek.

https://github.com/SWivid/F5-TTS/discussions/57#discussioncomment-10977003
https://github.com/SWivid/F5-TTS/discussions/57#discussioncomment-10977085

**Comment by mustapa0** [comment]
Thank you, I'll go check it out!

> Someone reported successfully training in Greek.
> 
> [#57 (comment)](https://bgithub.xyz/SWivid/F5-TTS/discussions/57#discussioncomment-10977003) [#57 (comment)](https://bgithub.xyz/SWivid/F5-TTS/discussions/57#discussioncomment-10977085)
