### ISSUE TITLE
If I want to customize a model with high sound quality and similar timbre, do I need to fine tune the base model

### ISSUE THREAD

**Issue by xwan07017** [SWivid/F5-TTS#156]
If I want to customize a model with high sound quality and similar timbre, do I need to fine tune the base model

**Comment by Toolfolks** [comment]
I think I do ... But new to all this cloning lark...
Is this training a model to make it sound more like the original ?????

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
