### ISSUE TITLE
合成的音频缺失和夹杂参考音频内容

### ISSUE THREAD

**Issue by 954028118** [SWivid/F5-TTS#157]
遇到的几个问题
gradio界面测试
1 合成的音频会在开头缺失几个字的发音(参考音频1s到3s试了几个)
2 以及开头会携带一点参考音频的尾部
3 合成音频中间会夹杂一些参考音频的内容（25s参考音频+长文本）
如题的3个问题，是什么原因呢，有没有什么解决方式

**Comment by SWivid** [comment]
我们在README里有说明，issue里也有类似的解答

1. 太短的参考音频会导致简单估算的时长不准，建议单独训练一个时长预测模型以应对该情况
2. 不太建议使用戛然而止的参考音频，最好留有一些空白静音在尾部
3. 过长的参考音频其实会被截断到15秒，参考2.

一般来说用10秒左右的参考音频，末尾留有一定空白余地会得到比较好的结果
我们的模型还很粗糙，带来使用不便敬请见谅~

**Comment by 954028118** [comment]
> 我们在README里有说明，issue里也有类似的解答
> 
> 1. 太短的参考音频会导致简单估算的时长不准，建议单独训练一个时长预测模型以应对该情况
> 2. 不太建议使用戛然而止的参考音频，最好留有一些空白静音在尾部
> 3. 过长的参考音频其实会被截断到15秒，参考2.
> 
> 一般来说用10秒左右的参考音频，末尾留有一定空白余地会得到比较好的结果 我们的模型还很粗糙，带来使用不便敬请见谅~

感谢解答，这对我很有帮助
