### ISSUE TITLE
What changed recently? Seems to run even slower now, and doesn't sound as good

### ISSUE THREAD

**Issue by nikolatesla20** [SWivid/F5-TTS#159]
I pulled latest GIT (Oct 18 2024) and really the performance and quality are worse now.

I also puts audio statements from the input reference audio at the beginning of the clip. It has like zero emotion now, reading very robotically.

**Comment by SWivid** [comment]
> I also puts audio statements from the input reference audio at the beginning of the clip

not quite understand for this part.

and for the changes made, the remove_silence option is default now, and you may turn it on in advance_setting, also with other controls

**Comment by sonicnerd14** [comment]
> > I also puts audio statements from the input reference audio at the beginning of the clip
> 
> not quite understand for this part.
> 
> and for the changes made, the remove_silence option is default now, and you may turn it on in advance_setting, also with other controls

I noticed this as well. Generations are taking much longer, and the output out is mostly just gibberish and nonsense artifacts. Not sure if they are doing something in the backend with the model, or the hugging face servers are getting hit hard. I'm able to generate better quality right now on my local machine with the same clips and text, then the servers. Only thing is the generation speed is much slower locally on my 3070.
