### ISSUE TITLE
finetune single speaker

### ISSUE THREAD

**Issue by kunibald413** [SWivid/F5-TTS#16]
is it possible to finetune for a single speaker, if so could you elaborate? (lora maybe)
thank you for your time!

**Comment by SWivid** [comment]
Full finetune is currently supported, lora or adapter not yet.
1. Set `checkpoint_path` to pretrained model dir in `test_train.py`, `model/trainer.py` will load from there to resume. Reuse the `vocab.txt` under `data
/Emilia_ZH_EN_pinyin` (Emilia_ZH_EN_pinyin <- tokenizer = "pinyin"; dataset_name = "Emilia_ZH_EN" in `test_train.py` setting) 
2. For preparing finetune data, see `model/dataset.py`. Just need e.g. the audio path, text (tokenized, leverage `convert_char_to_pinyin` func in `model/utils.py` see script/prepare_xxxx.py).
```
def __getitem__(self, index):
    row = self.data[index]
    audio_path = row["audio_path"]
    text = row["text"]
    duration = row["duration"]
```

**Comment by ZhikangNiu** [comment]
I'll close this issue, if you have other questions you can reopen this issue. @kunibald413

**Comment by JarodMica** [comment]
Hey guys, appreciate the project, the model has been great so far!

Reopening to ask a question, so I've set up a dataset to be compatible with dataset.py, set the parameters inside of the test_train.py, and on trying to load F5TTS_Base, it seems like it's missing some keys:

```
Exception has occurred: KeyError
'model_state_dict'
  File "C:\Users\jarod\OneDrive\Desktop\code\F5-TTS\model\trainer.py", line 154, in load_checkpoint
    self.accelerator.unwrap_model(self.model).load_state_dict(checkpoint['model_state_dict'])
                                                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jarod\OneDrive\Desktop\code\F5-TTS\model\trainer.py", line 240, in train
    start_step = self.load_checkpoint()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jarod\OneDrive\Desktop\code\F5-TTS\test_train.py", line 85, in main
    trainer.train(train_dataset,
  File "C:\Users\jarod\OneDrive\Desktop\code\F5-TTS\test_train.py", line 92, in <module>
    main()
KeyError: 'model_state_dict'
```

Were the pretrained models distilled down to remove these keys? If so, got any tips for loading it up into further training?

I played around with just trying to load ema_model_state_dict, but it seems like I ended up just starting from scratch with this.

**Comment by shekharmeena2896** [comment]
Hi I was trying to finetune the pretrained weights of hindi model, I changed the path in train.py (checkpoint_paths to the pretrained directory as suggested by @SWivid   and my config file is

hydra: 
run:
dir: ckpts/${model.name}${model.mel_spec.mel_spec_type}${model.tokenizer}_${datasets.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

datasets:
name: hindi_dataset_custom
batch_size_per_gpu: 3200
batch_size_type: frame
max_samples: 64
num_workers: 8 # Reduced from 16 to be safe

optim:
epochs: 500
learning_rate: 1e-5
num_warmup_updates: 500
grad_accumulation_steps: 1
max_grad_norm: 1.0
bnb_optimizer: False

model:
name: F5TTS_Hindi_Finetune
tokenizer: custom # Using custom for Hindi
tokenizer_path: /home/ubuntu/F5-TTS/data/hindi_dataset_custom/vocab.txt # Path to your Hindi vocab
backbone: DiT # This was missing in your config!
arch:
dim: 768
depth: 18
heads: 12
ff_mult: 2
text_dim: 512
text_mask_padding: False
conv_layers: 4
pe_attn_head: 1
checkpoint_activations: True
mel_spec:
target_sample_rate: 24000
n_mel_channels: 100
hop_length: 256
win_length: 1024
n_fft: 1024
mel_spec_type: vocos
vocoder:
is_local: False
local_path: null

ckpts:
logger: wandb # Set to null for simpler setup, or use wandb/tensorboard if desired
log_samples: True
save_per_updates: 5000 # Reduced from 50000 for more frequent saves
keep_last_n_checkpoints: 3 # Keep only the last 3 checkpoints to save space
last_per_updates: 500
save_dir: ckpts/my_hindi_finetune_run # Path to your pretrained model
(f5tts) root@t1-le-45-gra7:/home/ubuntu/F5-TTS/src/f5_tts/configs#

the training finish instantly I am not able to understand what mistake I am making this below is the output :

(f5tts) root@t1-le-45-gra7:/home/ubuntu/F5-TTS/src/f5_tts/configs# cd ../../..
(f5tts) root@t1-le-45-gra7:/home/ubuntu/F5-TTS# tail -f nohup.out
Loading dataset ...
Download Vocos from huggingface charactr/vocos-mel-24khz
Sorting with sampler... if slow, check whether dataset is provided with duration: 100%|██████████| 5900/5900 [00:00<00:00, 1259166.21it/s]
Creating dynamic batches with 3200 audio frames per gpu: 100%|██████████| 5900/5900 [00:00<00:00, 1693798.33it/s]
wandb:
wandb: 🚀 View run F5TTS_Hindi_Finetune_vocos_custom_hindi_dataset_custom at: https://wandb.ai/devteeoff-teeoff-technologies/CFM-TTS/runs/vtuhvwdi
wandb: ⭐️ View project at: https://wandb.ai/devteeoff-teeoff-technologies/CFM-TTS
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250527_073442-vtuhvwdi/logs
Saved last checkpoint at update 2500000
