### ISSUE TITLE
An additional speaker for the podcast (total of 3 speakers), Add speed sliders to adjust voices in podcast as well for each speaker.

### ISSUE THREAD

**Issue by CRCODE22** [SWivid/F5-TTS#161]
Hi please add an additional speaker for the podcast (total of 3 speakers) and speed sliders to adjust voices in podcast as well for each speaker.

**Comment by chigkim** [comment]
Why not just use multi-style tab to generate more than 2 speakers. Marking voices is different format, but it basically does the same thing.

**Comment by CRCODE22** [comment]
You do not understand I need a podcast between 3-4 people: Another AI write the scripts so I can copy and paste just two speakers is very limited surely it is not that difficult to add more speakers. Rather than closing this as completed which is not just say if you cannot do it rather than suggesting things that do not do what I need it to do.

For example:
Speaker:1
Speaker:2
Speaker:3

**Comment by CRCODE22** [comment]
Codewise it might look like this and I am not even an advanced coder just do not know if more scripts than gradio_app.py need to be modified:

@gpu_decorator
def generate_podcast(
    script, speaker1_name, ref_audio1, ref_text1, speaker2_name, ref_audio2, ref_text2, speaker3_name, ref_audio3, ref_text3,model, remove_silence
):
    # Split the script into speaker blocks
    speaker_pattern = re.compile(f"^({re.escape(speaker1_name)}|{re.escape(speaker2_name)})|({re.escape(speaker3_name)}:", re.MULTILINE)
    speaker_blocks = speaker_pattern.split(script)[1:]  # Skip the first empty element

    generated_audio_segments = []

    for i in range(0, len(speaker_blocks), 3):
        speaker = speaker_blocks[i]
        text = speaker_blocks[i + 1].strip()

        # Determine which speaker is talking
        if speaker == speaker1_name:
            ref_audio = ref_audio1
            ref_text = ref_text1
        elif speaker == speaker2_name:
            ref_audio = ref_audio2
            ref_text = ref_text2
        elif speaker == speaker3_name:
            ref_audio = ref_audio3
            ref_text = ref_text3
        else:
            continue  # Skip if the speaker is neither speaker1 nor speaker2 nor speaker3

**Comment by chigkim** [comment]
Have you looked at the Multi-Style as I suggested?
Just use the Multi-Style, and change your text format to:
(speaker1) blabla
(speaker2) blabla
(speaker999) bla bla
...

**Comment by CRCODE22** [comment]
> Have you looked at the Multi-Style as I suggested? Just use the Multi-Style, and change your text format to: (speaker1) blabla (speaker2) blabla (speaker999) bla bla ...

Not yet but I will see if that also works.

Here is an output of the modified script I made: Here is a 3 speaker podcast style example thanks to The Borg Queen: [https://github.com/CRCODE22/F5-TTS/blob/main/Rommie_The_Borg_Queen_Phoebe.wav](url)

**Comment by chigkim** [comment]
Practically multi-style does the same thing and is much more flexible. NO need to reinvent the wheel. We should just get rid of podcast tab.

**Comment by CRCODE22** [comment]
Multi-style does achieve the same output would have been nice to have similar in podcasts-style tab tho since the add option is better than having for example 2-3 fixed speakers. If it just remains multi-style tab the description could be more clear that you can also use it for multiple speakers rather than just changing emotions.
