### ISSUE TITLE
Couldn't find ffmpeg or avconv

### ISSUE THREAD

**Issue by quantumalchemy** [SWivid/F5-TTS#162]
/usr/local/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
I installed  ffmpeg  in path but no go any incites?

**Comment by lpscr** [comment]
in windows download 

[https://www.gyan.dev/ffmpeg/builds/](https://www.gyan.dev/ffmpeg/builds/) 

extract files then go inside to bin folder you find 3 exe files

create folder in c: with name **ffmpeg**
put in **C:\ffmpeg** the exe files **ffmpeg.exe** , **ffplay.exe** , **ffprobe.exe**

run cmd as admin
and run this command to set path after must wroking fine 
setx /M PATH "%PATH%;C:\ffmpeg

restart and must working fine

i hope this help

**Comment by ZhikangNiu** [comment]
I will close this issue. If you have other questions, you can reopen this issue
