### ISSUE TITLE
HuggingFace demo not working

### ISSUE THREAD

**Issue by Makkarob** [SWivid/F5-TTS#164]
The demo at this address doesn't work, it used to give one error earlier and the creator seems to have fixed it, but now another one has appeared, with even more text. Can you fix it, please?

https://huggingface.co/spaces/mrfakename/E2-F5-TTS

**Comment by ZhikangNiu** [comment]
![image](https://github.com/user-attachments/assets/a11b9122-2a2e-4407-b9d2-f07c12694958)
you can contact with @fakerybakery

**Comment by SWivid** [comment]
the demo is working now~  so we are closing this issue

**Comment by mymggithub** [comment]
It seems be another error.
can you please fix it?
https://huggingface.co/spaces/mrfakename/E2-F5-TTS
![image](https://github.com/user-attachments/assets/6d3ab453-2284-46f2-b2d2-0431c84beeb7)
