### ISSUE TITLE
Stays at "Processing" and never converts.

### ISSUE THREAD

**Issue by BMKBAI** [SWivid/F5-TTS#171]
Hi everyone. I've deleted the folder and started all over again just to see if that was the case, but it is not. I have everything in stalled, even ffmpeg and python version as well. The link opens, i am able to upload an audio sample and even synthesize, but i never ever get the conversion. Right now, it is literally at the 380-second mark. I understand it shouldn't take this long, so what am I doing incorrectly, or what am I missing?

**Comment by SWivid** [comment]
maybe you could help with checking your torch version, see if it's -cpu or -cuda.
and make sure your connection to huggingface is fine, otherwise using a local ckpt is better
