### ISSUE TITLE
inference results different from demo

### ISSUE THREAD

**Issue by yl4579** [SWivid/F5-TTS#172]
When I run 

```
python inference-cli.py \
--model "F5-TTS" \
--ref_audio "tests/ref_audio/test_en_1_ref_short.wav" \
--ref_text "Some call me nature, others call me mother nature." \
--gen_text "I don't really care what you call me. I've been a silent spectator, watching species evolve, empires rise and fall. But always remember, I am mighty and enduring. Respect me and I'll nurture you; ignore me and you shall face the consequences."
```
it outputs audio of 25 seconds instead of 19 seconds on the demo page, and it happens for all audios. How did you get these total lengths on the demo page?

**Comment by SWivid** [comment]
we are using the early version of repo
https://github.com/SWivid/F5-TTS/tree/ed0b71aa7010c83fa8a72c291a61cf51b28a646d
with a fixed duration
https://github.com/SWivid/F5-TTS/blob/ed0b71aa7010c83fa8a72c291a61cf51b28a646d/test_infer_single.py#L43
Thanks~

**Comment by yl4579** [comment]
does it mean you pre-specified the duration for each sample? where did you get these durations and how were they determined?

**Comment by SWivid** [comment]
> does it mean you pre-specified the duration for each sample? where did you get these durations and how were they determined?

in zero-shot generation test, we set a duration in order to have similar generated length as seed-tts demo page
as you can see, we use shorter ref_audio cuz our model can only support up to 30s generation

**Comment by SWivid** [comment]
> we set a duration in order to have similar generated length as seed-tts demo page

and i just double check for it, if the samples also exist in maskgct demo page, we are using a duration to have generated audio lengths equal to theirs.

**Comment by yl4579** [comment]
Thanks for your prompt reply. Does it apply to the code switching samples too? I found code switching has the worst performance, if I don’t specify the duration the results are almost always gibberish.

**Comment by SWivid** [comment]
> Does it apply to the code switching samples too?

Yes, the early version duration estimation does not consider code-switch. At that time we simply fix an approximate duration, and it's pretty straightforward to synthesize good code-switched sentences.

The current version takes into account the code-switch case, which I just tried `inference-cli.py` for `他今天的mood看起来不太好，可能需要一些space。`, seems fine.

btw, we are working hard to train and come up with a better version to make duration estimation less inconvenient.

**Comment by yl4579** [comment]
Thanks for your response. Looking forward to a better solution for duration modeling!
