### ISSUE TITLE
Possible bug in inference-cli: should ref_text length increase on each loop?

### ISSUE THREAD

**Issue by ajkessel** [SWivid/F5-TTS#178]
[This line](https://github.com/SWivid/F5-TTS/blob/84cb6e5f008381316349fcdd22e42c8315029ae1/inference-cli.py#L246) increases the length of ref_text for each text in the list. Shouldn't that line be outside the loop?

**Comment by SWivid** [comment]
Thanks! Fixed in a016d6f89cbc5fea94dc6fccec989f5c3a91b63a
