### ISSUE TITLE
zh_pause_punc in inference-cli.py seems to be missing regexp notation

### ISSUE THREAD

**Issue by ajkessel** [SWivid/F5-TTS#179]
[This line](https://github.com/SWivid/F5-TTS/blob/a016d6f89cbc5fea94dc6fccec989f5c3a91b63a/inference-cli.py#L253) appears to be designed to increase the total duration based on punctuation marks:
```
zh_pause_punc = r"。，、；：？！"
ref_text_len = len(ref_text.encode('utf-8')) + 3 * len(re.findall(zh_pause_punc, ref_text))
gen_text_len = len(gen_text.encode('utf-8')) + 3 * len(re.findall(zh_pause_punc, gen_text))
duration = ref_audio_len + int(ref_audio_len / ref_text_len * gen_text_len / speed)
```
But the `r""` notation creates a string literal, meaning it is going to look for that entire sequence of punctuation as written. Did you intend something like this instead?
```
zh_pause_punc = re.compile("[。，、；：？！]")
```
Also isn't that expression going to miss any non-Unicode (single width) punctuation?

**Comment by SWivid** [comment]
@ajkessel Thanks~
Let's just remove it. It was mainly for zh, cuz we observed longer silence with zh puncs.
69850fa2362e0f60c90e618c0fe79da664e2f3ac
