### ISSUE TITLE
example speech edit not accurate 

### ISSUE THREAD

**Issue by acul3** [SWivid/F5-TTS#183]
hey @SWivid 

i ran speech editiing.py without editing any code (same example audio also)

is this expected?

https://vocaroo.com/19904Rnvyj5U

it should be
`Some call me optimist, others call me realist.`

**Comment by SWivid** [comment]
Hi @acul3 
Thought it would be for using wrong ckpt or vocab.txt

**Comment by acul3** [comment]
> Hi @acul3 Thought it would be for using wrong ckpt or vocab.txt

weird,, i did use it from pretrained, i inference "optimist" and  "realist" using inference-cli and it generate correctly

**Comment by SWivid** [comment]
Yes, it's weird. I just got it work from my side.
https://voca.ro/14TvySpIU44a

**Comment by acul3** [comment]
@SWivid thanks for the confirmation!

let me see what wrong
thank you

**Comment by acul3** [comment]
git reset --hard, redownload file fix the issue
