### ISSUE TITLE
Streaming API and single voice mode

### ISSUE THREAD

**Issue by MithrilMan** [SWivid/F5-TTS#187]
Thanks for this project, I'm playing with it on docker right now.

I'm implementing a local assistant that has TTS, I've already implemented different TTS service and I'd like to play with this too.
Unluckily I need an Italian voice but atm I'm fine with English too.
I've impelemented a couple of tricks to improve the "realtime" feeling of TTS service when they cannot stream (e.g. generate in chunks and pre-generate the next sentence before the one ends playing) but of course having a Streaming API would be the preferred way.

Any plan to add a streaming API?

Also the FTTS (First Token To Speech) is very important, how can I improve it?
In my use case I need a single voice, could I improve the time by preloading a state with the reference voice and reuse it any time?
Would it help on response time or is it negligible?

P.S.
on the gradio demo, having a configurable NFE step dropdown helps evaluating, if you want I can add a PR to add it like I did on my local fork
![image](https://github.com/user-attachments/assets/7bb2b3c0-33bf-4da1-b834-b7f0ffde9207)

**Comment by SWivid** [comment]
Yes, don't hesitate to PR~

For FTTS, you could leverage a short text (maybe also a shorter version of ref_audio) at first chunk.

The current TTS systems (both F5 and E2) are trained with infilling task. They are generating both the part of reference (the masked part in training) and the part to output (a noise/noisy speech in training) at same time. 
So it consumes additional unnecessary computation to generate parts of the reference audio over and over again in each chunk (as we are not generally doing editing tasks).

Again thanks for using our model (still a rough version), and any discussion and suggestions are welcome.

**Comment by ahmetkca** [comment]
> Yes, don't hesitate to PR~
> 
> For FTTS, you could leverage a short text (maybe also a shorter version of ref_audio) at first chunk.
> 
> The current TTS systems (both F5 and E2) are trained with infilling task. They are generating both the part of reference (the masked part in training) and the part to output (a noise/noisy speech in training) at same time. So it consumes additional unnecessary computation to generate parts of the reference audio over and over again in each chunk (as we are not generally doing editing tasks).
> 
> Again thanks for using our model (still a rough version), and any discussion and suggestions are welcome.

I would like to take on the task of implementing Streaming API as I think would make this project skyrocket to the moon. Any starter points would be appreciated. Having realtime api or even close to 300-350 ms would be life changing. 

Do you think is it even possible with the current architecture? or does it require a new breakthrough?

**Comment by SWivid** [comment]
> Do you think is it even possible with the current architecture? or does it require a new breakthrough?

I'm for the latter lol. Might try with current arch. if have time, but we can look forward to a truly streaming NAR TTS model.

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.

**Comment by jadams777** [comment]
+1 for a streaming API!

**Comment by apensotti** [comment]
+1 for streaming API!

**Comment by Baytro** [comment]
has there been any progress? I was looking into it, only found the server client files where the infer_batch method has a streaming parameter, but can it stream during batch inference?
