### ISSUE TITLE
Request to split based on what word is being used for the Gradio app

### ISSUE THREAD

**Issue by GUUser91** [SWivid/F5-TTS#188]
Can you include the option to split the chunk based on what word is being used? Like say for example, I want the split to start with the word cheese and split from this

```
I like to eat cheese. I like to eat pizza.
```

to this

```
I like to eat cheese.
```

**Comment by SWivid** [comment]
It is like explicitly do chunking?
`I like to eat cheese. I like to eat pizza.` -> `I like to eat cheese.`    `I like to eat pizza.`
I thought it could be realized with multi-style generation (to do explicit chunking) but you just pass in same reference audio (for each chunk), lol
