### ISSUE TITLE
中文如何进行更精细的控制，如多音字、连读等

### ISSUE THREAD

**Issue by tengsimin** [SWivid/F5-TTS#193]
中文的有些句子多音字、断句和连读模型读的还有一些问题，如何进行控制，
eg：
各个区县市更以其得天独厚的户外休闲旅游资源吸引着来自海内外的游客
question:
各个区县市未连读，户外休闲旅游资源未连读被拆开读。

还有多音字如何控制，试了也不支持输入拼音，是否未进行这部分训练支持。

**Comment by SWivid** [comment]
`各个区县市更以其得天独厚的户外休闲旅游资源吸引着来自海内外的游客`
建议改成如
`各个区县市，更以其得天独厚的户外休闲旅游资源，吸引着来自海内外的游客。`
具体怎么得到更想要的结果，可以先多浏览issue，大部分都已经有说明。

我们paper中说明了训练是用全拼音，
https://github.com/SWivid/F5-TTS/blob/77e00db01bcd82882fcd8591d80e683a9da031bd/model/utils_infer.py#L220
将final_text_list改成你想要的，传入就行了
https://github.com/SWivid/F5-TTS/blob/77e00db01bcd82882fcd8591d80e683a9da031bd/model/utils_infer.py#L229-L237

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions

**Comment by leonjin819** [comment]
mark

**Comment by leonjin819** [comment]
https://github.com/SWivid/F5-TTS/issues/664
