### ISSUE TITLE
Why 15 seconds?

### ISSUE THREAD

**Issue by cocktailpeanut** [SWivid/F5-TTS#195]
Just curious why the model has the 15 second sample limit.

I actually tried changing the code to allow up to 30 seconds and trimmed first 30 seconds instead of 15 seconds and the generation seems to work, but the quality is pretty low compared to the 15 sec.

So the question is, is 15 second a number you came to after testing multiple different options? And why does this happen?

**Comment by SWivid** [comment]
`Currently support 30s for a single generation, which is the TOTAL length of prompt audio and the generated.`
Cuz the training set is up to 30s, so models are not good at over length generation (especially e2

**Comment by SWivid** [comment]
> if i entered 15 second prompt audio, i can only generate 15 second

Yes that's it.
The current way of generating long samples is actually generating by chunck (each with total length <30s), and concate them.
That's why there's inconsistency somtimes.

**Comment by SWivid** [comment]
will close this issue, if further questions feel free to open~
