### ISSUE TITLE
Minimal GPU Memory Requirements for Running the Model??

### ISSUE THREAD

**Issue by sachin-seisei** [SWivid/F5-TTS#197]
I would like to know:

What is the minimal GPU memory requirement for running this model smoothly?
Is there a recommended batch size or other configurations (like precision or memory optimizations) I should use to reduce memory usage?
i managed to change batch_size of trainer.py script, utils_infer.py still encountering cuda oom!! can you tell me the minimal requirements of GPU mmeory??

**Comment by SWivid** [comment]
the minimal GPU memory is like 2G (just loading F5/E2 TTS model, and not leverage ASR model to do transcription)
btw you were to do training or inference.

**Comment by SWivid** [comment]
which script are you using? gradio_app.py or inference-cli.py

**Comment by sachin-seisei** [comment]
inference-cli.py

**Comment by SWivid** [comment]
how many gpu mem do you have.
i just tweak the `inference-cli.py` script, make sure it is not loading unneeded asr pipeline.
it takes 1622M gpu mem for me running it

**Comment by sachin-seisei** [comment]
the issue has been resol
