### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [SWivid/F5-TTS#2]
Hi,
Thanks for releasing F5 TTS! I noticed the license is CC-BY, which is not normally used for code. Are there any plans to switch to a code license (i.e. MIT/Apache/ISC)?
Thanks!

**Comment by SWivid** [comment]
Sure,
I will switch to MIT if it would bring more convenient use.

**Comment by fakerybakery** [comment]
Thanks!

**Comment by fakerybakery** [comment]
Hi,
Just to clarify, are the models also released under the MIT license?
Thanks!

**Comment by SWivid** [comment]
CC-BY-4.0 on HF ckpt repo, though I thought to be almost the same as MIT license (as there's no NC or SA)

**Comment by SWivid** [comment]
> CC-BY-4.0 on HF ckpt repo, though I thought to be almost the same as MIT license (as there's no NC or SA)

@fakerybakery Hi, we're sorry that we made a mistake earlier. We just realized that Emilia is using cc-by-nc-4.0, mainly for it's an in-the-wild dataset, and the copyright should goes to the original owners of the videos or audio.

We think we should abide by the protocols, so we change our ckpt repo to cc-by-nc-4.0. Sorry again for any inconvenience this may cause. Our codebase will keeps with MIT license.

**Comment by kylehowells** [comment]
@SWivid regarding the licence and the Emilia dataset, the team behind it (who released the dataset itself) https://huggingface.co/datasets/amphion/Emilia obviously don't feel training on the in the wild data makes the models themselves `cc-by-nc-4.0` as their own MIT licensed `amphion/MaskGCT` is `MIT` licensed.

Also the big player in the SST world, Whisper https://github.com/openai/whisper was trained on almost entirely in the wild data (including YouTube from how often it hallucinates to "please like and subscribe") and is licensed as `MIT`.

**Comment by SWivid** [comment]
Hi @kylehowells ~

I think we should follow the basic rules, even though some people don't.

We don't actually restrict where the model can be used, the protocol is just to follow the rules. Please be assured that we will not cause you any trouble~

**Comment by lukaLLM** [comment]
Does this mean this model could be used for commercial purposes or not, I got a bit confused while reading it I see a lot of models use the Emilia and change license.
