### ISSUE TITLE
小数据训练

### ISSUE THREAD

**Issue by 1750585724** [SWivid/F5-TTS#203]
我想问一下你们有没有用小数据集训练出的模型，我想问一下效果大概是怎么样的

**Comment by SWivid** [comment]
> 我想问一下你们有没有用小数据集训练出的模型，我想问一下效果大概是怎么样的

小模型客观指标参考arxiv paper
小模型在部分细节上（比如timestep embedding的维度）和目前repo不兼容，整体结构一致的

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.

**Comment by justzmq** [comment]
我想问下，如果我只有半个小时的语音数据，可以微调出具有该语音特色的模型么？如果可以的话，我大概需要设置怎样的微调参数？期待回复！感谢！

**Comment by SWivid** [comment]
@justzmq 可以看看discussion里的讨论，他们会比较有经验
