### ISSUE TITLE
Pydantic Schema Generation Error

### ISSUE THREAD

**Issue by ldavis9000aws** [SWivid/F5-TTS#206]
After I upload a small audio clip in gradio (less than 15 seconds), then type a sentence in the "Tex to Generate" field and click synthesize, I receive the error below. I've also attached the traceback file.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/f5tts/lib/python3.10/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/ubuntu/miniconda3/envs/f5tts/lib/python3.10/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.**

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

[traceback_info.txt](https://github.com/user-attachments/files/17463284/traceback_info.txt)

**Comment by ldavis9000aws** [comment]
Turns out I was still wrestling with some Conda environment issues. I ended up recreating the environment & everything is finally working. I also realized that I had Cuda 12.1 installed and had to modify the Pytorch install lines to use that version rather than 11.8. 

pip install torch==2.3.0+**cu121** --extra-index-url https://download.pytorch.org/whl/cu121
pip install torchaudio==2.3.0+**cu121** --extra-index-url https://download.pytorch.org/whl/cu121

I also installed the requirements.txt file first, then Pytorch, then had to manually download the E2TTS and F5TTS checkpoint files into the "f5-tts/ckpts" directory.

**Comment by ldavis9000aws** [comment]
> Turns out I was still wrestling with some Conda environment issues. I ended up recreating the environment & everything is finally working. I also realized that I had Cuda 12.1 installed and had to modify the Pytorch install lines to use that version rather than 11.8.
> 
> pip install torch==2.3.0+**cu121** --extra-index-url https://download.pytorch.org/whl/cu121 pip install torchaudio==2.3.0+**cu121** --extra-index-url https://download.pytorch.org/whl/cu121
> 
> I also installed the requirements.txt file first, then Pytorch, then had to manually download the E2TTS and F5TTS checkpoint files into the "f5-tts/ckpts" directory.

A quick note here: I don't think I actually to manually download the models to that directory...it looks as the models in that separate directory are being used during inference. If that's how it's supposed to work, then great....may need to update the readme and point that out...

**Comment by SWivid** [comment]
Hi @ldavis9000aws great it works for you~
we have mentioned that in readme lol, like
`The pretrained model checkpoints can be reached at 🤗 Hugging Face and 🤖 Model Scope, or automatically downloaded with inference-cli and gradio_app.`
