### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by CamellIyquitous** [SWivid/F5-TTS#209]
(f5tts) haoen@showlab04:~/F5-TTS$ python gradio_app.py
Using cuda device
Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  Emilia_ZH_EN
tokenizer :  pinyin
model :  /home/haoen/.cache/huggingface/hub/models--SWivid--F5-TTS/snapshots/d0ac03c2b5ded76f302ada887ae0da5675e88a5d/F5TTS_Base/model_1200000.safetensors 

vocab :  Emilia_ZH_EN
tokenizer :  pinyin
model :  /home/haoen/.cache/huggingface/hub/models--SWivid--E2-TTS/snapshots/98016df3e24487aad803aff506335caba8414195/E2TTS_Base/model_1200000.safetensors 

Starting app...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.26k/1.26k [00:00<00:00, 8.07MB/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1.62G/1.62G [02:18<00:00, 11.7MB/s]
generation_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3.77k/3.77k [00:00<00:00, 22.1MB/s]
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 283k/283k [00:00<00:00, 1.26MB/s]
vocab.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 1.05MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 2.71M/2.71M [00:01<00:00, 2.53MB/s]
merges.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 494k/494k [00:00<00:00, 2.09MB/s]
normalizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 52.7k/52.7k [00:00<00:00, 19.2MB/s]
added_tokens.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 34.6k/34.6k [00:00<00:00, 3.07MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 2.19k/2.19k [00:00<00:00, 12.5MB/s]
preprocessor_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 340/340 [00:00<00:00, 1.02MB/s]
/home/haoen/anaconda3/envs/f5tts/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
Segmentation fault (core dumped)

--------
This problem has troubled me for a long time. I have tried many combinations of numpy, torch, and python versions, but none of them worked. Please help QAQ. For now, I am using python3.10.14, torch 2.3.0+cu118.

**Comment by SWivid** [comment]
closing this issue, feel free to open if further questions.

**Comment by yachuntsaikk** [comment]
I had a similar issue and resolved it by installing a different version of the package.

Replace this:

```
pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
```
with:

```
pip install torch==2.3.0+cu121 torchaudio==2.3.0+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
```

**Comment by CamellIyquitous** [comment]
> I had a similar issue and resolved it by installing a different version of the package.
> 
> Replace this:
> 
> ```
> pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
> ```
> 
> with:
> 
> ```
> pip install torch==2.3.0+cu121 torchaudio==2.3.0+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
> ```

you are right, cuda 12.1 is just fine.

**Comment by eehoeskrap** [comment]
> I had a similar issue and resolved it by installing a different version of the package.
> 
> Replace this:
> 
> ```
> pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
> ```
> 
> with:
> 
> ```
> pip install torch==2.3.0+cu121 torchaudio==2.3.0+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
> ```

Thank you!!!! I used this method and the error below was resolved and audio was generated normally.

`You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50359]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.`
