### ISSUE TITLE
Support for the persian language 

### ISSUE THREAD

**Issue by tavallaie** [SWivid/F5-TTS#21]
Hi, I wonder how I can add Persian to this awesome project. Is there any manual for training? Making dataset or aid for training? 
I would like to contribute despite there being no good open source tts for Persian.

**Comment by SWivid** [comment]
We are very pleased to have you participate in this project.
You may also refer to #5 #12 #16 for some guidance.

**Comment by ZhikangNiu** [comment]
I'll close this issue, if you have other questions you can reopen this issue. @tavallaie
