### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by PierrunoYT** [SWivid/F5-TTS#212]
![grafik](https://github.com/user-attachments/assets/2b095717-b55b-497f-9516-9da3cf817bcf)

**Comment by SWivid** [comment]
![image](https://github.com/user-attachments/assets/a4506229-54e3-4890-be5f-267c5430116b)
Seems you have not setup `accelerate config` which is mentioned in readme

**Comment by PierrunoYT** [comment]
Im using it with Pinokio

**Comment by SWivid** [comment]
> Im using it with Pinokio

Not sure if pinokio also compatible with training/finetuning.

If you just want to do inference, use `gradio_app.py` and `inference-cli.py`

**Comment by PierrunoYT** [comment]
> > Im using it with Pinokio
> 
> 
> 
> Not sure if pinokio also compatible with training/finetuning.
> 
> 
> 
> If you just want to do inference, use `gradio_app.py` and `inference-cli.py`

Yes it is but something went wrong.

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions~
