### ISSUE TITLE
对中文的使用拼音写的文字，转义效果不好

### ISSUE THREAD

**Issue by sc-lj** [SWivid/F5-TTS#215]
比如，“采用jieba分词工具进行分词”，中对“jieba“ TTS完全识别不到是中文的读法jieba， 二是使用英文读法了。
这个有什么方式改善吗？

**Comment by SWivid** [comment]
可以在输入文本时把`jieba`换成`结巴`

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
