### ISSUE TITLE
ONNX Version of Models

### ISSUE THREAD

**Issue by amblamps** [SWivid/F5-TTS#22]
Hi, thank you for sharing these models, the quality of the output is amazing! Is there any chance of an ONNX release?

**Comment by SWivid** [comment]
Not sure if onnx inference would be slow, and it is very possible that we will publish updated ckpt (e.g. more language support)

If anyone is familiar with onnx and interested, welcome to pr

**Comment by amblamps** [comment]
ONNX does not yet support ISTFT needed for Vocos. There are a couple of workarounds.

https://github.com/gemelo-ai/vocos/issues/38

**Comment by mush42** [comment]
Hi

For ONNX support we can use WaveNeXt which is based on Vocos but it does not use the istft component.

Unless the tokenizer is separated, exporting to ONNX will not be that useful. The whole point is to have a minimal inference-only package that does not require pytorch.

**Comment by SWivid** [comment]
#214 @DakeQQ got a onnx version.
Will move to there with onnx discussion, closing this issue~
