### ISSUE TITLE
convert_char_to_pinyin doesn't tokenize the input string?

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#220]
I noticed the function convert_char_to_pinyin wasn't correctly tokenizing my text according to my vocab. This only affects custom vocabs, but the function was returning every word as a token, even though those words aren't tokens in my vocab.

I had to create my own tokenization script.

**Comment by SWivid** [comment]
Yes, customed tokenizer is needed to match for changes.
