### ISSUE TITLE
CUDA OOM during training, after some steps

### ISSUE THREAD

**Issue by vu-the-dung** [SWivid/F5-TTS#223]
Hi, I notice GPU mem usage keeps increasing during training
I'm training on 1x A5000 24GB, dataset ~300h contains of 0.2-49s audio files

My train.py settings: 
batch_size_per_gpu = 1500
batch_size_type = "frame"
max_samples = 64

At start, GPU mem usage ~9GB, after some x10000 steps, GPU mem usage increases to ~16GB, after some another x10000 steps, GPU mem usage increases to ~22GB, then eventually leads to OOM
If I resume training, this phenomenon repeat

Is this intended or a bug somewhere?

**Comment by SWivid** [comment]
cuz attention as a quadratic mem cost,
need to adjust current rough batchsampler taking longer samples into consideration, e.g. dynamically adjust threshold, smaller for longer samples.

**Comment by SWivid** [comment]
#233 might help

**Comment by vu-the-dung** [comment]
i changed constraint < 0.3 to < 0.2, use bf16 precision. So far VRAM usage seems stable, no OOM yet. So I'll close this issue
