### ISSUE TITLE
Podcast vs Multi-Style Tabs on Gradio App?

### ISSUE THREAD

**Issue by chigkim** [SWivid/F5-TTS#229]
@SWivid @jpgallegoar @JarodMica @lpscr @cocktailpeanut, are there any difference in multi-style and podcast tabs other than markup format?

### Podcast
Speaker1: Hello
Speaker2: Hi
...

### Multi-Style
(Speaker1_Happy) Hello
(Speaker2_Sad) Hi
(Speaker1_Main) What's going on?
...

If that's the only difference, maybe delete Podcast tab, and rename multi-style to multi-voice, clarify the usage, and have people to use for both.
Multi-style is much more flexible than podcast tab anyways.

Thoughts?

**Comment by SWivid** [comment]
Yes, you could just remove it.
thought 
```
Multi-Style
(Speaker1_Happy) Hello
(Speaker2_Sad) Hi
(Speaker1_Main) What's going on?
```
is great, with newline is more clear

**Comment by chigkim** [comment]
Also, I'm thinking it should use characters less likely to encounter in the main text to markup voices?
Maybe, <Speaker-1> instead of (Speaker1)?

**Comment by chigkim** [comment]
Oops, Github stripped the characters. lol
Maybe, `<Speaker-1>` instead of (Speaker1)?

**Comment by SWivid** [comment]
> `<Speaker1>` instead of (Speaker1)?

or `|<Speaker1>|`

**Comment by jpgallegoar** [comment]
Changed the multi speech type token to "{" and "}", hope that is better. Will close the issue, feel free to reopen if needed.

**Comment by jpgallegoar** [comment]
Also, I can't delete Podcast because I didn't create it, it would not be right.

**Comment by jpgallegoar** [comment]
@RootingInLoad

**Comment by SWivid** [comment]
Thought will just be fine, cuz the basic structure of chunk inference is done by @RootingInLoad .
We could take the best for user experience and properly updating the credit part

**Comment by chigkim** [comment]
@RootingInLoad, Would it be okay to consolidate the Podcast tab into the Multi-Style tab and remove the Podcast tab?
Currently, the Multi-Style tab is described as being for emotions, but it actually can do the same thing as the Podcast tab, just with a different markup format. It's also more flexible and has additional features.
I believe updating the instructions/description for the Multi-Style tab could simplify the user experience. What do you think?
Thanks!

**Comment by jpgallegoar** [comment]
I agree we could improve the experience by consolidating those and improving instructions. Perhaps even make the creation of said scripts easier by making the {Speaker} tags appear with the click of an individual button each speaker can have.

**Comment by SWivid** [comment]
@chigkim @jpgallegoar @RootingInLoad 
I will just switch to a new repo structure, which is more fine-grained, and with pip pkg support

**Comment by jpgallegoar** [comment]
@SWivid Sounds great!

**Comment by RootingInLoad** [comment]
Hello everyone, you can do everything you desire with the Podcast Generation feature. 
When I created it, it was because F5-TTS just came out, and that I wanted to try that feature out. 

You can remove/modify/revamp it in any way, shape or form.

I do not really care about credits, I'm not here for fame haha, only to help the community !
