### ISSUE TITLE
i got these error when train data

### ISSUE THREAD

**Issue by ChibiChubu** [SWivid/F5-TTS#231]
accelerate launch finetune-cli.py --exp_name F5TTS_Base --learning_rate 1e-05 --batch_size_per_gpu 3200 --batch_size_type frame --max_samples 6 --grad_accumulation_steps 1 --max_grad_norm 1 --epochs 10 --num_warmup_updates 2 --save_per_updates 2 --last_per_steps 10 --dataset_name gegurl --finetune True
Fatal Python error: config_init_hash_seed: PYTHONHASHSEED must be "random" or an integer in range [0; 4294967295]
Python runtime state: preinitialized
![image](https://github.com/user-attachments/assets/661d3943-7659-4ec3-84a2-ee5c492a31ed)

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions~

**Comment by RASPIAUDIO** [comment]
hi, I have the same issue. 
I firsst tried a very small corpus and it was working, then larger and got this error.

**Comment by juangea** [comment]
I have the same error, no idea why

**Comment by justinjohn0306** [comment]
Try reopening the terminal

**Comment by juangea** [comment]
Yeah, that helped, thanks
