### ISSUE TITLE
Ability to specify finetuned model in the Gradio app

### ISSUE THREAD

**Issue by danielw97** [SWivid/F5-TTS#232]
Hello,
I've come to this repo recently, so apologies if I've missed something here.
Things sound great, although I'm currently doing some finetuning tests from the original f5tts checkpoint with the gradio finetuning app.
One feature that would be great is an ability to specify a custom checkpoint in the gradio_app.py if possible, maybe in the advanced settings?
That way a finetuned checkpoint can be used more easily.
If this feature is already available, do please let me know and thank you again for your work so far on this.
Thanks in advance.

**Comment by SWivid** [comment]
https://github.com/SWivid/F5-TTS/blob/32c3ee77017d728321ffaa5d10e9f9f6cd44f20d/gradio_app.py#L48
Could temporarily change `str(cached_path("hf://SWivid/F5-TTS/F5TTS_Base/model_1200000.safetensors")` to `<YOUR_CKPT>.

Maybe someone to add an on-the-fly selection feature to gradio, welcome PR

**Comment by lpscr** [comment]
@danielw97 check new update in gradio finetune now you can change the model you want https://github.com/SWivid/F5-TTS/discussions/143

**Comment by SWivid** [comment]
will close as solved, feel free to open if further questions

**Comment by SWivid** [comment]
will close as solved, feel free to open if further questions

**Comment by Archviz360** [comment]
where is Model: local_path | hf://user_id/repo_id/model_ckpt located??
