### ISSUE TITLE
No Synthesized Audio

### ISSUE THREAD

**Issue by trunks970** [SWivid/F5-TTS#238]
Not sure if I should post this here or elsewhere but im very new to programs like this and whenever i upload a reference audio then attempt to synthesize it I get nothing, I should mention I am using Pinokio. I also plan on trying this software of my much much much better pc at home to see if theres a difference.
![fail ](https://github.com/user-attachments/assets/ddf517ab-405f-4004-8410-80c54e7485df)

**Comment by SWivid** [comment]
Use lower case as we suggested in readme, or you are telling model to read letter by letter
Also check if reference audio uploaded correctly, will show waveform if so

**Comment by trunks970** [comment]
> Use lower case as we suggested in readme, or you are telling model to read letter by letter Also check if reference audio uploaded correctly, will show waveform if so

done both unfortunately no success

**Comment by SWivid** [comment]
@trunks970 some similar issues,
try online space demo in huggingface/modelscope.

Probably with whisper asr failure or network stuffs...

**Comment by trunks970** [comment]
> @trunks970 some similar issues, try online space demo in huggingface/modelscope.
> 
> Probably with whisper asr failure or network stuffs...

so a few things got it to work on my pc (3070) but was still unable to get it to work on my laptop (1650) im not too sure what the difference would be but i reinstalled pinokio on both to try to fix it all in all im satisfied ill use the online version on my laptop whenever i can 

Thanks for your help
