### ISSUE TITLE
The audio synthesized by the model I trained myself has no sound

### ISSUE THREAD

**Issue by JackZ2024** [SWivid/F5-TTS#239]
I have a Thai dataset of more than 5 hours, and I trained 160k. The audio inferred by the model has no sound. What could be the reason?
@SWivid

**Comment by SWivid** [comment]
Hi @JackZ2024 , could you elaborate more on the issue?
e.g. provide generated samples and used prompt audio, ref_text and gen_text
and maybe also the vocab.txt?

**Comment by JackZ2024** [comment]
Hi@SWivid 
The following is a screenshot of the generated results:
![image](https://github.com/user-attachments/assets/29a6a4a0-a7e6-4d9f-9e84-e6c06e311a0e)

The prompt audio: [https://vocaroo.com/1oAVlIkSw2KG](https://vocaroo.com/1oAVlIkSw2KG)
No reference text。
gen_text: หากเจ้าเพียงแต่หลับตา และพ้นคำพูดที่จำเจสำสร้างออกมา
vocab file: 
[vocab.txt](https://github.com/user-attachments/files/17532859/vocab.txt)

Should I modify the convert_char_to_pinyin function for Thai?

**Comment by SWivid** [comment]
> Should I modify the convert_char_to_pinyin function for Thai?

The current tokenize can support Thai.
However the vocab.txt should be checked and modifed to your need, **making sure not vocab for Thai is left out**, e.g. พี in not in the vocab.txt of pretrained model.
You might see though #57 #143

**Comment by elisa12323** [comment]
have you fixed it yet

**Comment by elisa12323** [comment]
Hi @JackZ2024
have you fixed it yet

**Comment by JackZ2024** [comment]
Hi, @elisa12323 
I'm sorry, I've been busy with other things recently and this problem has not been solved yet.

**Comment by SWivid** [comment]
will close here, move discussion to #356
