### ISSUE TITLE
ARPAbet phoneme pronunciation not working.

### ISSUE THREAD

**Issue by HaileyStorm** [SWivid/F5-TTS#241]
When I try to generate text with ARPAbet phones in parenthesis like you see in the "Specifying the pronunciation without model re-training" of https://www.microsoft.com/en-us/research/project/e2-tts/, it's not working, instead more attempting to pronounce it as you'd read it out unfamiliar with ARPAbet. This is with the E2 model.

**Comment by SWivid** [comment]
Our reproduced E2 model doesn't train with that scheme. Check E2 paper:
![image](https://github.com/user-attachments/assets/cad5427e-9794-4b85-8116-8d7411d07ccd)
We just use characters, no random replacement with g2p for English yet.
