### ISSUE TITLE
可以支持多少种音色？

### ISSUE THREAD

**Issue by WGS-note** [SWivid/F5-TTS#243]
请问：可以支持多少种音色？我如何切换不同的音色？谢谢！

**Comment by SWivid** [comment]
给不同音色的参考音频就行了
口音特别独特或者风格太强（超出训练集分布太多）的效果可能没那么好
一般的都还行的

**Comment by WGS-note** [comment]
谢谢！

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions~
