### ISSUE TITLE
How can I tokenize text into the desired size using the code in this repository?

### ISSUE THREAD

**Issue by PhamDangNguyen** [SWivid/F5-TTS#257]
**I get an error when i run inference-cli.py with my code:**
python inference-cli.py \
--model "F5-TTS" \
--ref_audio "/home/pdnguyen/TTS/F5-TTS/notebooks/data/fine-tune/wavs/chunk_2.wav" \
--ref_text "Trẻ trung với giàu  nhiều nhiệt huyết  ạ ạ. Tôi có thể kể đến lúc đó chị Nguyễn Thị doan còn là hiệu trưởng đại học Bách" \
--gen_text "Tôi là Nguyên" \
--vocab_file "notebooks/out_data/vocab.txt"

### after that I get an error:
  **size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2546, 512]) from checkpoint, the shape in current model is torch.Size([88, 512]).**
  
 I modified the tokenizer code for Vietnamese by replacing 'convert_char_to_pinyin' with 'convert_char_to_pinyin' function. 
 code in:
 ```
def convert_words_to_char_Vi_En(text_list, polyphone=True):
    final_text_list = []
    custom_trans = str.maketrans({";": ","})  # add custom trans here, to address oov
    for text in text_list:
        char_list = []
        text = text.translate(custom_trans)
        for seg in list(text):
            seg_byte_len = len(bytes(seg, "UTF-8"))
            if seg_byte_len == len(seg):  # if pure alphabets and symbols
                if char_list and seg_byte_len > 1 and char_list[-1] not in " :'\"":
                    char_list.append(" ")
                char_list.extend(seg)
            else: #Vietnamese
                for c in seg:
                    char_list.append(c)
        final_text_list.append(char_list)
        print("--------------------------------------------nguyen--------------------------------------")
        print(char_list)

    return final_text_list
```
    
Then I get a vocab.txt with 88 elements. How can i get 2546 elements in vocab.txt for train and infer ??

**Comment by SWivid** [comment]
Hi @PhamDangNguyen . You could just reuse the original vocab.txt if the 88 elements are included in that.
If miss some, you could manually replace some vocab you don't want with your own.

**Comment by PhamDangNguyen** [comment]
> Hi @PhamDangNguyen . You could just reuse the original vocab.txt if the 88 elements are included in that. If miss some, you could manually replace some vocab you don't want with your own.

this is mean I can't using my vocab.txt (which 88 elements). Instead that I must replace some origin vocab's element ?

**Comment by SWivid** [comment]
@PhamDangNguyen Sure, or you could just use the code, and train from scratch

**Comment by PhamDangNguyen** [comment]
> @PhamDangNguyen Sure, or you could just use the code, and train from scratch

please show me path to load pre-train model in your repo!! I don't find it :v

**Comment by PhamDangNguyen** [comment]
@SWivid  Is this checkpoint_path in the Trainer class?
```
self.epochs = epochs
        self.num_warmup_updates = num_warmup_updates
        self.save_per_updates = save_per_updates
        self.last_per_steps = default(last_per_steps, save_per_updates * grad_accumulation_steps)
        self.checkpoint_path = default(checkpoint_path, "ckpts/test_e2-tts")

        self.batch_size = batch_size
        self.batch_size_type = batch_size_type
        self.max_samples = max_samples
        self.grad_accumulation_steps = grad_accumulation_steps
        self.max_grad_norm = max_grad_norm
```

**Comment by SWivid** [comment]
@PhamDangNguyen have you got through training readme yet?
https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train

**Comment by PhamDangNguyen** [comment]
@SWivid I know you're using a pre-trained model, but currently, after reviewing the code, I haven’t found where the code loads the pre-trained model. Could you please show me? Thank you!

**Comment by SWivid** [comment]
Ah we refer to F5/E2 TTS as pretrained model lol

**Comment by PhamDangNguyen** [comment]
@SWivid This mean have not pre-train check-point to load here. I still train from scratch, but architecture is F5-TTS bruh

**Comment by PhamDangNguyen** [comment]
@SWivid This means have not pre-train check-point to load here. I still train from scratch, but architechture is F5-TTS bruh?

**Comment by SWivid** [comment]
@PhamDangNguyen We have the link https://github.com/SWivid/F5-TTS?tab=readme-ov-file#news
And we have mentioned the ckpt_file path in 

>@PhamDangNguyen have you got through training readme yet?
https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train

And you said that want to use a custom vocab.txt rather than reuse our vocab.txt which is matched to our pretrained model.
Thus I see not big evidence the point to load a pretrained model ckpt

**Comment by vu-the-dung** [comment]
@PhamDangNguyen if you run inference-cli.py without providing your own checkpoint path in --ckpt_file, it will load F5/E2 TTS pretrained checkpoint as default
https://github.com/SWivid/F5-TTS/blob/6a104b4025eba819b078c40a2134d675fc387af2/src/f5_tts/infer/infer_cli.py#L120

For training, the Trainer will check for a .pt checkpoint in /ckpts/F5TTS_Base/ , it's implemented in /model/trainer.py 
https://github.com/SWivid/F5-TTS/blob/6a104b4025eba819b078c40a2134d675fc387af2/src/f5_tts/model/trainer.py#L137

**Comment by PhamDangNguyen** [comment]
I got it. The problem may be solved. Thanks
