### ISSUE TITLE
How to optimize the mispronunciation of Chinese polyphonic characters

### ISSUE THREAD

**Issue by LSliu666** [SWivid/F5-TTS#259]
How to optimize the mispronunciation of Chinese polyphonic characters

**Comment by SWivid** [comment]
@LSliu666 Hi, see #193

**Comment by LSliu666** [comment]
Okay, thank you。Is there any optimization in determining the pronunciation of polyphonic characters based on specific phrases @SWivid

**Comment by SWivid** [comment]
@LSliu666 Mainly for dataset.
A good dataset covering most cases and transcribed just correctly will let model do better on this.

**Comment by LSliu666** [comment]
我使用的是gradio,给的文本怎么标明拼音，这样就不会读错了

**Comment by LSliu666** [comment]
I am using Gradio. How to indicate the pinyin of the text so that I won't read it incorrectly

**Comment by LSliu666** [comment]
@SWivid

**Comment by SWivid** [comment]
Currently no such feature in Gradio yet. Welcome PR~

**Comment by LSliu666** [comment]
Is code inference possible？

**Comment by SWivid** [comment]
What do you mean with `code inference`, the `infer-cli`?

**Comment by LSliu666** [comment]
yes

**Comment by SWivid** [comment]
Yes, it is just as we suggest above

> Need to see through the code, part as in https://github.com/SWivid/F5-TTS/issues/193.

Or simple you could do like:
好奇 -> 浩奇

**Comment by LSliu666** [comment]
f5-tts_infer-cli \
--model "F5-TTS" \
--ref_audio "ref_audio.wav" \
--ref_text "The content, subtitle or transcription of reference audio." \
--gen_text "Some text you want TTS model generate for you."
Fill in Pinyin in gen_text

**Comment by LSliu666** [comment]
Yeah, I can change the homophone to his homophone.thanks

**Comment by LSliu666** [comment]
Pursuing accurate pronunciation rather than word accuracy, haha, interesting

**Comment by SWivid** [comment]
> @LSliu666 Mainly for dataset. A good dataset covering most cases and transcribed just correctly will let model do better on this.

@LSliu666 Or you could just provide us with some data, we will take that to training.

**Comment by LSliu666** [comment]
Sorry, I don't have any relevant data

**Comment by LSliu666** [comment]
> 追求发音准确而不是单词准确，哈哈，音符

The meaning of this is that I have found an alternative method for mispronouncing polyphonic characters, which is to replace the Chinese character of a polyphonic character with its homophone, so that its pronunciation is correct, pursuing consistency in pronunciation without worrying about whether the character is correct. Just like 穿着 can read as chuanzhe，If I write 穿卓 can read as chuanzhuo this is the right place to study

**Comment by SWivid** [comment]
@LSliu666 Sure, hope this temporary strategy would help.
We don't mean to limit model's ability on that, rather the model is limit with dataset (if you could just provide a bunch of perfect data, we could just train with unicodes and let model learn semantic things itself)

Feel free to open issue if further questions.

**Comment by LSliu666** [comment]
Okay, thank you for your answer

**Comment by leonjin819** [comment]
https://github.com/SWivid/F5-TTS/issues/664
