### ISSUE TITLE
Not able to produce good quality output with other reference audio

### ISSUE THREAD

**Issue by smallsudarshan** [SWivid/F5-TTS#26]
I am running the `test_infer_single.py`. I have downloaded the checkpoints correctly and the default script works for me. 

But it does not work for me when I change the reference to anything else.

This is the speaker reference that I added - [Ref Wav File](https://drive.google.com/file/d/1GKcFsvZrH_C5Kq0q0xIkmUEpNyH8DR4g/view?usp=sharing)

Post this, I changed these lines in the `test_infer_single.py`:

```
ref_audio = "tests/ref_audio/jessica-01.wav"
ref_text = "Hey there, how are you doing?"
gen_text = "I really missed you! Care for some coffee?"
```

This is the output I get - [Output Wav File](https://drive.google.com/file/d/1agw0mkIBH6W5EDzzvaxgwLtMzr17JAEF/view?usp=sharing)

**Comment by SWivid** [comment]
Remember to check if you set `fix_duration` right, refer to [README.md, single inference part](https://github.com/SWivid/F5-TTS?tab=readme-ov-file#single-inference)

**Comment by smallsudarshan** [comment]
So setting it to `None` worked @SWivid , then would it make sense to keep that as default?

**Comment by SWivid** [comment]
> So setting it to `None` worked @SWivid , then would it make sense to keep that as default?

We wish we could, though the linearly estimated duration for inference example will exceed 30s lol (as there's long silence).
