### ISSUE TITLE
Is the new packaged version compatible with Huggingface Spaces and Pinokio?

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#260]
Thanks for your efforts @SWivid in transforming the app. However the new version has broken the apps available on huggingface and pinokio. Do you know if its possible to use packaged apps there?

**Comment by SWivid** [comment]
@jpgallegoar Hi, it's basically for sync_f5 used previous setup way
We move to `pyproject.toml` and not with `requirement.txt` now

@fakerybakery might help with the tweak things

**Comment by jpgallegoar** [comment]
@cocktailpeanut

**Comment by jpgallegoar** [comment]
> @jpgallegoar Hi, it's basically for sync_f5 used previous setup way We move to `pyproject.toml` and not with `requirement.txt` now
> 
> @fakerybakery might help with the tweak things
> 
> Ah! It is needed to have a app.py outside? Will take care of that.

And will you delete the Podcasts tab then? And change instructions for MultiSpeechType to make it more generalized

**Comment by SWivid** [comment]
> Ah! It is needed to have a app.py outside? Will take care of that.

try with just `infer_gradio.py` inside, will work if done `pip install -e .`

**Comment by SWivid** [comment]
@jpgallegoar initial prune done. That convenient button to add `{stype}` not yet

**Comment by fakerybakery** [comment]
> @jpgallegoar Hi, it's basically for sync_f5 used previous setup way We move to `pyproject.toml` and not with `requirement.txt` now
> 
> @fakerybakery might help with the tweak things

Hi,
Sorry about the issues! The Space should be running again.

> Ah! It is needed to have a app.py outside? Will take care of that.

The app.py file doesn't need to be outside, as when syncing the repo to the Space it (should) move the files to the correct location.

Thanks!

**Comment by cocktailpeanut** [comment]
I've updated the pinokio script to the new install&launch method https://github.com/pinokiofactory/e2-f5-tts/commit/920295d86e7e8ea76035c5548b17a55999d2bf72

I understand why this had to be done, hopefully the commands won't change again in the future, or if it does, ensure that things are backward compatible.

**Comment by SWivid** [comment]
#274 
> Saw pinokio updated! Maybe we could take the current version as v1.0.0 lol
We will ensure backward compatibility to this start point (and it's very possible that no change to whole structure will be made after)

will close as solved~
