### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for CFM

### ISSUE THREAD

**Issue by liuhui881125** [SWivid/F5-TTS#261]
Download Vocos from huggingface charactr/vocos-mel-24khz
vocab :  /root/F5-TTS/src/f5_tts/infer/examples/vocab.txt
tokenizer :  custom
model :  /root/F5-TTS/ckpts/F5TTS_Base/model_1200000.safetensors 

Traceback (most recent call last):
  File "/root/anaconda3/envs/E2F5/bin/f5-tts_infer-gradio", line 5, in <module>
    from f5_tts.infer.infer_gradio import main
  File "/root/F5-TTS/src/f5_tts/infer/infer_gradio.py", line 51, in <module>
    E2TTS_ema_model = load_model(
  File "/root/F5-TTS/src/f5_tts/infer/utils_infer.py", line 172, in load_model
    model = load_checkpoint(model, ckpt_path, device, use_ema=use_ema)
  File "/root/F5-TTS/src/f5_tts/infer/utils_infer.py", line 137, in load_checkpoint
    model.load_state_dict(checkpoint["model_state_dict"])
  File "/root/anaconda3/envs/E2F5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CFM:
Missing key(s) in state_dict: "transformer.layers.0.1.g", "transformer.layers.0.2.to_q.weight",……
Unexpected key(s) in state_dict: "transformer.transformer_blocks.0.attn.to_k.bias", "transformer.transformer_blocks, ……
        size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2546, 512]) from checkpoint, the shape in current model is torch.Size([2546, 100]).
        size mismatch for transformer.input_embed.proj.weight: copying a param with shape torch.Size([1024, 712]) from checkpoint, the shape in current model is torch.Size([1024, 300]).

**Comment by liuhui881125** [comment]
who can help me？ 求教。

**Comment by SWivid** [comment]
Thought fixed with #262

**Comment by liuhui881125** [comment]
> Thought fixed with #262

no change

**Comment by liuhui881125** [comment]
After rolling back this commit, it can run, but the generated file is a current sound. [46d391a](url) [](https://github.com/SWivid/F5-TTS/commit/46d391a8766d8eabb967b326ccb473bc2d8b9a6c)

**Comment by liuhui881125** [comment]
> Thought fixed with #262
> 
> question seems edited, you could provide infos of what you have modified, otherwise hard to find solution

哥，帮忙看一下呗，非常感谢。

**Comment by liuhui881125** [comment]
> > Thought fixed with #262
> > question seems edited, you could provide infos of what you have modified, otherwise hard to find solution
> 我这里不能科学上网，就把所有从hf下载的东西都改成绝对路径了，一共三个地方，
1./usr/local/lib/python3.10/site-packages/vocos/pretrained.py  67/68 两行
2.utils_infer.py  108行
3.gradio_app.py  49/54行

**Comment by liuhui881125** [comment]
@SWivid 大哥，帮忙看下吧

**Comment by SWivid** [comment]
@liuhui881125 
建议重新安装一下这些包，像是vocos，以及重构repo之后的f5-tts


> RuntimeError: Error(s) in loading state_dict for CFM:
> Missing key(s) in state_dict: "transformer.layers.0.1.g", "transformer.layers.0.2.to_q.weight",……
> Unexpected key(s) in state_dict: "transformer.transformer_blocks.0.attn.to_k.bias", "transformer.transformer_blocks, ……
> size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2546, 512]) from checkpoint, the shape in current model is torch.Size([2546, 100]).
> size mismatch for transformer.input_embed.proj.weight: copying a param with shape torch.Size([1024, 712]) from checkpoint, the shape in current model is torch.Size([1024, 300]).

看上去像是你手动改了模型的参数或者某些结构的 命名/位置 导致的
你这里的报错712的维度即512+2*100，像是f5的模型权重文件；但你想要load进e2的模型结构里？
你可以先确认下是不是搞错了这个，f5的权重应该往f5的模型里放，e2的权重往e2的模型里放

**Comment by liuhui881125** [comment]
非常感谢，确实是由于我的e2和f5指向了错误的路径。

> @liuhui881125 建议重新安装一下这些包，像是vocos，以及重构repo之后的f5-tts
> 
> > RuntimeError: Error(s) in loading state_dict for CFM:
> > Missing key(s) in state_dict: "transformer.layers.0.1.g", "transformer.layers.0.2.to_q.weight",……
> > Unexpected key(s) in state_dict: "transformer.transformer_blocks.0.attn.to_k.bias", "transformer.transformer_blocks, ……
> > size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2546, 512]) from checkpoint, the shape in current model is torch.Size([2546, 100]).
> > size mismatch for transformer.input_embed.proj.weight: copying a param with shape torch.Size([1024, 712]) from checkpoint, the shape in current model is torch.Size([1024, 300]).
> 
> 看上去像是你手动改了模型的参数或者某些结构的 命名/位置 导致的 你这里的报错712的维度即512+2*100，像是f5的模型权重文件；但你想要load进e2的模型结构里？ 你可以先确认下是不是搞错了这个，f5的权重应该往f5的模型里放，e2的权重往e2的模型里放

非常感谢，确实是我绝对路径指向错误。
