### ISSUE TITLE
有可能实现多个句子在一个batch中同时推理么

### ISSUE THREAD

**Issue by justzmq** [SWivid/F5-TTS#264]
对于一些长文本，代码中是先将文本分割，然后在循环中推理这些分割的句子，但这样速度很慢，当前的模型结构有可能做到在一个batch中同时推理多个句子么，这样速度应该会提升很多。

**Comment by SWivid** [comment]
可以，但是需要加mask，不一定会快

**Comment by justzmq** [comment]
> 可以，但是需要加口罩，不一定会快

感谢大佬回复！那么之后有测试或者添加这个功能的计划么，有的话我会持续关注的😊

**Comment by SWivid** [comment]
@justzmq 现有的code已经支持这种形式的inference（即batch，可以看`cfm.py`的`sample()`函数
只是如上面所说，因为一个batch里长短不一样所以要加mask有额外开销

目前用fp16推理速度已经还不错的，这些更多是工程上的优化。欢迎PR~~

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
