### ISSUE TITLE
convert_char_to_pinyin(text_list) 生成的拼音和最终生成语音结果不符

### ISSUE THREAD

**Issue by JiajunDou** [SWivid/F5-TTS#266]
> 我们的技术完全没有被全世界落下。
> [['wo3', ' ', 'men', ' ', 'de', ' ', 'ji4', ' ', 'shu4', ' ', 'wan2', ' ', 'quan2', ' ', 'mei2', ' ', 'you3', ' ', 'bei4', ' ', 'quan2', ' ', 'shi4', ' ', 'jie4', ' ', 'la4', ' ', 'xia4', '。']]

上一个F5-TTS打死读成luo4 xia4

这个版本的F5-TTS打死读成le4 xia4

**Comment by SWivid** [comment]
@JiajunDou 我试了下这个case确实有问题，而且暂时没有很好的解决方案

应该是训练集里`落下`基本只有`luo4 xia4`读法的语音（尽管文本在转拼音时候会既有`luo4 xia4`也有`la4 xia4`），所以模型在这两个词一起出现时候，都会对应成`luo4 xia4`的读法
而像是`蜡烛`->`la4 zhu2`就可以正常读对`la4`

这种需要在包含正确读法对应的数据上微调或重训

**Comment by JiajunDou** [comment]
@SWivid 感谢回复，看来遇到类似问题只能自己微调了， 关于落下我又测试了几遍，这个版本的确是读le4 xia4

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
