### ISSUE TITLE
推理的音频偶现叠音或吞字

### ISSUE THREAD

**Issue by Narcooo** [SWivid/F5-TTS#267]
我使用了main.flac这个作为ref_audio，同时拿掉了输入的ref_text使用了whisper转录，在我自己测试的样例上他会出现类似于’如果果‘，‘存存在于’的音频，出现的位置相对随机（不在chunk的首尾），亦或者是'存于'，这个问题怎么缓解呢。

**Comment by SWivid** [comment]
有具体使用的gen_text和failure的生成结果作为分析参考吗？

**Comment by Narcooo** [comment]
如果你低头看看手机，会发现很多存在于现实世界的物体已经被吸纳到地图，计算器，邮件，时钟，当然还有很多人的钱包中。这种数字化转型不仅改变了我们的生活方式，更让 smart device 成为连接物理世界和 digital world 的桥梁。Future Tech 的研究表明，超过百分之八十的 daily tasks 已经可以通过 mobile phone 完成。这是gen_text，这里计算器的器没了。叠字是类似的，听上去很自然的读了两次。
[segment_0000_A.wav.zip](https://github.com/user-attachments/files/17524282/segment_0000_A.wav.zip)

**Comment by SWivid** [comment]
@Narcooo 这是模型目前存在的缺陷，没有显式做对齐，会吞字。叠字在我们之前的测试里基本没有出现，可能是因为code-switch的影响。
临时的解决方案是通过re-rank（即多抽几次卡，因为根据我们的实验结果F5的吞字主要是对齐还不够强带来的，没有像E2那样耦合导致一些集外情况re-rank也无法解决）
我们也在重点看这个问题，希望之后的版本能更好解决~

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
