### ISSUE TITLE
KeyError: 'model_state_dict' when using test_train.py

### ISSUE THREAD

**Issue by JarodMica** [SWivid/F5-TTS#27]
Hey guys, appreciate the project, the model has been great so far!

So I've set up a dataset to be compatible with dataset.py, set the parameters inside of the test_train.py, and on trying to load F5TTS_Base, it seems like it's missing some keys:

```
Exception has occurred: KeyError
'model_state_dict'
  File "C:\Users\jarod\OneDrive\Desktop\code\F5-TTS\model\trainer.py", line 154, in load_checkpoint
    self.accelerator.unwrap_model(self.model).load_state_dict(checkpoint['model_state_dict'])
                                                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jarod\OneDrive\Desktop\code\F5-TTS\model\trainer.py", line 240, in train
    start_step = self.load_checkpoint()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jarod\OneDrive\Desktop\code\F5-TTS\test_train.py", line 85, in main
    trainer.train(train_dataset,
  File "C:\Users\jarod\OneDrive\Desktop\code\F5-TTS\test_train.py", line 92, in <module>
    main()
KeyError: 'model_state_dict'
```

Were the pretrained models distilled down to remove these keys? If so, got any tips for loading it up into further training?

I played around with just trying to load ema_model_state_dict, but it seems like I ended up just starting from scratch with this.

Related to https://github.com/SWivid/F5-TTS/issues/16

**Comment by SWivid** [comment]
Ah yes, we just leave ema_state_dict without other things to make it neat.
Just copy from `checkpoint['ema_model_state_dict]` to `checkpoint['model_state_dict]`, renaming prefix `model` to `ema_model`

**Comment by JarodMica** [comment]
Thanks for the response!  So I made the modifications:

```

**Comment by JarodMica** [comment]
Thanks for the response!

So I made the modifications:
```
def load_checkpoint(self):
        if not exists(self.checkpoint_path) or not os.path.exists(self.checkpoint_path) or not os.listdir(self.checkpoint_path):
            return 0
        
        self.accelerator.wait_for_everyone()
        if "model_last.pt" in os.listdir(self.checkpoint_path):
            latest_checkpoint = "model_last.pt"
        else:
            latest_checkpoint = sorted(os.listdir(self.checkpoint_path), key=lambda x: int(''.join(filter(str.isdigit, x))))[-1]
        # checkpoint = torch.load(f"{self.checkpoint_path}/{latest_checkpoint}", map_location=self.accelerator.device)  # rather use accelerator.load_state ಥ_ಥ
        checkpoint = torch.load(f"{self.checkpoint_path}/{latest_checkpoint}", map_location="cpu")
        print("Checkpoint keys:", checkpoint.keys())

        # self.accelerator.unwrap_model(self.model).load_state_dict(checkpoint['ema_model_state_dict'])
        # self.accelerator.unwrap_model(self.optimizer).load_state_dict(checkpoint['optimizer_state_dict'])


        if self.is_main:
            self.ema_model.load_state_dict(checkpoint['ema_model_state_dict'])
            
        self.ema_model.copy_params_from_ema_to_model()

        # if self.scheduler:
        #     self.scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
        
        # step = checkpoint['step']
        step = 0
        
        del checkpoint; gc.collect()
        return step
```

And training seems to be running.

I did set the model to save just to try it out and make sure it's still working, so after 100 steps, the model still outputs comprehensible speech so I think we're good here

**Comment by SWivid** [comment]
I will test on it, but place the loading in init as we're using `accelerator` and `ema` is only recorded at main_process of ddp

**Comment by JarodMica** [comment]
Gotcha, thanks! @SWivid I also had a question in regards to Dataloader, any reason that ```persistent_workers=True``` is not being used here?

If not, on small dataset, the workers get reinitialized on each epoch, causing massive overhead if there are lots of workers.

I have set mine to True just to test it out here

**Comment by SWivid** [comment]
We just missed that. Thanks for mentioning this ~

**Comment by JarodMica** [comment]
> I will test on it, but place the loading in init as we're using `accelerator`, cuz `ema` is only recorded at main_process of ddp

When you mentioned this, would this be what you were thinking:
```
self.accelerator.init_trackers(
            project_name = wandb_project, 
            init_kwargs=init_kwargs,
            config={"epochs": epochs,
                    "learning_rate": learning_rate,
                    "num_warmup_updates": num_warmup_updates, 
                    "batch_size": batch_size,
                    "batch_size_type": batch_size_type,
                    "max_samples": max_samples,
                    "grad_accumulation_steps": grad_accumulation_steps,
                    "max_grad_norm": max_grad_norm,
                    "gpus": self.accelerator.num_processes,
                    "noise_scheduler": noise_scheduler}
            )

        self.model = model
        
        if self.is_main:
            self.ema_model = EMA(
                model,
                include_online_model=False,
                **ema_kwargs
            )
            self.ema_model.to(self.accelerator.device)
            
        self.epochs = epochs
        self.num_warmup_updates = num_warmup_updates
        self.save_per_updates = save_per_updates
        self.last_per_steps = default(last_per_steps, save_per_updates * grad_accumulation_steps)
        self.checkpoint_path = default(checkpoint_path, 'ckpts/test_e2-tts')
        self.load_checkpoint() # Load the checkpoint here

        self.batch_size = batch_size
        self.batch_size_type = batch_size_type
        self.max_samples = max_samples
        self.grad_accumulation_steps = grad_accumulation_steps
        self.max_grad_norm = max_grad_norm

        self.noise_scheduler = noise_scheduler

        self.duration_predictor = duration_predictor

        self.optimizer = AdamW(model.parameters(), lr=learning_rate)
        self.model, self.optimizer = self.accelerator.prepare(
            self.model, self.optimizer
        )```

**Comment by SWivid** [comment]
We currently deal it with 0d7b47bc3b7064ce1bdb4688392c9b907e4fbf3f
Give it a try~

**Comment by JarodMica** [comment]
Awesome, thank you! Appreciate the quick responses

**Comment by JarodMica** [comment]
Alright, I got around to trying https://github.com/SWivid/F5-TTS/commit/0d7b47bc3b7064ce1bdb4688392c9b907e4fbf3f and I got some missing keys (I'll put them all in a text file).  This I'm not too sure why and what's missing:
```
Exception has occurred: RuntimeError
Error(s) in loading state_dict for CFM:
	Missing key(s) in state_dict: "mel_spec.mel_stft.spectrogram.window", "mel_spec.mel_stft.mel_scale.fb", "transformer.time_embed.time_mlp.0.weight", "transformer.time_embed.time_mlp.0.bias", "transformer.time_embed.time_mlp.2.weight", "transformer.time_embed.time_mlp.2.bias",
```
[Missing_keys.txt](https://github.com/user-attachments/files/17354902/Missing_keys.txt)

Also, one other thing I wanted to note was that in the modifications here: https://github.com/SWivid/F5-TTS/issues/27#issuecomment-2408837536 even though it started training, when testing the inference of the model after 5k steps, the output audio model still sounded exactly the same as the base model with the same seed on inference.  I would have expected that even though its a small amount of data (1 hour of speaker data), something would change in inference, so I'm not too certain if this is correct either.

The graph looks like the below:
![image](https://github.com/user-attachments/assets/b813cc64-876d-483b-b3fc-07cc8a43549a)

**Comment by SWivid** [comment]
Try turn `use_ema = False`
We will try to figure out for missing keys.

**Comment by JarodMica** [comment]
> Try turn `use_ema = False` and see if the inference has some differences. We will try to figure out for missing keys.

Ah, yes after turning it to False, there are noticeable differences now! So if I understand correctly, when you guys removed the model_dict from the trained model, did you guys have to copy the params from model_dict to EMA? I can infer that EMA doesn't update/get trained during training.

**Comment by SWivid** [comment]
> I can infer that EMA doesn't update/get trained during training.

Thought it was updated, but still dominated by previous updates, say pretraining, as the finetune process just goes few updates.

**Comment by SWivid** [comment]
@JarodMica key error solved. 
Previously we replace replaced the prefix of keys, `ema_model.` with `model.`, though I should just be removed.
We fix this in 46d391a8766d8eabb967b326ccb473bc2d8b9a6c, and we did an actual run to make sure it is correct now.

**Comment by JarodMica** [comment]
Looks good to go, I have a finetune running now with the latest pull.  Appreciate it!

**Comment by yukiarimo** [comment]
Colab notebook for fine-tuning?
