### ISSUE TITLE
Any way to make voice more expressive?

### ISSUE THREAD

**Issue by Likkkez** [SWivid/F5-TTS#273]
Is there any value that can be tweaked to sacrifice stability but add more random expression? I'd love that if that's possible.

**Comment by SWivid** [comment]
Currently the control mechanism is just with reference audio.
As we are not fixing with a default value of random seed during the process of generation, you could simply get various (diverse to some extent) results.

Unlike autoregressive way of TTS modeling, it is not that convenient for non-autoregressive model to explicitly introduce "more" randomness.

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
