### ISSUE TITLE
Removed Requirments.txt and nodel folders

### ISSUE THREAD

**Issue by gjnave** [SWivid/F5-TTS#275]
Amazing app! Just curious, whats the reasoning for removing requirements.txt? and the models folder? Youve made the app uninstallable

thanks!

**Comment by SWivid** [comment]
Hi @gjnave , you could uninstall the pkg simply with `pip uninstall f5-tts`
And the `pyproject.toml` just fulfilled the role of `requirements.txt`.

**Comment by SWivid** [comment]
will closed as solved, feel free to open if further questions
