### ISSUE TITLE
How to completely uninstall?

### ISSUE THREAD

**Issue by WarmRainIdea** [SWivid/F5-TTS#279]
Thank you for making this amazing tool. I would like to know how to uninstall F5-TTS and its dependencies. Thank you very much!

**Comment by SWivid** [comment]
Maybe you could notice that there exists just a same issue #275 at first place before you start the issue?
Also
https://github.com/SWivid/F5-TTS/blob/e963929b8e6961a37f8321b788ca1969ad9ac4e0/README.md?plain=1#L103
