### ISSUE TITLE
where can I find setp by step tutorials on how to use this to make very clean and good voices please?

### ISSUE THREAD

**Issue by GPU-server** [SWivid/F5-TTS#290]

**Comment by ZhikangNiu** [comment]
If only inference, read the README
If train, check the https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train

**Comment by SWivid** [comment]
> *No description provided.*

Hi @GPU-server nice to see you again.
1. You need to check out README.md
2. Use neat reference audio rather than `not very clean and good` voice
3. Have you got new ideas or found exciting models? welcome to share with us.

**Comment by GPU-server** [comment]
I used to use RVC and get "pth" files(models) for training.
Ok questions for training:
1) Can we use .pth models (training from other tools) here?
2) are there training instructions in form of a video instead of the text guide?

Questions for inference:
1) I am reading the readme instructions for inference, (https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/infer)

>  However, you can provide infer_cli and infer_gradio with longer text, will automatically do chunk generation

- cli is the same as inference gradio except it is run from terminal, I mean both provides same features right? If yes I am sticking to gradio.
- I can use any text length and the code will take care for making it the right length, right?

>  Currently only load TTS models first, will load ASR model to do transcription if ref_text not provided, will load LLM model if use Voice Chat.

I don't understand this sentence.
- TTS models = pth files? It says "The script will load model checkpoints from Huggingface.", so there is only 2 models? (in gradio I saw 2 options in the TAB).
- As for teanscription, there is a module that does it even if we dont provide text next to the inputaudio right?



That's all I found in the inference "guide"/readme. (I ignored the part with LLM I suppose that's something different from what I am lookingfor)

I would like a step by step guide how to reproduce the voice of Geralt from Witcher 3 (this guy "https://www.youtube.com/watch?v=zxau03Row9U")

**Comment by SWivid** [comment]
Training/finetuning
1. TTS model mean model itself (the structure or design with its model weights), `.pth` `.pt` or `.safetensors` are the **format** of model checkpoint, as you may have `.mp3` `.wav` `.flac` `m4a` for audio files)
2. Other model .pth checkpoint file is for their own model structure, so cannot be used for other design.
3. The training, thought finetuning you need, has already a video #143 , mentioned in readme
> Gradio UI training/finetuning with src/f5_tts/train/finetune_gradio.py see https://github.com/SWivid/F5-TTS/discussions/143.

Inference:
1. Gradio has more features and easier usage (if not sufficient gpu mem, use online space demo https://huggingface.co/spaces/mrfakename/E2-F5-TTS or https://modelscope.cn/studios/modelscope/E2-F5-TTS )
2. Any length? Yes, but need to make sure the reference audio quality (as mentioned in readme: proper length, proper silence at end, if much noised may do denoising first with some online denoising service)

> I would like a step by step guide how to reproduce the voice of Geralt from Witcher 3 (this guy "https://www.youtube.com/watch?v=zxau03Row9U")

Very stylized speech to synthesize will need finetuning in order to have better result.
You could just try it out with finetuning, or wait for further stronger base models then do that

**Comment by GPU-server** [comment]
>  so cannot be used for other design
I see, so I need new trainings to make it work in this new "environment/design"

I will check the teh video you mentioned. Thanks.
I will surely be back with another message perhaps (or maybe comment there)

I am glad gui offers more features, so I dont need to check cli.
Finally:
Maybe I am blind or lazy, but I am doing a "CTRL+F" to search for the word "silence" on both:
- official readme repo: https://github.com/SWivid/F5-TTS
- inference readme: https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/infer

And I don't see anywhere any mention of this:

> proper silence at end,

?

Thanks again, apart from this detail about silence and "intructions" similar, I will next comment on the training most probably.

**Comment by GPU-server** [comment]
Yet again, people seem to have great expericence with the tool(https://x.com/cocktailpeanut/status/1850612952350502930)this popped on my feed.
I will try the training later in the week when I finish something. But for the direct inference:




> need to make sure the reference audio quality (as mentioned in readme: proper length, proper silence at end,


I just did a search for the word "silence" in the whole repo (https://github.com/search?q=repo%3ASWivid%2FF5-TTS%20silence&type=code) @SWivid 
It is not mentioned anywhere that a silence at end is important. Can you tell me where it is written please? Maybe I am missing some important page. Please tell me where was this "inference guide" apart from (https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/infer) which does not mention any needed silence at the end of audio inputs.
Eager to learn more.

**Comment by SWivid** [comment]
> 3. More instructions
> - In order to have better generation results, take a moment to read [detailed guidance](https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/infer).
> - The [Issues](https://github.com/SWivid/F5-TTS/issues?q=is%3Aissue) are very useful, please try to find the solution by properly searching the keywords of problem encountered. If no answer found, then feel free to open an issue.

https://github.com/SWivid/F5-TTS/issues?q=is%3Aissue+silence
https://github.com/SWivid/F5-TTS/issues/85 https://github.com/SWivid/F5-TTS/issues/133

**Comment by SWivid** [comment]
@GPU-server lol. Nobody is forcing you to use F5-TTS.
Or do you have a weakness in speaking like normal people?
