### ISSUE TITLE
Used with audio instead of text?

### ISSUE THREAD

**Issue by AIisCool** [SWivid/F5-TTS#292]
I am amazed at how faithful the voices are with just 15 seconds of audio. Is it possible to use this cloned voice with audio instead of writing text?

Thank you.

**Comment by jpgallegoar** [comment]
What do you mean exactly? You would like your voice to be transcribed into the reference text for batched generation?

**Comment by AIisCool** [comment]
I mean something like RVC, where the cloned voice can be used with uploaded audio or even real-time. This sounds much better than any RVC model I've heard by miles.

**Comment by jpgallegoar** [comment]
I understand now, unfortunately speech to speech is not possible right now due to the model architecture, although it's something they are looking into.

**Comment by AIisCool** [comment]
Ah I see. Still that is news I hope that comes eventually. Thank you for you time.
