### ISSUE TITLE
Is the generated audio length limited to only 15 seconds?

### ISSUE THREAD

**Issue by ScottishFold007** [SWivid/F5-TTS#3]
Can the generated audio be made longer, such as 30 seconds or more? I've found that when there's more text, the speech rate becomes faster, trying to squeeze into 15 seconds.

**Comment by SWivid** [comment]
modify the `fix_duration` or set to None for simple estimation
i will add this mentioning in README

the trainset is up to 30s, thus will do for 30s inference (prompt + to_generate, total length)
