### ISSUE TITLE
Multi-machine training quesion

### ISSUE THREAD

**Issue by yangyyt** [SWivid/F5-TTS#30]
Hi, Is this code suitable for multi-machine training? Seems to be stuck all the time. @SWivid

**Comment by SWivid** [comment]
we try `accelerate config` with multi-machine setting.
seems ok with our expr. maybe check for the port used

**Comment by SWivid** [comment]
will close, if any questions welcome to open it~

**Comment by yangyyt** [comment]
> we tried `accelerate config` with multi-machine setting. seems ok with our expr. maybe check for the port used

I noticed a phenomenon during my training. The training uses batch_size_per_gpu=20000, max_samples=64, the data only uses 0.3-20s of audio, training on 80G A100, in the middle of training, cuda oom, printing cuda memory occupation in training, found that in the middle of a batch, memory directly increased from 30G to 70G, and then kept at 70G, continue to train some steps, The OOM error is reported. 
Have you ever encountered it， or Do you have any suggestions？ @SWivid

**Comment by yangyyt** [comment]
Another question is why you use frame-wise batch_size with 32 for small models and 64 for base models. Why not use 32 for the base model and 64 for the small model?  @SWivid

**Comment by SWivid** [comment]
Hi @yangyyt , the increased gpu memory is normal as all ranks are prepared and batches with audio samples are in.
Our experience is that once figure out a oom-free batchsize, the mem usage will just keep the same all along training.

For the max_sample setting, we just intuitively have small model with smaller batchsize, and not squeeze too much short samples into one batch :D

**Comment by yangyyt** [comment]
> the increased gpu memory is normal. Once all ranks are prepared and batches with audio samples starts to swarm into gpu mem.

Thank you for your reply.
emmm,  step 3-step 3566: gpu mem~30G, but step3567-step 6454: gpu mem~70G, and then oom. Isn't that a little strange?

**Comment by SWivid** [comment]
> step 3 to step 3566: gpu mem_30G, but step 3567 to step 6454: gpu mem_70G

ah, this is strange. we just thought all gpu would reach 70g once step from 0 to 1.
will test for it.
