### ISSUE TITLE
涉及數字都不能正確發音

### ISSUE THREAD

**Issue by Happydingcyber** [SWivid/F5-TTS#300]
無論是中文、英文（只測試了這兩種語言）都存在這樣的問題，只要在文本中存在數字、字符（譬如“%”）等，就會發出一串怪音，聽起來像是英文，但細聽即使是英文也不準確，怎么解決？謝謝！

**Comment by SWivid** [comment]
Hi，一個直接的方式是將數字顯式轉換成中英文`1->一` or `1->one`
在大部分情況下數字和符號會被用英文發音，這是由於數據集分佈導致的
在我們的測試結果中，純英文的生成環境數字能夠被正常發音，%也會被正確讀成“percent”
但如果你希望非常精確地控制讀法，建議還是預先手動處理較好~

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.

**Comment by Happydingcyber** [comment]
Thanks your help! I'll try it. Thanks.
