### ISSUE TITLE
Can your pretrained model (pretrained checkpoints) speak multiple languages?

### ISSUE THREAD

**Issue by manhcuong17072002** [SWivid/F5-TTS#302]
I wonder if your pretrained model (pretrained checkpoints) can speak two or more languages simultaneously. If so, can it accurately distinguish between languages, especially those with similar alphabets but different pronunciations?

**Comment by SWivid** [comment]
it is code-switch you mean?
just try it out, everything is provided~

**Comment by manhcuong17072002** [comment]
@SWivid I want it to be able to understand more than 2 languages. For example, I have a Vietnamese model (main model) but sometimes there are some English technical terms (or domain-specific terms, or proper nouns like store names, company names, ...) and I still want it to read correctly. Is that possible?

**Comment by SWivid** [comment]
Possible, just check out our demo page, this is already smooth Chinese/English code-switch there
[here](https://swivid.github.io/F5-TTS/#:~:text=Code%2DSwitch%2C%20Text%20from%20FireRedTTS%20demo%20page.)

**Comment by manhcuong17072002** [comment]
@SWivid Thank you for your reply. Could you please advise me on how many hours of audio data are sufficient for training a new language model? I've looked through the issues but haven't found a clear answer to this question yet. Thanks

**Comment by SWivid** [comment]
@manhcuong17072002 if finetuning on current base model, with English+Vietnamese properly mixed, at least several kilo hours. More is better.
