### ISSUE TITLE
Generated audio speak repeated words, or wrong order of words

### ISSUE THREAD

**Issue by vu-the-dung** [SWivid/F5-TTS#303]
Hi,
I've finetuned F5TTS_Base model with my ~300h dataset and tokenizer for Vietnamese language.
The model can speak intelligible Vietnamese now, but it has problem of repeating words, missing words, or wrong order of words, compared to the input gen_text.
For example:
- input gen_text: "Chất lượng cuộc sống của người dân sau khi sắp xếp đơn vị hành chính là yếu tố then chốt"
- output audio as heard by ear: "Chất lượng cuộc sống của người dân **_sau khin_**(<--wrong and repeated words) sau khi sắp xếp **_đị_**(<--wrong word) hành chính là yếu tố **_viều_**(<--added word) then chốt"

From 1M steps to currently at 1M6 steps, I haven't yet to see any improvement.
Should I train more or what else should I do to improve this problem?

My train setting:
- bf16 precision on 1x GPU A5000 24GB
- learning_rate = 7.5e-5
- batch_size_per_gpu = 3000
- batch_size_type = "frame"
- max_sample = 64

Thanks

**Comment by SWivid** [comment]
> The model can speak intelligible Vietnamese now, but it has problem of repeating words, missing words, or wrong order of words, compared to the input gen_text.

It is nice that it can speak some Vietnamese.
The robustness issue is mainly for insufficient data, as you can compare with the pretrained data amount.
Two possible way out:
1. Try get more Vietnamese data.
2. Wait for our more powerful pretrained model.

**Comment by vu-the-dung** [comment]
Thanks,
I'll continue training and try to get more data. Let's see if it can improve the issue

**Comment by manhcuong17072002** [comment]
@vu-the-dung  Could you please provide more updates on the results? What dataset did you train it on, and how long did the training process take? Thank you.

**Comment by manhcuong17072002** [comment]
@vu-the-dung Thank you for the useful information from you
