### ISSUE TITLE
新版效果似乎比旧版的差一些

### ISSUE THREAD

**Issue by musicking** [SWivid/F5-TTS#306]
Hi， @SWivid 
非常棒的项目，感谢开源！
测试使用过程中发现一些问题，想和你分享一下，希望对项目改进有帮助。

一周前，我下载了一个版本，commit id是：4d29f11cf00088e0f9ed143905fe22e6cc62b93c
这个版本表现很好，只是第一个字之前会莫名多出一个音。

昨天，我看到了有一些更新，于是下载了最新的版本，经过测试，同样的素材，新的版本生成的音频会有很大的损失，并且感觉速度上会快很多。似乎和`ref audio`有

关，换了一个`ref audio`好像可以正常，但是会出现吞字、叠字的情况，感觉旧版的会更好一些。

期间怀疑和环境有关，重新创建了环境测试也是一样的表现。

音效请查看附件！
[测试音频.zip](https://github.com/user-attachments/files/17546341/default.zip)

**Comment by SWivid** [comment]
@musicking 感谢反馈！
应该是因为新的更平滑的长音频切分是根据静音来分段的，之前的脚本没考虑找不到合适长静音片段的情况，因此没有正确切分。
最新commit应该修复了~

**Comment by musicking** [comment]
非常感谢，刚测试已经恢复！
另外请问一下，第一个字会多出一点音，这个有办法处理吗？

**Comment by SWivid** [comment]
> 非常感谢，刚测试已经恢复！

85089a276beca7fb853e0f77d91197ee7e0a1358 刚刚再改了一下

> 另外请问一下，第一个字会多出一点音，这个有办法处理吗？

我观察到用的参考音频里基本都是连续的，手动切成<15s的音频，尾部留一些静音会好一些

**Comment by musicking** [comment]
好的，感谢大佬指点！
