### ISSUE TITLE
Generation broken when using reference clips longer than 15 sec

### ISSUE THREAD

**Issue by cocktailpeanut** [SWivid/F5-TTS#311]
Not sure when this started happening, but if you use a reference clip of--for example 30 seconds--the generated result is 10 second gibberish.

For comparison I trimmed the exact same reference clip to 12 second and generated with the exact same text, and it works perfectly.

**Comment by SWivid** [comment]
Hi @cocktailpeanut ~

Thanks for reporting this, mainly because some edge cases not properly considered when clipping long ref_audio input.
Fix in 456456971b1e7a227764aff16c46ab4c1cc97c39

Thanks!
