### ISSUE TITLE
How to train the model effectively?

### ISSUE THREAD

**Issue by PhamDangNguyen** [SWivid/F5-TTS#313]
I’m unsure whether I should train this TTS model with multiple voices or just one to achieve the best results. Should the text be normalized to all lowercase, or is it okay to keep uppercase letters? Also, should punctuation marks like '. , ? !' be removed from sentences? I would appreciate any advice. Thank you!

**Comment by SWivid** [comment]
All keeped in our training, you may refer to Emilia dataset, and you can see there are punctuations and capitalizations, and our tokenizer has no operations of lowercase or punc removal.

**Comment by PhamDangNguyen** [comment]
@SWivid Is using multiple speakers better than using just one? What do you think?

**Comment by SWivid** [comment]
> @SWivid Is using multiple speakers better than using just one? What do you think?

Up to your need, if you only do inference with the typical one speaker style, one for training is fine.
Otherwise more is better.
