### ISSUE TITLE
Accent with cross-lingual voice cloning

### ISSUE THREAD

**Issue by rlenain** [SWivid/F5-TTS#315]
Hello,

I successfully trained a model in Spanish using Spanish + English data! Great news.
The model unfortunately speaks with an accent when I use an English prompt with English source text and target text in Spanish (with an English accent) and vice-versa when I use a Spanish prompt with Spanish source text and target text in English (with a Spanish accent).

If the source is in the same language as the target, then I don't get this issue.

Does this happen to others who might have trained models when trying to do cross lingual voice cloning?

Thanks a lot!

**Comment by jpgallegoar** [comment]
This is because the model uses the same style of speech as used in the reference audio in the generated audio, so the model keeps using that same style. You would have to include language changes in the dataset or use language-specific tokens to combat this issue. (I might be mistaken). Are you planning on sharing your model?

**Comment by rlenain** [comment]
Unfortunately I cannot share my model.
I see what you are saying, and I would tend to agree, but if you look at the demo page [here](https://swivid.github.io/F5-TTS/), you can see the crosslingual voice cloning examples which don't have much of an accent. Perhaps they're cherry picked?

**Comment by SWivid** [comment]
actually with heavy accent

> the demo page [here](https://swivid.github.io/F5-TTS/)

**Comment by jpgallegoar** [comment]
> Unfortunately I cannot share my model. I see what you are saying, and I would tend to agree, but if you look at the demo page [here](https://swivid.github.io/F5-TTS/), you can see the crosslingual voice cloning examples which don't have much of an accent. Perhaps they're cherry picked?

The demo page has a huge accent, what do you mean?

**Comment by rlenain** [comment]
which samples are you looking at specifically?

**Comment by SWivid** [comment]
Maybe we are just talking about things in different aspect.
Accent is just part of speech style, which is somehow different from timbre.
English and Chinese are far from each other, thus in this case, transfering the timbre might not seems to transfer accent while the current model design is actually transfer all style, say it also transfer an accent from Chinese to English but not that distinguishable as for Spanish and English.

**Comment by attashe** [comment]
Hi, can you share your training parameters and loss values when model starts converge? I'm still waiting my training run when it will drop but have only flat line.

**Comment by SWivid** [comment]
Hi @attashe #9

**Comment by attashe** [comment]
> Hi @attashe #9

Thanks, just neet to wait more. Morning checkpoint already can produce some words but rare - 1 of 10

**Comment by jpgallegoar** [comment]
Hello @attashe, what language are you training? How many hours is your dataset? How many samples have you trained so far? I think you are doing something wrong because it should be better and faster to learn

**Comment by attashe** [comment]
> Hello @attashe, what language are you training? How many hours is your dataset? How many samples have you trained so far? I think you are doing something wrong because it should be better and faster to learn

I trained russian language. After two days it began to produce some result distinguishable words with bad quality. I used a dataset with short examples (6-10s) with overall size around ~500 hours.

I'm agree that something looks wrong - dataset and maybe training params (2e-5 lr), I'll try to change dataset and extend vocab with more tokens

**Comment by rlenain** [comment]
Hi @attashe did you find some new better parameters?

**Comment by rlenain** [comment]
@SWivid im not sure i follow your argument. when i say accented speech, i mean speech in english that sounds like someone who is from spain, and has a strong spanish accent in english, for example. what id like to achieve is generating english with the same speaker identity, but with no spanish accent

**Comment by SWivid** [comment]
If wish a standard English output, try using a standard English utterance for reference audio; otherwise it is having the model to mimick the accent which is part of acoustic features.
Also there have been recent researches digging into disentanglement of acoustic features like accent and speaking style in different level, though not open-source.

**Comment by SWivid** [comment]
I'm not quite get why you stick with using different language as reference prompt.
Is it for reason that the speaker you want to do voice cloning has just very accent and no clear english utterence at all?
If it's that case, try design a different model structure to do acoustic features' disentanglement, and i'm not sure if one day the speaker could just speak english with no accent in real world.

What is of certainty is that you could share some specific used reference prompts and generation results, which will help diagnose.

**Comment by rlenain** [comment]
With some more work i understood that finetuning just a little bit learns the language, but with a strong accent, and training longer mostly gets rid of the accent, but not completely. 

For example using the `F5-TTS-German` model on Huggingface which shares the model after 90k iterations and after 1M iterations, with [this English reference](https://whyp.it/tracks/229270/reference?token=rGYyP), I get [this sample](https://whyp.it/tracks/229272/generated-90k-iterations?token=DMiuT) after 90k iterations, and [this sample](https://whyp.it/tracks/229274/generated-1m-iterations?token=TS3T9) after 1M iterations -- you can clearly hear the difference in accent.

**Comment by attashe** [comment]
@rlenain @SWivid 
I found a reason of bad perfomance. I used a pinyin tokenizer (finetuning) and original code process cyrillic symbols adding extra space symbol after each one:
```
['Я', ' ', ' ', 'и', ' ', 'д', ' ', 'у', ' ', ' ', 'д'...  
```
I fixed this adding a if-case for cyrillic symbols in `convert_char_to_pinyin` function:

```python
if ord(c) < 256:
    char_list.extend(c)
elif '\u0400' <= c <= '\u04FF':  # Cyrillic Unicode block
    char_list.extend(c)
else:
    if c not in "。，、；：？！《》【】—…":
        char_list.append(" ")
        char_list.extend(lazy_pinyin(c, style=Style.TONE3, tone_sandhi=True))
```

After that perfomance improved. But still want to find a bigger corpus especially with woman voices to clarify accents and some hard cases
