### ISSUE TITLE
Model does not create frequencies above 12k hz

### ISSUE THREAD

**Issue by remorses** [SWivid/F5-TTS#32]
Hi, amazing model thank you for open sourcing it!

I noticed that the generated output does not have frequencies higher than 12k hz, which is essential to produce an high quality voice.

I attach below the reference spectrogram of the original audio and the generated one.

![Screenshot 2024-10-13 at 13 19 57](https://github.com/user-attachments/assets/444e1554-c52c-4306-8478-4a7804639478)
![Screenshot 2024-10-13 at 13 22 24](https://github.com/user-attachments/assets/ded4b2ee-2a2e-4c50-acc1-67d629f40fb2)

**Comment by SWivid** [comment]
As we see throught our train set - Emilia is actually up to 12khz, though the files are saved with 24khz.
Probably for this reason.
