### ISSUE TITLE
python error / torch version problem! please help.

### ISSUE THREAD

**Issue by ProxiEx3** [SWivid/F5-TTS#320]
Hey I ran into yet another problem...
Every time I'm starting F5-TTS I get the following errors:

![image](https://github.com/user-attachments/assets/163894f7-24c4-4b29-b9e6-f0c909555781)
![image](https://github.com/user-attachments/assets/5fe39842-d5e0-4463-8414-40495d442cdd)

I'm sorry those errors are in german but it's essentially not finding the "process entry point" in the following paths.

So I reran the torchvision command "pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118", which gave me the following error:

_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.16.0 requires torch==2.1.0, but you have torch 2.3.0+cu118 which is incompatible._

So what I did was downgrading to torch 2.1.0, which after a successful install gave me the same error but backwards:

_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.3.0+cu118 requires torch==2.3.0+cu118, but you have torch 2.1.0 which is incompatible._

Tempted to just reinstall everything but I kinda doubt it would help. I also have ComfyUI and A1111 still running on all this and I'm scared it breaks everything.

So I have no idea what's going on really and I need help please!

**Comment by SWivid** [comment]
basically you need
```
# Create a python 3.10 conda env (you could also use virtualenv)
conda create -n f5-tts python=3.10
conda activate f5-tts
```
which will have a separate env

**Comment by ProxiEx3** [comment]
I do have set envionment.. 
So when it's active I put in "f5-tts_infer-gradio" to start it and then I get the 2 errors which I screenshotted.
the web UI opens and I can navigate it, but when everything is set and I click "synthesize" the process runs infinitely.
yesterday I let a 15sec sample run for 20 mins and nothing happened. Which I'd assume goes back to the error messages which I get every time. I have beastly hardware, which should not be a problem.

**Comment by SWivid** [comment]
Check for existing issues.
Mainly because of   wrongly setup environment    /   network failure to huggingface

**Comment by ProxiEx3** [comment]
Okay I managed to get it to work somehow.. kept reinstalling stuff, not sure what ultimately fixed it.
I still get the 2 errors though, but doesn't seem like they prevent me from using it! 
Thank you for your time and you can close this threat please!

**Comment by SWivid** [comment]
Sure, feel free to open an issue if further questions.
