### ISSUE TITLE
Code Problem

### ISSUE THREAD

**Issue by JackZ2024** [SWivid/F5-TTS#321]
在finetune_gradio.py文件里：
![image](https://github.com/user-attachments/assets/ca173a3a-def3-4937-91fc-024017d127a5)

**Comment by SWivid** [comment]
可以具体说下这里的问题吗，maybe elaborate on this issue?

**Comment by JackZ2024** [comment]
Should "and" be changed to "or"?

**Comment by SWivid** [comment]
ah yes @lpscr

**Comment by lpscr** [comment]
ops !!! @JackZ2024  , @SWivid i just update fix this
