### ISSUE TITLE
no such file f5-tts_infer-gradio

### ISSUE THREAD

**Issue by michaeltran33** [SWivid/F5-TTS#322]
# Launch a Gradio app (web interface)
f5-tts_infer-gradio
There is no such file in the repo. cannot run it.

**Comment by justinjohn0306** [comment]
> # Launch a Gradio app (web interface)
> f5-tts_infer-gradio There is no such file in the repo. cannot run it.

cd F5-TTS
pip install -e .

**Comment by michaeltran33** [comment]
> > # Launch a Gradio app (web interface)
> > f5-tts_infer-gradio There is no such file in the repo. cannot run it.
> 
> cd F5-TTS pip install -e .
no such file regardless. Best to review the repo.

**Comment by danielw97** [comment]
Please note that this command is available when f5tts is installed as a pip package, not before.
Hope this helps a bit.

**Comment by michaeltran33** [comment]
lemme try. found it. it is exe form. thx.

**Comment by michaeltran33** [comment]
it works now. thanks in a bunch.
