### ISSUE TITLE
infer 和 finetune 不能同时启动

### ISSUE THREAD

**Issue by liuhui881125** [SWivid/F5-TTS#324]
同时启动后，会报错：
error
Connection errored out.

**Comment by SWivid** [comment]
如果指定不同port看看能不能行

**Comment by liuhui881125** [comment]
指定不同的port，也不行。

我觉得可能是   http://x.x.x.x/queue/join?   这个接口在调用的时候，分不清到底是infer的还是finetune的
![image](https://github.com/user-attachments/assets/a09b37f3-5e29-4894-827a-e839ce018c70)

@SWivid 这个问题后面可以优化么。或者能不能提供一个nginx的配置方案

**Comment by SWivid** [comment]
这应该不是我们所擅长和规划内范畴了。
欢迎PR~

**Comment by liuhui881125** [comment]
训练好的模型可以用来推理吗？是不是需要用训练后的last模型替换掉原始的F5的120000模型呢？
