### ISSUE TITLE
Using a temp directory inside of F5 instead of clogging %temp%

### ISSUE THREAD

**Issue by spike4379** [SWivid/F5-TTS#325]
So I have notice that F5 is exporting everything to %temp% on windows and I would rather make it run everything from within the local directory to make users systems cleaner.
Already it calls to users/user/.cache when an updated gradio.py could solve this problem.

Originally with infer_gradio.py I added 

import os

# Set up the temp directory at the top of your script
app_root = os.path.dirname(os.path.abspath(__file__))
temp_dir = os.path.join(app_root, 'temp')
os.makedirs(temp_dir, exist_ok=True)
tempfile.tempdir = temp_dir

This makes generations appear in F5-TTS\src\f5_tts\infer\temp which can be cleaner.
I don't know much about python so I can't make it better, but including something like this will be a step towards making f5 more 'portable' which should be the end goal.

I love the project by the way!

**Comment by spike4379** [comment]
Closing and moving to discussions. apologies

**Comment by SWivid** [comment]
@spike4379 Thanks~
If further questions, feel free to open an issue.
