### ISSUE TITLE
Emilia_ZH_EN_pinyin vocab size changed

### ISSUE THREAD

**Issue by sarpba** [SWivid/F5-TTS#328]
vocab.txt size in data/Emilia_ZH_EN_pinyin dir changed, because windows style line brakes (^M) Its not problem?
![Képernyőkép 2024-10-30 07-09-55](https://github.com/user-attachments/assets/407044f9-41c9-42ca-9bc5-e54b40665342)

**Comment by SWivid** [comment]
if in `finetune` scripts' loading method is the same `utf-8-sig` maybe fine.

@v3ucn @lpscr

**Comment by sarpba** [comment]
linux - midnight commander

**Comment by lpscr** [comment]
@sarpba make sure you have last update repo then see 

https://github.com/SWivid/F5-TTS/blob/7dd3eecf2d91dde806946e23b8227365bb6e3a6b/src/f5_tts/train/finetune_gradio.py#L1094

replace the "utf-8" with "utf-8-sig"

then run again gradio finetune and make new project see now working ?

this fix the problem let me know

**Comment by SWivid** [comment]
will close this issue, if further questions feel free to reopen
