### ISSUE TITLE
Whether external api calls can be made

### ISSUE THREAD

**Issue by YJS0420** [SWivid/F5-TTS#329]
Hello author, please forgive my ignorance. I want to use voice cloning in my small project. I have also checked the infer_gradio code, but only the gradio api is available, but I still can't write the external interface. Do you have any suggestions? Expect a reply from the author.

**Comment by SWivid** [comment]
We mainly provide our code and along with base model checkpoints for TTS task, the gradio is from community contribution.
Not quite get your need, what is the specific `external interface`

**Comment by YJS0420** [comment]
Thanks for the author's reply, I think it is the kind of post interface that connects the front and back ends. For example, there is a project that specially integrates such an interface. The following URL 
”https://github.com/RVC-Boss/GPT-SoVITS/blob/main/api_v2.py “
is what I want. If it is inconvenient for you to check, I will post it below. Thank you again.
![案例1](https://github.com/user-attachments/assets/73e69cc8-1437-4181-a4c5-c904d88e6d60)

**Comment by SWivid** [comment]
Oh, so you need a POST GET way web interaction.
Not current script for it, but as we have updated the repo recently making it compatible with pkg form, it's doable.
Welcome PR~

**Comment by YJS0420** [comment]
Yes, as you said I need a kind of POST or GET interaction,
 I will try to write the code, but the integrity and effect may not be as good as yours, I will redouble my efforts before your code comes out. thank you.

**Comment by lpscr** [comment]
@YJS0420   i dont test yet but this must working something like this

```
from flask import Flask, request, send_file, jsonify
import os
from f5_tts.api import F5TTS

app = Flask(__name__)

UPLOAD_FOLDER = './uploads'
OUTPUT_FOLDER = './outputs'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['OUTPUT_FOLDER'] = OUTPUT_FOLDER

for folder in [UPLOAD_FOLDER, OUTPUT_FOLDER]:
    if not os.path.exists(folder):
        os.makedirs(folder)

f5tts = F5TTS()

# API endpoint to accept ref_audio, ref_text, and gen_text
@app.route('/process', methods=['POST'])
def process_data():

    if 'ref_audio' not in request.files:
        return jsonify({"error": "No ref_audio part"}), 400
    
    ref_audio = request.files['ref_audio']
    
    if ref_audio:
        audio_path = os.path.join(app.config['UPLOAD_FOLDER'], ref_audio.filename)
        ref_audio.save(audio_path)
    else:
        return jsonify({"error": "Failed to upload the audio file"}), 400
    
    ref_text = request.form.get('ref_text')
    gen_text = request.form.get('gen_text')

    if not ref_text or not gen_text:
        return jsonify({"error": "Missing ref_text or gen_text"}), 400

    output_wave_path = os.path.join(app.config['OUTPUT_FOLDER'], 'out.wav')

    try:
        wav, sr, spect = f5tts.infer(
            ref_file=audio_path,
            ref_text=ref_text,
            gen_text=gen_text,
            file_wave=output_wave_path,
            seed=-1  # Using random seed (-1)
        )
    except Exception as e:
        return jsonify({"error": f"F5TTS inference failed: {str(e)}"}), 500

    return send_file(output_wave_path, mimetype='audio/wav')
if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by YJS0420** [comment]
@lpscr OK, thank you for the reference.So, where do you think the source code should start to analyze this edition?

**Comment by lpscr** [comment]
@SWivid you can make new api_flask.py for example and put in F5-TTS\src\f5_tts where the api.py
and you can run then this create server local and then you can use with 

```
curl -X POST http://127.0.0.1:5000/process \
    -F "ref_audio=@/path/to/your/audiofile.wav" \
    -F "ref_text=some call me nature, others call me mother nature." \
    -F "gen_text=I don't really care what you call me..." \
    --output generated_audio.wav
```

**Comment by SWivid** [comment]
We are just ordinary open source contributors lol
and you are welcome to join us~

**Comment by YJS0420** [comment]
@lpscr Thanks for your reminder, I think I have wrapped it in post form now, because I used POSTMAN test, he can get the result. haha

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions

**Comment by banank1989** [comment]
@SWivid  @YJS0420 @lpscr 
Is it possible that I process ref_audio once and do not need to do that at every API call which would speed up the infer? This would definitely speep up the API
