### ISSUE TITLE
precompute_max_pos = 4096 目前最大只能支持到4096token的文本长度么？

### ISSUE THREAD

**Issue by pengyong94** [SWivid/F5-TTS#33]
if conv_layers > 0:
          self.extra_modeling = True
          self.precompute_max_pos = 4096  # ~44s of 24khz audio
          self.register_buffer("freqs_cis", precompute_freqs_cis(text_dim, self.precompute_max_pos), persistent=False)
          self.text_blocks = nn.Sequential(*[ConvNeXtV2Block(text_dim, text_dim * conv_mult) for _ in range(conv_layers)])

请问后续是否有计划支持更大的长度。

**Comment by SWivid** [comment]
实际上目前训练集最长是30秒，所以4096 ~44s完全覆盖了
目前通过分块生成，30s应该够用，之后大概率会往流式的方向走

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.

**Comment by pengyong94** [comment]
ok, thanks for your reply ,and your work is great !
