### ISSUE TITLE
Multiple Speech-Type Generation broken?

### ISSUE THREAD

**Issue by 0dram** [SWivid/F5-TTS#335]
I din´t know if i am stupid but no mater what i do, as soon as i put text into the Text to Generate field the button to generate audio grays out and can´t be used.
How does this function work now? 
The description text at the top also doesn´t make me smarter ^^

**Comment by SWivid** [comment]
Hi @0dram , will need to assure the text input has a reference audio matched.
e.g. 
if you input text as : "{happy} happy happy, {sad} sad sad"
you should have uploaded two reference audio and mark them as `happy` and `sad`

**Comment by 0dram** [comment]
hey there thanks for the quick reply <3
It just doesn't work in Pinocchio interface. I tried it with the browser and it worked just fine. I'm sorry. 
Thanks again

**Comment by SWivid** [comment]
If work is great~
Will close this issue, feel free to open if further questions
