### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by MJAnderson1** [SWivid/F5-TTS#340]
Is there a way to set a seed, for consistent output.

**Comment by lpscr** [comment]
@MJAnderson1 you can also api support seed 
and also you can get the value is seed =-1 make random

https://github.com/SWivid/F5-TTS/blob/dee0420b59819cea85917d0bb15521aa96bf3f5b/src/f5_tts/api.py#L134-L143

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions

**Comment by AIisCool** [comment]
Would it be possible to add a field in the `f5-tts_infer-gradio` to enter a seed?

**Comment by SWivid** [comment]
@AIisCool it's possible to manually add it. We might not just add it ourselves for some considerations we all know

**Comment by x4080** [comment]
Hi, it seems infer_cli is not calling api ?
