### ISSUE TITLE
FutureWarning

### ISSUE THREAD

**Issue by vootox** [SWivid/F5-TTS#344]
I'm getting this warning, though the program is running really good. How to fix it?

`E:\Test\F5-TTS\venv\Lib\site-packages\vocos\pretrained.py:70: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(model_path, map_location="cpu")`

**Comment by SWivid** [comment]
It's normal with torch2.4
1. ignore warning
2. go for these places and literally add `weights_only=True`

**Comment by vootox** [comment]
> pretrained.py:70

Thank you for your help. I'm not sure what I'm doing here. My understanding is to search and find all places where weights_only=False and change to True. Please verify if the following 38 places are all meant to be included?

`Search "weights_only=False" (38 hits in 12 files of 15912 searched)
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\distributed\checkpoint\default_planner.py (2 hits)
	Line 248:                 torch.load(value, weights_only=False),
	Line 252:                 value, weights_only=False
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\distributed\checkpoint\format_utils.py (2 hits)
	Line  88:                 self.checkpoint_id, map_location="cpu", weights_only=False
	Line 236:     state_dict = torch.load(torch_save_path, weights_only=False)
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\distributed\checkpoint\planner.py (1 hit)
	Line 330:     >>>         self.original_state_dict[read_item.dest_index.fqn[4:]] = torch.load(value, weights_only=False)
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\distributed\optim\zero_redundancy_optimizer.py (1 hit)
	Line  111:         obj = torch.load(buffer, map_location=device, weights_only=False)
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\fx\graph_module.py (2 hits)
	Line 570:                 # weights_only=False as this is legacy code that saves the model
	Line 571:                 module_str = f"torch.load(r'{module_file}', weights_only=False) # {module_repr}"
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\serialization.py (6 hits)
	Line 1131:     """load(f, map_location=None, pickle_module=pickle, *, weights_only=False, mmap=None, **pickle_load_args)
	Line 1222:         # Loading from a buffer setting weights_only=False, warning this can be unsafe
	Line 1225:         >>> torch.load(buffer, weights_only=False)
	Line 1227:         # Loading from a module setting weights_only=False, warning this can be unsafe
	Line 1228:         >>> torch.load("module.pt", encoding="ascii", weights_only=False)
	Line 1295:                     "You are using `torch.load` with `weights_only=False` (the current default value), which uses "
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\storage.py (1 hit)
	Line  520:     return torch.load(io.BytesIO(b), weights_only=False)
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\testing\_internal\common_nn.py (2 hits)
	Line 3440:                     # weights_only=False as this is legacy code that saves the model
	Line 3441:                     module_copy = torch.load(f, weights_only=False)
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\testing\_internal\common_quantization.py (4 hits)
	Line  660:         # weights_only=False as we sometimes get a ScriptObect here (weird)
	Line  661:         loaded_dict = torch.load(b, weights_only=False)
	Line  678:         # weights_only=False as this is legacy code that saves the model
	Line  679:         loaded = torch.load(b, weights_only=False)
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\testing\_internal\distributed\distributed_test.py (14 hits)
	Line  4274:                             # weights_only=False as this is legacy code that saves the model
	Line  4275:                             model_DDP = torch.load(tmp, weights_only=False)
	Line  4278:                             # weights_only=False as this is legacy code that saves the model
	Line  4279:                             model_DDP = torch.load(tmp.name, weights_only=False)
	Line  4284:                 # weights_only=False as this is legacy code that saves the model
	Line  4285:                 saved_model = torch.load(tmp_file, weights_only=False)
	Line  4326:                     # weights_only=False as this is legacy code that saves the model
	Line  4327:                     model_DDP = torch.load(tmp, weights_only=False)
	Line  4330:                     # weights_only=False as this is legacy code that saves the model
	Line  4331:                     model_DDP = torch.load(tmp.name, weights_only=False)
	Line  5606:                     # weights_only=False as this is legacy code that saves the model
	Line  5607:                     model_DDP = torch.load(tmp, weights_only=False)
	Line  5610:                     # weights_only=False as this is legacy code that saves the model
	Line  5611:                     model_DDP = torch.load(tmp.name, weights_only=False)
  E:\Test\F5-TTS\venv\Lib\site-packages\torch\_export\serde\serialize.py (2 hits)
	Line  325:     # weights_only=False as we want to load custom objects here (e.g. ScriptObject)
	Line  326:     artifact = torch.load(buffer, weights_only=False)
  E:\Test\F5-TTS\venv\Lib\site-packages\wandb\integration\keras\keras.py (1 hit)
	Line  393:         save_weights_only=False,`

**Comment by SWivid** [comment]
> PS: I just realized there are some which are not included e.g, 'save_weights_only=False'. But I'm not sure if all the exact matches must be or not.

is actually to add `save_weights_only=True` to those have only `torch.load("model_ckpt.pt")

**Comment by vootox** [comment]
I was going to ignore but it was literally as you said
From: `pretrained.py:70: state_dict = torch.load(model_path, map_location="cpu")`
I just had to add the 3rd parameter:
To: `pretrained.py:70: state_dict = torch.load(model_path, map_location="cpu", weights_only=True)`
Thank you, and for such incredible software.

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
