### ISSUE TITLE
audio output without content, silent

### ISSUE THREAD

**Issue by marksherano** [SWivid/F5-TTS#347]
Hello, I have a problem in one of the two computers where I have tested it; both are Windows. 

In the one with low resources, where it took 2 hours to generate an audio, to give you an idea of what kind of computer it is, the audio is generated correctly and the output audio is heard correctly.

On the other hand, the more powerful one, an Asus laptop with 4 gigs of vram, installs everything well but the output audio is generated without content. It seems to be as long as it should be, but without content.

I am using the same reference file on both computers. 
![captura](https://github.com/user-attachments/assets/19197614-d90d-469b-acc5-5f3b79fb2793)

**Comment by SWivid** [comment]
it is better if you could provide a full screen shot of command line output

**Comment by armthug213** [comment]
hi @SWivid , i have the very same issue (2nd issue/ the output audio is generated without content. It seems to be as long as it should be, but without content.) here the screenshots:

![iuohui](https://github.com/user-attachments/assets/f3723660-df1a-43c4-b177-46e467a9d68e)
![inin](https://github.com/user-attachments/assets/326251fb-8829-47f8-ad8b-a89bc32aaab5)
![bibhibb](https://github.com/user-attachments/assets/c9618f65-a82a-4275-96c9-7583c867c07a)
![inikn](https://github.com/user-attachments/assets/84669492-105a-428d-89ef-b7b902dce336)

**Comment by SWivid** [comment]
@marksherano @armthug213 Hi, will close this issue and move discussion to #356
