### ISSUE TITLE
Multi-speaker small bug

### ISSUE THREAD

**Issue by Huowuge** [SWivid/F5-TTS#348]
When using infer-cli for multi-speaker operations, I discovered that if gen_text begins with a character tag, such as [main]This is a speaker speaks., it throws an error. However, if it doesn't start with a character tag, no error occurs. The error message is:
F5-TTS/src/f5_tts/infer/utils_infer.py", line 380, in infer_batch_process
final_wave = generated_waves[0]
~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by SWivid** [comment]
@Huowuge Thanks for reporting the bug !
