### ISSUE TITLE
Is it possible to fine tune to add pronunciation for words such as people's names?

### ISSUE THREAD

**Issue by HumanGamer** [SWivid/F5-TTS#349]
Currently certain words are not pronounced right, such as the name Mathew.

Is it possible to fine tune and add words in?

If it is possible, can you explain how to do so?
I have a 3090ti so I think that should be good enough to train, however I have no idea where to start.

**Comment by lpscr** [comment]
@HumanGamer hi you need use lowcase also
if you like to fintune to test if working there is gradio finetune i working on here there is help and tutorial if you like give a try
https://github.com/SWivid/F5-TTS/discussions/143 ,

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions

**Comment by danielw97** [comment]
Hi there,
I'm replying on this issue as it is the same topic, although let me know if a new issue is preferred.
Currently I'm running into the same problem as the original poster, there are certain words that are pronounced incorrectly such as people's names and the names of cities ETC.
Is it a matter of finetuning the model on problematic words, or would a different phonomizer help in this case?
I'm generating speech in English, and the pronunciation rules in English are complicated so there maybe a better way to tackle this.
Thanks for any guidance.
