### ISSUE TITLE
Why is it necessary to divide by num_channels in get_audio_duration?

### ISSUE THREAD

**Issue by jeremy110** [SWivid/F5-TTS#351]
This part seems a bit strange. It shouldn’t need to be divided by num_channels; it should just be audio.shape[1] / sample_rate, right?

**Comment by SWivid** [comment]
Maybe you could post the link to indicate which specific part is related.
And yes, as the input sample is raw audio yet not mel, ndim is 2, [-1] is same as [1]

**Comment by jeremy110** [comment]
https://github.com/SWivid/F5-TTS/blob/dee0420b59819cea85917d0bb15521aa96bf3f5b/src/f5_tts/train/finetune_gradio.py#L174
https://github.com/SWivid/F5-TTS/blob/dee0420b59819cea85917d0bb15521aa96bf3f5b/src/f5_tts/train/datasets/prepare_csv_wavs.py#L55

The torchaudio.load function returns audio with dimensions (channel, time), so to calculate the duration, I should just use audio.shape[1] / sample_rate, right?

My data is stereo, and each audio file is longer than 1 second, but about 30% of the data got filtered out when using finetune_gradio because the calculation included the num_channels, resulting in shorter segments (less than 2 seconds) being mistakenly discarded.

**Comment by SWivid** [comment]
@jeremy110 thanks for mentioning this!
for inference is correct:
https://github.com/SWivid/F5-TTS/blob/dee0420b59819cea85917d0bb15521aa96bf3f5b/src/f5_tts/infer/utils_infer.py#L320-L322

@lpscr might help fix this

**Comment by jeremy110** [comment]
Thank you; I understand that this won’t affect the training results, but I’m concerned that others may encounter audio files being filtered out as well.

**Comment by lpscr** [comment]
@jeremy110 hi update soon , you simple relace the and must working fine

`num_channels = audio.shape[0]` to `num_channels = 1`
