### ISSUE TITLE
Can I generate speech without reference audio?

### ISSUE THREAD

**Issue by Jasonlin00** [SWivid/F5-TTS#357]
Actually, what I want to ask is, can I directly use the trained model to generate audio?

**Comment by SWivid** [comment]
the issue title seems more clear.
is this you want?
https://github.com/SWivid/F5-TTS/blob/dee0420b59819cea85917d0bb15521aa96bf3f5b/src/f5_tts/model/cfm.py#L95
you could simply pass in an all zero tensor for original ref_audio place, but need to assure properly pass in a duration info
currently the duration is linearly estimated, check the code

**Comment by shirubei** [comment]
@SWivid 
Appreciate your team's great work. 
I've trained my own dataset and wanted to generate audio without reference wav.

With the help from chatGPT(sorry for my poor knowledge), I modified infer_batch_process() as below in src\f5_tts\infer\utils_infer.py , 
but the output audio is indistinguishable sound. 
Please help.

def infer_batch_process(
    gen_text_batches,
    model_obj,
    vocoder,
    mel_spec_type="vocos",
    progress=tqdm,
    target_rms=0.1,
    cross_fade_duration=0.15,
    nfe_step=32,
    cfg_strength=2.0,
    sway_sampling_coef=-1,
    speed=1,
    fix_duration=None,
    device=None,
):

    # 生成填充的cond
    cond = torch.zeros((1, target_sample_rate * 1), device=device)  # 假设一个1秒的空白参考音频
    generated_waves = []

    for i, gen_text in enumerate(progress.tqdm(gen_text_batches)):
        # Prepare the text
        final_text_list = convert_char_to_pinyin([gen_text])

        if fix_duration is not None:
            duration = int(fix_duration * target_sample_rate / hop_length)
        else:
            # Calculate duration based on the length of the generated text
            gen_text_len = len(gen_text.encode("utf-8"))
            duration = int(gen_text_len / speed) * (target_sample_rate // hop_length)

        # inference
        with torch.inference_mode():
            generated, _ = model_obj.sample(
                cond=cond,  # 使用生成的填充cond
                text=final_text_list,
                duration=duration,
                steps=nfe_step,
                cfg_strength=cfg_strength,
                sway_sampling_coef=sway_sampling_coef,
            )

            generated = generated.to(torch.float32)
            generated_mel_spec = generated.permute(0, 2, 1)
            if mel_spec_type == "vocos":
                generated_wave = vocoder.decode(generated_mel_spec)
            elif mel_spec_type == "bigvgan":
                generated_wave = vocoder(generated_mel_spec)

            # wav -> numpy
            generated_wave = generated_wave.squeeze().cpu().numpy()

            generated_waves.append(generated_wave)

    # Combine all generated waves with cross-fading
    if cross_fade_duration <= 0:
        # Simply concatenate
        final_wave = np.concatenate(generated_waves)
    else:
        final_wave = generated_waves[0]
        for i in range(1, len(generated_waves)):
            prev_wave = final_wave
            next_wave = generated_waves[i]

            # Calculate cross-fade samples, ensuring it does not exceed wave lengths
            cross_fade_samples = int(cross_fade_duration * target_sample_rate)
            cross_fade_samples = min(cross_fade_samples, len(prev_wave), len(next_wave))

            if cross_fade_samples <= 0:
                # No overlap possible, concatenate
                final_wave = np.concatenate([prev_wave, next_wave])
                continue

            # Overlapping parts
            prev_overlap = prev_wave[-cross_fade_samples:]
            next_overlap = next_wave[:cross_fade_samples]

            # Fade out and fade in
            fade_out = np.linspace(1, 0, cross_fade_samples)
            fade_in = np.linspace(0, 1, cross_fade_samples)

            # Cross-faded overlap
            cross_faded_overlap = prev_overlap * fade_out + next_overlap * fade_in

            # Combine
            new_wave = np.concatenate(
                [prev_wave[:-cross_fade_samples], cross_faded_overlap, next_wave[cross_fade_samples:]]
            )

            final_wave = new_wave

    return final_wave, target_sample_rate

**Comment by SWivid** [comment]
@shirubei Hi, thanks for using.
note for the change in this line
> duration = int(gen_text_len / speed) * (target_sample_rate // hop_length)

here `int(gen_text_len / speed)` indicates the duration in second, i.e. if yuo set like this, will have 1 second for each character (you could set the speed as a common speaking rate of the language you use

**Comment by ILG2021** [comment]
Hello, @SWivid I see the paper B.2 Ablation study on Input Condition, when drop audio prompt, the wer will reduce, can you show a example code? How about gt duration(may be accurate duration) + drop audio prompt? Because I want to finetune a single speaker will stable output.

**Comment by SWivid** [comment]
Hi @ILG2021 , it's at https://github.com/SWivid/F5-TTS/blob/46266f1d142d7e9d72e1da4eed5d180ae4b7535a/src/f5_tts/model/cfm.py#L95
https://github.com/SWivid/F5-TTS/blob/46266f1d142d7e9d72e1da4eed5d180ae4b7535a/src/f5_tts/model/cfm.py#L145-L146

gt duration is to set `fix_duration` (the total seconds of ref_audio and gen_audio)

**Comment by wanchch** [comment]
Hi, I have a question. when I pass cond(ref_audio) and text(ref_text+gen_text) into the cfm.py' sample and let no_ref_audio=True, I did  eliminate the ref_audio, but text contains the information of ref_text, won't this be a problem? Thanks!
