### ISSUE TITLE
Was working fine for finetuning until I pulled a update today and got his using gradio

### ISSUE THREAD

**Issue by rikabi89** [SWivid/F5-TTS#361]
```
F5-TTS) D:\F5-TTS\F5-TTS>git pull
Already up to date.

(F5-TTS) D:\F5-TTS\F5-TTS>f5-tts_finetune-gradio
Starting app...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
accelerate launch  src/f5_tts/train/finetune_cli.py --exp_name F5TTS_Base --learning_rate 1e-05 --batch_size_per_gpu 3200 --batch_size_type frame --max_samples 64 --grad_accumulation_steps 1 --max_grad_norm 1 --epochs 112129 --num_warmup_updates 4 --save_per_updates 8 --last_per_steps 2 --dataset_name test --finetune True --tokenizer pinyin  --log_samples True --logger wandb
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.

vocab :  2545
Using logger: wandb
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: rikabi. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.5
wandb: Run data is saved locally in D:\F5-TTS\F5-TTS\wandb\run-20241101_101220-f7cf95t9
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run F5TTS_Base
wandb:  View project at https://wandb.ai/rikabi/test
wandb:  View run at https://wandb.ai/rikabi/test/runs/f7cf95t9
Loading dataset ...
Download Vocos from huggingface charactr/vocos-mel-24khz
H:\anaconda3\envs\F5-TTS\lib\site-packages\vocos\pretrained.py:70: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(model_path, map_location="cpu")
Sorting with sampler... if slow, check whether dataset is provided with duration: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 77/77 [00:00<00:00, 300708.95it/s]
Creating dynamic batches with 3200 audio frames per gpu: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 77/77 [00:00<00:00, 177062.18it/s]
Traceback (most recent call last):
  File "D:\F5-TTS\F5-TTS\src\f5_tts\train\finetune_cli.py", line 161, in <module>
    main()
  File "D:\F5-TTS\F5-TTS\src\f5_tts\train\finetune_cli.py", line 154, in main
    trainer.train(
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 247, in train
    start_step = self.load_checkpoint()
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 167, in load_checkpoint
    self.ema_model.load_state_dict(checkpoint["ema_model_state_dict"])
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torch\nn\modules\module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for EMA:
        Unexpected key(s) in state_dict: "ema_model.mel_spec.mel_stft.spectrogram.window", "ema_model.mel_spec.mel_stft.mel_scale.fb".
Traceback (most recent call last):
  File "D:\F5-TTS\F5-TTS\src\f5_tts\train\finetune_cli.py", line 161, in <module>
    main()
  File "D:\F5-TTS\F5-TTS\src\f5_tts\train\finetune_cli.py", line 154, in main
    trainer.train(
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 247, in train
    start_step = self.load_checkpoint()
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 167, in load_checkpoint
    self.ema_model.load_state_dict(checkpoint["ema_model_state_dict"])
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torch\nn\modules\module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for EMA:
        Unexpected key(s) in state_dict: "ema_model.mel_spec.mel_stft.spectrogram.window", "ema_model.mel_spec.mel_stft.mel_scale.fb".
wandb: 🚀 View run F5TTS_Base at: https://wandb.ai/rikabi/test/runs/f7cf95t9
wandb: Find logs at: wandb\run-20241101_101220-f7cf95t9\logs
Traceback (most recent call last):
  File "H:\anaconda3\envs\F5-TTS\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\anaconda3\envs\F5-TTS\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\anaconda3\envs\F5-TTS\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\anaconda3\\envs\\F5-TTS\\python.exe', 'src/f5_tts/train/finetune_cli.py', '--exp_name', 'F5TTS_Base', '--learning_rate', '1e-05', '--batch_size_per_gpu', '3200', '--batch_size_type', 'frame', '--max_samples', '64', '--grad_accumulation_steps', '1', '--max_grad_norm', '1', '--epochs', '112129', '--num_warmup_updates', '4', '--save_per_updates', '8', '--last_per_steps', '2', '--dataset_name', 'test', '--finetune', 'True', '--tokenizer', 'pinyin', '--log_samples', 'True', '--logger', 'wandb']' returned non-zero exit status 1.


```

**Comment by SWivid** [comment]
@rikabi89 check if work with lastest commit

**Comment by rikabi89** [comment]
> @rikabi89 check if work with lastest commit

`(F5-TTS) D:\F5-TTS>git pull
Already up to date.

(F5-TTS) D:\F5-TTS>f5-tts_finetune-gradio
Starting app...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
H:\anaconda3\envs\F5-TTS\lib\site-packages\transformers\models\whisper\generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
3
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Ali\AppData\Local\Temp\jieba.cache
Loading model cost 0.430 seconds.
Prefix dict has been built successfully.
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
accelerate launch  src/f5_tts/train/finetune_cli.py --exp_name F5TTS_Base --learning_rate 1e-05 --batch_size_per_gpu 3200 --batch_size_type frame --max_samples 64 --grad_accumulation_steps 1 --max_grad_norm 1 --epochs 112129 --num_warmup_updates 4 --save_per_updates 8 --last_per_steps 2 --dataset_name test3 --finetune True --tokenizer pinyin  --log_samples True --logger wandb
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
copy checkpoint for finetune

vocab :  2545
Using logger: wandb
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: rikabi. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.5
wandb: Run data is saved locally in D:\F5-TTS\wandb\run-20241101_110327-cbi7jhd1
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run F5TTS_Base
wandb:  View project at https://wandb.ai/rikabi/test3
wandb:  View run at https://wandb.ai/rikabi/test3/runs/cbi7jhd1
Loading dataset ...
Download Vocos from huggingface charactr/vocos-mel-24khz
H:\anaconda3\envs\F5-TTS\lib\site-packages\vocos\pretrained.py:70: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(model_path, map_location="cpu")

Sorting with sampler... if slow, check whether dataset is provided with duration:   0%|          | 0/77 [00:00<?, ?it/s]Sorting with sampler... if slow, check whether dataset is provided with duration: 100%|##########| 77/77 [00:00<00:00, 108668.04it/s]

Creating dynamic batches with 3200 audio frames per gpu:   0%|          | 0/77 [00:00<?, ?it/s]
Creating dynamic batches with 3200 audio frames per gpu: 100%|##########| 77/77 [00:00<00:00, 1048576.00it/s]
Traceback (most recent call last):
  File "D:\F5-TTS\src\f5_tts\train\finetune_cli.py", line 161, in <module>
    main()
  File "D:\F5-TTS\src\f5_tts\train\finetune_cli.py", line 154, in main
    trainer.train(
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 255, in train
    start_step = self.load_checkpoint()
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 171, in load_checkpoint
    if key in checkpoint["model_state_dict"]:
KeyError: 'model_state_dict'
Traceback (most recent call last):
  File "D:\F5-TTS\src\f5_tts\train\finetune_cli.py", line 161, in <module>
    main()
  File "D:\F5-TTS\src\f5_tts\train\finetune_cli.py", line 154, in main
    trainer.train(
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 255, in train
    start_step = self.load_checkpoint()
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 171, in load_checkpoint
    if key in checkpoint["model_state_dict"]:
KeyError: 'model_state_dict'
wandb: ðŸš€ View run F5TTS_Base at: https://wandb.ai/rikabi/test3/runs/cbi7jhd1
wandb: Find logs at: wandb\run-20241101_110327-cbi7jhd1\logs
Traceback (most recent call last):
  File "H:\anaconda3\envs\F5-TTS\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\anaconda3\envs\F5-TTS\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\anaconda3\envs\F5-TTS\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\anaconda3\\envs\\F5-TTS\\python.exe', 'src/f5_tts/train/finetune_cli.py', '--exp_name', 'F5TTS_Base', '--learning_rate', '1e-05', '--batch_size_per_gpu', '3200', '--batch_size_type', 'frame', '--max_samples', '64', '--grad_accumulation_steps', '1', '--max_grad_norm', '1', '--epochs', '112129', '--num_warmup_updates', '4', '--save_per_updates', '8', '--last_per_steps', '2', '--dataset_name', 'test3', '--finetune', 'True', '--tokenizer', 'pinyin', '--log_samples', 'True', '--logger', 'wandb']' returned non-zero exit status 1.`
