### ISSUE TITLE
trained voice playback gui

### ISSUE THREAD

**Issue by dpp-user** [SWivid/F5-TTS#368]
Hello

I finetuned a voice using the finetune_gradio.py succesfully, now how am im using it as the model with the infer_gradio normal gui and not only in test tab of the finetune gui?

is it a way to load the trained checkpoint with the normal infer_gradio gui? also why do i need a voice reference if i already trained a model which i want that specific voice?

Thank you

**Comment by jpgallegoar** [comment]
An easy way to do it is to launch the app and look for this in the terminal:

"
vocab :  D:\AI\F5-TTS\src\f5_tts\infer\examples\vocab.txt
tokenizer :  custom
model :  C:\Users\thega\.cache\huggingface\hub\models--SWivid--F5-TTS\snapshots\995ff41929c08ff968786b448a384330438b5cb6\F5TTS_Base\model_1200000.safetensors
"

now go to that model path and put your new model with the name "model_1200000.safetensors". Make sure to reduce the model selecting safetensors type in the finetune_gradio app

**Comment by dpp-user** [comment]
> An easy way to do it is to launch the app and look for this in the terminal:
> 
> " vocab : D:\AI\F5-TTS\src\f5_tts\infer\examples\vocab.txt tokenizer : custom model : C:\Users\thega.cache\huggingface\hub\models--SWivid--F5-TTS\snapshots\995ff41929c08ff968786b448a384330438b5cb6\F5TTS_Base\model_1200000.safetensors "
> 
> now go to that model path and put your new model with the name "model_1200000.safetensors". Make sure to reduce the model selecting safetensors type in the finetune_gradio app

Thanks i will try it. it would be awesome if we could get an option on the gui to switch models on the fly like in rvc. also i really 
liked the chat option if only we could use other models than the qwen. 

f5-tts is really good has a great potential if it could integrate with other platforms

**Comment by jpgallegoar** [comment]
I'm planning on implementing something like that when the open source community releases some finetunes. I'm doing spanish, which did you do?

About Chat, which model would you like to use? I also thought about making the model swappable

**Comment by dpp-user** [comment]
i did some english finetune not other lang
i thought a more powerful models like lllama 3.2 and more uncensored models as well.

**Comment by jpgallegoar** [comment]
oh nice. I mean if you want you can change what model you want in the code it's really easy. it's not trivial implementing the dropdown because for example huggingface spaces can't do that (they have a single instance for many users using the same model)

**Comment by dpp-user** [comment]
i tried but i couldnt make it to work. i even tried to load it from my local pc and not hf and still didnt work

**Comment by dpp-user** [comment]
Anyone knows how to swap the model for the chat section? like use other models and not the qwen

**Comment by dpp-user** [comment]
> > Anyone knows how to swap the model for the chat section? like use other models and not the qwen
> 
> you can change it in the code, where it loads Qwen in infer_gradio.py, you can put any huggingface LLM.

i couldnt do it, i tried using chatgpt but i get an error. can help with what to change and how? like example

**Comment by jpgallegoar** [comment]
> > > Anyone knows how to swap the model for the chat section? like use other models and not the qwen
> 
> > 
> 
> > you can change it in the code, where it loads Qwen in infer_gradio.py, you can put any huggingface LLM.
> 
> 
> 
> i couldnt do it, i tried using chatgpt but i get an error. can help with what to change and how? like example
> 
> 

Well ChatGPT isn't in huggingface obviously. You'd need to integrate the API yourself, that's currently out of scope.

**Comment by dpp-user** [comment]
> > > > Anyone knows how to swap the model for the chat section? like use other models and not the qwen
> > 
> > 
> > > 
> > 
> > 
> > > you can change it in the code, where it loads Qwen in infer_gradio.py, you can put any huggingface LLM.
> > 
> > 
> > i couldnt do it, i tried using chatgpt but i get an error. can help with what to change and how? like example
> 
> Well ChatGPT isn't in huggingface obviously. You'd need to integrate the API yourself, that's currently out of scope.

i meant chatgpt guidance, well i thought it is something simple like only directing to hugging face model page.

Thanks anyway

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions~
