### ISSUE TITLE
Training a new language - two questions.

### ISSUE THREAD

**Issue by juangea** [SWivid/F5-TTS#369]
Hi there, I want to try to train a new language, I will use the librispeech dataset in spanish to start the trial, but I have a pair of questions:

1.- When I download the dataset it comes in "arrow" format, does the train webui support that?
The dataset is already transcribed, so I assume it shoudl work, but I want to know if I have to unpack it or not.

2.- Regarding the training, I assume that the training we can do in the UI is more a fine tuning of the existing model more than a full traning, if that's the case, the new fine tuning will have the same CC-BY-NC license, I will do the test anyways, but for future traning the question is:

- Are you going to traing a new model with a different license? 
- If that's the case, do you have any estiamte? 

Please keep in mind that I'm asking this with the most possible respect to your work and the project, not trying to rush anything or to push anything, just want to know the situation.

Thanks!

**Comment by SWivid** [comment]
1. two ways: 
      - tailor a customed dataloader and modified code for finetuning ui
      - change the dataset in format compatible with current dataloader
2. we have such plan, the crucial part is data
      - the estimate is: we will test on current dataset and focus on the model part, then we will start a larger-scale pretraining taking in license concerns
      - as you know, we don't have that much computation resources to always release a cc-by version for each update step

**Comment by juangea** [comment]
Thanks for this @SWivid 

for 1 I extracted all the wavs, I'm trying fro a 9 hour dataset in one 3090, if all goes well I will try in a 4090 that I have in a different computer :)

As for 2, I imagine, I just hope you can release a base model under a license that can actually be used, otherwise we will be in the same case as with Fish Speech, wich is also great, but cannot be really used.

Once again, thanks a lot for the project and your efforts, I'll keep posted the results of what I'm trying :)

**Comment by juangea** [comment]
@SWivid is there a way to contact you via email or PM?

**Comment by SWivid** [comment]
@juangea email is fine, in [paper](https://arxiv.org/pdf/2410.06885)
