### ISSUE TITLE
Cantonese needed!

### ISSUE THREAD

**Issue by huangkun1985** [SWivid/F5-TTS#37]
Please vote for Cantonese!!!

**Comment by SWivid** [comment]
b（￣▽￣）d

**Comment by wong813** [comment]
Yes Cantonese needed!!!

**Comment by ringolam** [comment]
Strongly request to have Cantonese language

**Comment by elbartohub** [comment]
Yes, one of the most powerful language on Earth

**Comment by pebblehack** [comment]
It's not an issue but- Cantonese would be neat.

**Comment by indiejoseph** [comment]
+1

**Comment by niknah** [comment]
> ### Dataset Details
> * Dataset: Common Voice Corpus 19.0
> * Validated Hours: 109 hours
> * Training Steps: ~190K steps

The fork by rumourscape uses a smaller F5 model.  They used it to train on 80 hours of data.
https://github.com/SWivid/F5-TTS/pull/534

**Comment by ZhikangNiu** [comment]
This issue will be discussed at https://github.com/SWivid/F5-TTS/issues/87, and we will close this issue.

**Comment by coffeedrinker2021** [comment]
When the Cantonese model will be available for F5-FSS ?
