### ISSUE TITLE
output without content, silent

### ISSUE THREAD

**Issue by armthug213** [SWivid/F5-TTS#370]
Hello, I have a problem in an Hp 15-dk0056wm gaming laptop with 4 gigs of vram, installs everything well but the output audio is generated without content silent. It seems to be as long as it should be, but without content.

![iuohui](https://github.com/user-attachments/assets/4f7f4af0-51db-4ed1-a9ce-e76da61e5efa)
![inin](https://github.com/user-attachments/assets/701f34c7-1e9b-4540-b64b-e86c961d963d)
![bibhibb](https://github.com/user-attachments/assets/c86c52c9-d042-41e5-88fb-2651906bd498)
![inikn](https://github.com/user-attachments/assets/034fcbd0-3f23-40d5-a2f1-3d2456dca616)

kindly help ... thanks

**Comment by SWivid** [comment]
Hi @armthug213 , thanks for reporting this and give a clear screenshot.
We might go to #356 and have discussion there as it's common issue.
