### ISSUE TITLE
UnboundLocalError: local variable 'bigvgan' referenced before assignment

### ISSUE THREAD

**Issue by trigsoft** [SWivid/F5-TTS#371]
I tried on colab. it works fine with default vocoder. 

It returned the error when using bigvgan.

**Comment by ZhikangNiu** [comment]
@trigsoft Can you provide your code to help me reproduce this problem

**Comment by trigsoft** [comment]
https://colab.research.google.com/drive/1PHd9Vy6Mf5hNXcudNl8nV9iDv4ht2LTq?usp=sharing   

I will send a mail to you with a ref audio. I cannot gen an proper audio with the same content....

**Comment by ZhikangNiu** [comment]
@trigsoft you need to clone bigvgan follow README instruction, or the following command
<img width="971" alt="截屏2024-11-02 22 11 46" src="https://github.com/user-attachments/assets/153a6648-6cc7-477b-b45f-7aff77ffa2db">

**Comment by ZhikangNiu** [comment]
<img width="859" alt="截屏2024-11-02 22 13 29" src="https://github.com/user-attachments/assets/62b1fb00-06f6-4016-86e6-49d5f9e66916">

**Comment by ZhikangNiu** [comment]
More details is written on the README

**Comment by trigsoft** [comment]
Can you send me the link please? I don't see the git clone line? 

This is what I see
# git submodule update --init --recursive  # (optional, if need bigvgan)

**Comment by trigsoft** [comment]
Same error. 

!git clone https://github.com/SWivid/F5-TTS.git
%cd F5-TTS/src/third_party
!git clone https://github.com/NVIDIA/BigVGAN.git
%cd ../..
!pip install -e .

**Comment by ZhikangNiu** [comment]
> Same error.
> 
> !git clone https://github.com/SWivid/F5-TTS.git %cd F5-TTS/src/third_party !git clone https://github.com/NVIDIA/BigVGAN.git %cd ../.. !pip install -e .

have you changed the bigvgan source code?

**Comment by trigsoft** [comment]
> > Same error.
> > !git clone https://github.com/SWivid/F5-TTS.git %cd F5-TTS/src/third_party !git clone https://github.com/NVIDIA/BigVGAN.git %cd ../.. !pip install -e .
> 
> have you changed the bigvgan source code?

Current code:
!pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
!git clone https://github.com/SWivid/F5-TTS.git
%cd F5-TTS/src/third_party
!git clone https://github.com/NVIDIA/BigVGAN.git
%cd ../..
!pip install -e .

Modified code:
# Copyright (c) 2024 NVIDIA CORPORATION.
#   Licensed under the MIT license.

# Adapted from https://github.com/jik876/hifi-gan under the MIT license.
#   LICENSE is in incl_licenses directory.
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import os
import json
from pathlib import Path
from typing import Optional, Union, Dict

import torch
import torch.nn as nn
from torch.nn import Conv1d, ConvTranspose1d
from torch.nn.utils import weight_norm, remove_weight_norm

import activations
from utils import init_weights, get_padding
from alias_free_activation.torch.act import Activation1d as TorchActivation1d
from env import AttrDict

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
