### ISSUE TITLE
Batched inference with multiple texts at once

### ISSUE THREAD

**Issue by singularity-s0** [SWivid/F5-TTS#372]
The current inference script only supports generating one audio per pass, which is slow and inefficient for massive speech generation. However, the evaluation script supports batched inference where a list of text is passed to the model and the inference  process is split among multiple GPUs. It would be nice if the inference script supported batched inference across multiple GPUs  too, just like the evaluation script.

I wonder if there are any plans to implement this? Thanks for the great work.

**Comment by SWivid** [comment]
Hi @singularity-s0 , batch inference with ddp generally needs more gpu thus serves more as an advanced operation. In this case, there would be many scenarios of batch inference compared to single inference. It is very welcome some PR for it.

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions~
