### ISSUE TITLE
Error with inference following guide/instructions after a fresh install

### ISSUE THREAD

**Issue by Simplereally** [SWivid/F5-TTS#374]
Following guide with provided test wav (and any other files tried) produces a silent error, no inference output.

Fresh install.

![image](https://github.com/user-attachments/assets/e3429c17-9880-4082-82ad-62ad38dfaf5b)

![image](https://github.com/user-attachments/assets/8b29c2c5-afa6-4a97-bc69-768dac38533a)

**Comment by SWivid** [comment]
@Simplereally Hi, it seems you are doing training/finetuning but not inference.
Check the script, should be `f5-tts_infer-gradio`

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
