### ISSUE TITLE
Training using a checkpoint or a safetensor I trained before

### ISSUE THREAD

**Issue by juangea** [SWivid/F5-TTS#380]
Hi there, I have tested to fine tune a model, now I want to use it as a base for another fine tune, how can I do that?

I don't see any place int he Gradio UI to define the model to use as the base model to train.

I assume that when we use the Gradio UI we are finetuning over the F5 provided model, am I right?

Probably I do have to change something in the code, I'm ok with that, I want to specify the path to my F5 safetensors model so I can fine tune it with a different dataset.

¡Thanks!

**Comment by jpgallegoar** [comment]
Place your model named as "model_last.pt" in the ckpts/your_new_project/model_last.pt. The finetune gradio should automatically detect and use that one now. You should see in the terminal it doesn't start from step 0 and you know it worked

**Comment by juangea** [comment]
Ah ok, si I créate a new project, with the new dataset, the. I copy the model there and then I continue the training of that checkpoint with the new dataset, correct?

thanks a lot!

**Comment by juangea** [comment]
I did it and the training continued, however in mey other dataset I got 580 epochs, but when I started with this dataset i told me that iot was around 2600 epochs, I don't understand why.

I'm training right now so I don't know if the dataset will work correctly, I'll test it in an hour or so.

**Comment by lpscr** [comment]
@juangea you can also put the path when your check point it's 

to fintune the new model you need first covert to small_model other you continue the train where you left with new dataset 

![image](https://github.com/user-attachments/assets/ea6c0f82-9a74-43cd-8992-914a51fe461f)

**Comment by Gonzaluigi** [comment]
> @juangea you can also put the path when your check point it's
> 
> `data/my_project` like this take this check point and finetune or if you have already inside the `model_steps.pt ` in your project `data/new_project/model_steps.pt` find automatic `model_steps.pt` and use this to finetune
> 
> but first need reduse the model to fintune the new model you need first `reduse `covert to small_model other you continue the train where you left with new dataset see video help #143
> 
> ![image](https://private-user-images.githubusercontent.com/147736764/382574065-ea6c0f82-9a74-43cd-8992-914a51fe461f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NTA0NDQsIm5iZiI6MTczMDY1MDE0NCwicGF0aCI6Ii8xNDc3MzY3NjQvMzgyNTc0MDY1LWVhNmMwZjgyLTlhNzQtNDNjZC04OTkyLTkxNGE1MWZlNDYxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxNjA5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjhmMjc4NGY2MzViNDRjNWFkNTYyNzk5ZDY0ZDExZTRiNTlkZjQ4YWU4MTk0MzhmYTYwNmUzYzYyYjkxYjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H8y0vxkpwNFpelr_9HQVcoo8iBv1JIxvgawi2GaFBIM)

I can't finetune from the checkpoint because is giving me an argument not found error.

**Comment by lpscr** [comment]
@Gonzaluigi i cant test right now so use this 
first create new project then
put inside the reduse model_steps.pt the model  in your project data/new_project/model_steps.pt the run this must working fine

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions

**Comment by campar** [comment]
@lpscr If I understand correctly, to fine-tune a new dataset with new audio files, we need to reduce model_steps.pt and then start the new fine-tuning from model_steps_reduced.pt. 

So the only purpose of model_last.pt is to continue fine-tuning if it is interrupted or if we are not satisfied with the results and we want to continue, am I  right?
