### ISSUE TITLE
The pronunciation of uppercase English letters is not accurate

### ISSUE THREAD

**Issue by kitty359** [SWivid/F5-TTS#382]
Hello, in my actual test, I found that the pronunciation of Chinese and English (lowercase) words is very good, but when there are multiple consecutive uppercase English letters in the generated text, the pronunciation of uppercase letters often fails to align or the pronunciation is wrong. How can I alleviate this problem。

My command inference text is: "请发音ABCDEFGHIK"
[test.zip](https://github.com/user-attachments/files/17610763/test.zip)

**Comment by SWivid** [comment]
consider
https://github.com/SWivid/F5-TTS/blob/61ff2a62d9487e3362ffa5680007e788ad764065/src/f5_tts/infer/utils_infer.py#L51

**Comment by kitty359** [comment]
> 考虑
> 
> https://github.com/SWivid/F5-TTS/blob/61ff2a62d9487e3362ffa5680007e788ad764065/src/f5_tts/infer/utils_infer.py#L51
My variable does set ‘None’

**Comment by kitty359** [comment]
It will not only swallow English capital letters, but even mispronounce them

**Comment by SWivid** [comment]
what do you mean by `My variable does set ‘None’`
I mean, we could set a fix_duration e.g. `fix_duration=6` for `"请发音ABCDEFGHIK"`

> It will not only swallow English capital letters, but even mispronounce them
try fix duration or also "请发音 A B C D E F G H I K"

**Comment by kitty359** [comment]
when fix_duration=6，Inference audio cannot be generated。my ref_audio  duration is 0.06s.
just only fix_duration=None,Inference audio can be generated

**Comment by kitty359** [comment]
Thank you very much. I see what you mean. however，when fix_duration=6，Inference audio cannot be generated。my ref_audio duration is 6s.just only fix_duration=None,Inference audio can be generated

**Comment by kitty359** [comment]
oh，thank you。 i know the reason，because if ref_audio time +gen_audio。thank you

**Comment by juangea** [comment]
I'm having that problem, how did you solve it?

**Comment by kitty359** [comment]
Insert other symbols into uppercase letters, such as :" ", ", "."




九歌_萧萧
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SWivid/F5-TTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月4日(星期一) 晚上10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SWivid/F5-TTS] The pronunciation of uppercase English letters is not accurate (Issue #382)





 
I'm having that problem, how did you solve it?

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions~
