### ISSUE TITLE
Why is the new duration predictor model not being merged in this repository?

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#384]
### Checks

- [x] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I saw there's a new duration predictor that is supposedly better than the current one, why is it not merged here?

**Comment by SWivid** [comment]
Discussions at #363 
It's generally having output speech read faster, and other considerations mentioned there.
If interested, could also help with organizing modules.py in JM's fork repo which is helpful for those need a duration predictor

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
