### ISSUE TITLE
Hi, how can I specify the download directory for the model 

### ISSUE THREAD

**Issue by zhaojigang** [SWivid/F5-TTS#385]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Hi, how can I specify the download directory for the model

**Comment by ZhikangNiu** [comment]
huggingface-cli download --resume-download SWivid/F5-TTS --local-dir <YOUR PATH>

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
