### ISSUE TITLE
How can I get Emilia_ZH_EN_pinyin/duration.json？

### ISSUE THREAD

**Issue by CreepJoye** [SWivid/F5-TTS#387]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

CUDA Version: 12.0；torch 2.0.1+cu118；Python 3.10.15

### Steps to Reproduce

Create a new conda environment.
Clone the repository and install as pip package.
Run the command: f5-tts_training with test_train.py.
Stuck there with the following message... (FileNotFoundError: [Errno 2] No such file or directory: 'data/Emilia_ZH_EN_pinyin/duration.json').

### ✔️ Expected Behavior

I download [EN-B000024.tar](https://huggingface.co/datasets/amphion/Emilia-Dataset/blob/main/EN/EN-B000024.tar) on https://huggingface.co/datasets/amphion/Emilia-Dataset/tree/main and try to train the model with `test_train.py` file，but it reports an error about duration.json file.I want to know where can I find this duration.json or what's the format of it,Thank you!

Loading dataset ...
Trying to load dataset from: data/Emilia_ZH_EN_pinyin/raw
Traceback (most recent call last):
  File "/home/F5-TTS/test_train.py", line 91, in <module>
    main()
  File "/home/F5-TTS/test_train.py", line 84, in main
    train_dataset = load_dataset(dataset_name, tokenizer, mel_spec_kwargs=mel_spec_kwargs)
  File "/home/F5-TTS/model/dataset.py", line 210, in load_dataset
    with open(f"data/{dataset_name}_{tokenizer}/duration.json", 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/Emilia_ZH_EN_pinyin/duration.json'

### ❌ Actual Behavior

FileNotFoundError: [Errno 2] No such file or directory: 'data/Emilia_ZH_EN_pinyin/duration.json'

**Comment by SWivid** [comment]
> * I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.

pls check

**Comment by SWivid** [comment]
using English to submit this report in order to facilitate communication.
