### ISSUE TITLE
about frame batch size OOM

### ISSUE THREAD

**Issue by acul3** [SWivid/F5-TTS#39]
hello @SWivid 

i want to reproduce your train,

i am using 8xH100 
with amount 5k hours data

but when i use 38400 batch size i got OOM

right now i am using half of it 19200 seems working

my question :
is 38400 depend on the dataset we use ?
(i am also make sure that duration.json and data have same index in dataset collate)

also if i am about scaling it to 16 gpu what hyper parameter that you would recommend to change?

thanks

**Comment by SWivid** [comment]
1. We use torch==2.3.0 (native flash_attn for torch>=2.2), and fp16/bf16
2. 38400 is just the exact batchsize in E2 TTS paper (8*38400=307200). If OOM 19200 is fine, set grad_accumuation_steps is the same, while saved ckpt e.g. model_10000.pt is actually for 5000 updates.
3. The hyper parameter is generally with used batchsize, thought no big change with 16*19200 to 8*38400
