### ISSUE TITLE
Chinese Number Pronunciation

### ISSUE THREAD

**Issue by skyboooox** [SWivid/F5-TTS#390]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

In a Chinese sentence, all numbers are pronounced in English. 
Can it be arranged so that the entire output is in Chinese instead?

**Comment by SWivid** [comment]
#138 #244 etc.
Turn Chinese number to words.
