### ISSUE TITLE
Custom model selection in Gradio inference interface, a dropdown list, etc.

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#396]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

@SWivid Hello, I have successfully finetuned the spanish model, it's available here:
https://huggingface.co/jpgallegoar/F5-Spanish/tree/main
https://github.com/jpgallegoar/Spanish-F5

Can we go through with the idea to be able to select the model from different sources, which we will manually add into a list once quality has been assessed, and presented as a dropdown list to the users who are not using the huggingface space? Mainly for Pinokio users. This can also incentivize users to open source their models.

**Comment by SWivid** [comment]
Hi @jpgallegoar Yes, agreed before~ #339 

With `if not USING_SPACES: `, and load censored model ckpts and corresponding vocab.txt; 
or also have users freely make PR with evalution results elaborated (will an input textbox suit for those want to use self maintained ckpts?)

**Comment by SWivid** [comment]
@jpgallegoar an init custom ckpt load method (local gradio) with latest commit.
feel free to check if work~

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
