### ISSUE TITLE
Plan for other languages?

### ISSUE THREAD

**Issue by imthebilliejoe** [SWivid/F5-TTS#40]
Hi there,

Thank you for the release, you did such a great job, voice cloning quality is unbelievable.

I was wondering if by any chance you planned to extend the model to other languages beyond English and Chinese; I saw that you used Emilia dataset for pretraining so I guess that for the Emilia’s languages should be doable.

And what about languages not included in the Emilia dataset like Italian? Do you have any plan about it?

Here in Italy we’re really suffering the lack of high quality open source alternative for text to speech.

thank you and great work again.

**Comment by SWivid** [comment]
We'll try our best to train on broader corpus.
