### ISSUE TITLE
Error while generating / no audio

### ISSUE THREAD

**Issue by Takinono** [SWivid/F5-TTS#404]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 11, RTX 3070

### Steps to Reproduce

When I upload my audio sample along with my prompt and hit synthesize, nothing happens. I do have weird error messages:

![image](https://github.com/user-attachments/assets/65833961-2c15-4e90-ac3b-53828b541df9)

but it remains stuck at 0% after "Prefix dict has been built successfully".

Edit, tried in CLI, same problem

![image](https://github.com/user-attachments/assets/84e0ae6a-499c-492f-94c8-dabf0da4a5a6)

I tried following these fixes, but it doesn't solve the problem.
https://github.com/SWivid/F5-TTS/issues/356

Thanks for your help

**Comment by SWivid** [comment]
what is your torch (cuda or cpu version installed?) and cuda version, and how it the gpu usage when inference

**Comment by Takinono** [comment]
Sorry, I'm using :
Windows 11
RTX 3070
conda 24.9.2
torch Version: 2.5.1
CUDA Version: 12.3

**Comment by SWivid** [comment]
@Takinono so it seems like a torch-cpu version installed
try
`pip install torch==2.5.1+cu121 torchaudio==2.5.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121`
if you still want torch2.5.1 or just following installation instruction:
`pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`

**Comment by Takinono** [comment]
This solved the problem !
`pip install torch==2.5.1+cu121 torchaudio==2.5.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121`

Thanks !

**Comment by SWivid** [comment]
will close as solved, feel free to open if further questions
