### ISSUE TITLE
ModuleNotFoundError: No module named 'f5_tts'

### ISSUE THREAD

**Issue by Jandown** [SWivid/F5-TTS#407]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Great project, thank you to the author.
I encountered an error while running my reasoning. May I ask what the problem is?
Deploy in Windows system environment

**Comment by SWivid** [comment]
> I have thoroughly reviewed the project documentation and read the related paper(s).

Follow the installation in README.md first.
