### ISSUE TITLE
How to modify the code to save the file to the folder I specify

### ISSUE THREAD

**Issue by NiaSylvieTellpen** [SWivid/F5-TTS#411]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I am a novice and want to deploy this project on the server, but the server does not allow me to create a tmp file. Which part of the code should I modify so that it can be saved in the folder I specify? Thank you for taking the time to check my doubts.
The error is as follows: 
PermissionError: [Errno 13] Permission denied: '/tmp/gradio/dcb43344e73cf4bfdc2c1514eb5f0dc555bde0ab8b2e2da6cdc6999c0943f2ff'

**Comment by NiaSylvieTellpen** [comment]
I tried changing the environment variables of gradio, but it didn't work.

**Comment by SWivid** [comment]
If you could have root authority, try switch to root.
Otherwise need to change parts with tempile within also code scripts, e.g. 
https://github.com/SWivid/F5-TTS/blob/8a7e8495fff609cd8f4085c9efe8f2964995fc12/src/f5_tts/infer/utils_infer.py#L242
to a path you have permission

**Comment by NiaSylvieTellpen** [comment]
> 如果你有 root 权限，请尝试切换到 root。 否则，还需要使用 tempile 更改代码脚本中的部分，例如
> 
> https://github.com/SWivid/F5-TTS/blob/8a7e8495fff609cd8f4085c9efe8f2964995fc12/src/f5_tts/infer/utils_infer.py#L242
> 
> 
> 到您有权限的路径

thanks

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
