### ISSUE TITLE
加载西班牙和日语模型的时候，报错：RuntimeError: Error(s) in loading state_dict for CFM:

### ISSUE THREAD

**Issue by liuhui881125** [SWivid/F5-TTS#412]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

加载Discussions中提供的训练好的日语和西班牙语模型的时候报错：
日语报错：
model :  /root/F5-TTS/ckpts/.../model_1108224.pt

RuntimeError: Error(s) in loading state_dict for CFM:
        size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2743, 512]) from checkpoint, the shape in current model is torch.Size([2546, 512]).

西班牙语报错：
model :  /root/F5-TTS/ckpts/jpgallegoar/model_1200000.safetensors

RuntimeError: Error(s) in loading state_dict for CFM:
        Missing key(s) in state_dict: "mel_spec.mel_stft.spectrogram.window", "mel_spec.mel_stft.mel_scale.fb".

**Comment by SWivid** [comment]
> RuntimeError: Error(s) in loading state_dict for CFM:
> size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2743, 512]) from checkpoint, the shape in current model is torch.Size([2546, 512]).

Use corresponding vocab.txt

> RuntimeError: Error(s) in loading state_dict for CFM:
Missing key(s) in state_dict: "mel_spec.mel_stft.spectrogram.window", "mel_spec.mel_stft.mel_scale.fb".

pull latest repo commit

**Comment by liuhui881125** [comment]
ok.fix .good

**Comment by atlonxp** [comment]
@SWivid I have the same problem. My case is different is that I'm training for a new language, which vocab.txt is extended from the corresponding vocab. any suggestion here?

**Comment by wzr0108** [comment]
请问日语和西班牙语模型在哪里找的？
