### ISSUE TITLE
Training the model from scratch, pronunciation is unintelligible

### ISSUE THREAD

**Issue by yygg678** [SWivid/F5-TTS#413]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Using my own phone sequence, I trained the model from scratch, with about 200 hours of Chinese data and a 155M model. The synthesized speech is completely incomprehensible.
How much data is generally needed to train a model from scratch?

**Comment by SWivid** [comment]
> I have thoroughly reviewed the project documentation and read the related paper(s).

all details are given in our paper, including used training corpus for small model, batchsize, evaluation results from 400~800k updates

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
