### ISSUE TITLE
why is this code trying to create a reverse proxy?

### ISSUE THREAD

**Issue by buddylee7** [SWivid/F5-TTS#42]
why is this code trying to create a reverse proxy?

**Comment by SWivid** [comment]
Not quite understand, maybe you could provide more details for us to figure out the issue

**Comment by fat-tire** [comment]
hey @buddylee7 weird issue description-- what exactly are you referencing?

**Comment by chigkim** [comment]
Are you running the Gradio app?
"Although the link is served through the Gradio Share Servers, these servers are only a proxy for your local server, and do not store any data sent through your app."
https://www.gradio.app/guides/sharing-your-app

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.
