### ISSUE TITLE
infer_cli use wrong ref_text rather than ASR if not set ref_text

### ISSUE THREAD

**Issue by oska117** [SWivid/F5-TTS#429]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

RTX 4070, python 3.10, torch==2.3.0+cu118, torchaudio==2.3.0+cu118

### Steps to Reproduce

If the `--ref_text` parameter is not set, the system will always use the default ref_text (i.e., `Some call me nature, others call me mother nature.` from src/f5_tts/infer/examples/basic/basic.toml ), instead of using the ASR output from openai-whisper.

```
f5-tts_infer-cli 
--model "F5-TTS" 
--ref_audio "E:\data\dezhan_13s.m4a" 
--gen_text "Today is a beautiful day, and the sun is shining brightly in the sky. The birds are singing, and the flowers are blooming. " --load_vocoder_from_local
```

### ✔️ Expected Behavior

If the "ref_text" not set, should use the ASR output instead of the default text , related code:
```
ref_text = args.ref_text if args.ref_text != "666" else config["ref_text"]
```

### ❌ Actual Behavior

output:
```
Load vocos-mel-24khz from local path ckpts/vocos
Using F5-TTS...

vocab :  E:\MyProject\F5-TTS\src\f5_tts\infer\examples\vocab.txt
tokenizer :  custom
model :  ckpts/F5TTS_Base/model_1200000.safetensors

Converting audio...
Using custom reference text...
Voice: main
Ref_audio: C:\Users\MechRevo\AppData\Local\Temp\tmp4lw8skb0.wav
Ref_text: Some call me nature, others call me mother nature.
No voice tag found, using main.
Voice: main
gen_text 0 Today is a beautiful day,
gen_text 1 and the sun is shining brightly in the sky.
gen_text 2 The birds are singing, and the flowers are blooming.
Generating audio in 3 batches...
  0%|                                                                                                                 | 0/3 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\MechRevo\AppData\Local\Temp\jieba.cache
Loading model cost 0.398 seconds.
Prefix dict has been built successfully.
D:\dev\miniconda\envs\f5-tts\lib\site-packages\torch\functional.py:665: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ..\aten\src\ATen\EmptyTensor.cpp:42.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
E:\MyProject\F5-TTS\src\f5_tts\model\modules.py:359: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  x = F.scaled_dot_product_attention(query, key, value, attn_mask=attn_mask, dropout_p=0.0, is_causal=False)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.57s/it]
tests\infer_cli_out.wav
```
![image](https://github.com/user-attachments/assets/81247e19-8501-44dc-bc8a-ae4aea5c1e05)

Although a wav file is generated, all the content inside is incorrect.

**Comment by SWivid** [comment]
> I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.

> If the "ref_text" not set, should use the ASR output instead of the default text , related code:

1. if note provide, will use default in toml.
2.  `# If an empty "", transcribes the reference audio automatically.` and `# Leave --ref_text "" will have ASR model transcribe (extra GPU memory usage)` in readme
