### ISSUE TITLE
How to  customizable Voices?

### ISSUE THREAD

**Issue by ldgoooo** [SWivid/F5-TTS#430]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Does it support some custom parameters, such as tone, pitch, softened voice, etc.?

**Comment by SWivid** [comment]
> I have thoroughly reviewed the project documentation and read the related paper(s).

could use ref_audio to control
