### ISSUE TITLE
How do I change the A.I. model used in the F5-TTS "voice chat" mode?

### ISSUE THREAD

**Issue by kaboombomberz** [SWivid/F5-TTS#436]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 10 Pro
Python 3.10

### Steps to Reproduce

Start F5-TTS Local interface
go to "voice chat" tab

### ✔️ Expected Behavior

Model complies with all the request, including NSFW ones

### ❌ Actual Behavior

Model denies to engage with NSFW related conversations even after using the 'advanced settings' system prompts. 

If there was a way to connect it to run your own model (such as mixtral) it would be great

**Comment by SWivid** [comment]
Hi @kaboombomberz , that might not be supported with official code as it's sync with hf and other platforms.
You could modify the part in https://github.com/SWivid/F5-TTS/blob/c33a83c0094ca4c62c1d193cf457a5e2a2e9d87a/src/f5_tts/infer/infer_gradio.py#L487
with any llm fit in cuz it's currently a cascaded chat system (asr+llm+tts).

**Comment by dpp-user** [comment]
i would like to know as well if someone managed to do that, i tried so much time without a success.

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions

**Comment by GawainProdigy** [comment]
There is a readme file in (F5-TTS\src\f5_tts\infer) that explains how to use your own model.

**Comment by kaboombomberz** [comment]
Oh that is HUGE, thank you so much!! I couldnt get around to doing it, this really helps!

**Comment by dpp-user** [comment]
> There is a readme file in (F5-TTS\src\f5_tts\infer) that explains how to use your own model.

all it mention is that you can download a model manually and edit the path in infer_gradio.py

it not mentioning what else you need to change there cause there are lots of lines related to qwen model. 

any help would be appreciated
