### ISSUE TITLE
After fine-tuning the original model with other languages, I can no longer speak Chinese and English properly when reasoning in both languages. However, my newly tuned language is becoming more and more similar. I want to keep both Chinese and English with my newly added language. Did I do something wrong?

### ISSUE THREAD

**Issue by 0x1001u** [SWivid/F5-TTS#438]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

After fine-tuning the original model with other languages, I can no longer speak Chinese and English properly when reasoning in both languages. However, my newly tuned language is becoming more and more similar. I want to keep both Chinese and English with my newly added language. Did I do something wrong?
BTW The audio I used is 16000Hz, and the tokenizer I selected is custom. I don't know if this has any impact.

**Comment by SWivid** [comment]
@0x1001u You could keep some English and Chinese data while finetuning, do such a mixed training would help mitigate catastrophic forgetting problem

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions~
