### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by TheMattBin** [SWivid/F5-TTS#450]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Hi, thanks for the great work! I've checking quite few issues related to training or finetuning. As what I can see from license, does it mean that model either trained/finetuned from [training script](https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train) or gradio UI is under non-CC? Thanks!

**Comment by SWivid** [comment]
Hi @TheMattBin , at the bottom of main page readme.md
![image](https://github.com/user-attachments/assets/198847cc-c1ce-4c2e-b123-8745306b10b0)
