### ISSUE TITLE
generate  streams API

### ISSUE THREAD

**Issue by duanx123** [SWivid/F5-TTS#457]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Can streaming speech synthesis return binary streams by calling methods in the form of APIs? If so, how should it be done

**Comment by mhenrichsen** [comment]
But does this actually make it faster? It seems that it has to generated the whole speech before sending it anyway?

**Comment by kresle** [comment]
> I found this [socket-realtime-client](https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/infer#socket-realtime-client)

Most APIs use `infer_process` from `utils_infer.py`, and `infer_process` will call `infer_batch_process` instead. So they all end up with the same function, there should be no differences in terms of inference speed.
