### ISSUE TITLE
Question : anybody got "PytorchStreamWriter failed writing file data.pkl" while training ?

### ISSUE THREAD

**Issue by x4080** [SWivid/F5-TTS#458]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Error look like this
```
Epoch 4/5:   0%|                 | 0/33 [00:01<?, ?step/s, loss=0.688, step=100]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/conda/envs/venv/lib/python3.10/site-packages/torch/serialization.py", line 652, in save
[rank0]:     _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
[rank0]:   File "/opt/conda/envs/venv/lib/python3.10/site-packages/torch/serialization.py", line 866, in _save
[rank0]:     zip_file.write_record('data.pkl', data_value, len(data_value))
[rank0]: RuntimeError: [enforce fail at inline_container.cc:778] . PytorchStreamWriter failed writing file data.pkl: file write failed
```

Before was working fine just before finishing epoch ex target is 5 epoch it will slow down and maybe memory leak ? So I just canceled the training

here's the parameter of training I did :

```
accelerate launch --mixed_precision=fp16 src/f5_tts/train/finetune_cli.py --exp_name F5TTS_Base --learning_rate 7.5e-05 --batch_size_per_gpu 2742 --batch_size_type frame --max_samples 64 --grad_accumulation_steps 1 --max_grad_norm 1 --epochs 5 --num_warmup_updates 2 --save_per_updates 300 --last_per_steps 100 --dataset_name my_speak --tokenizer char --log_samples True --logger wandb
```

**Comment by SWivid** [comment]
check if have sufficient disk space

**Comment by x4080** [comment]
@SWivid Yes, thats what I thought earlier but it have lot of space, the strange thing is it works before and running it to 80 epochs

**Comment by x4080** [comment]
I retried it again the next day and the error is no more dont know what happened (its a rented gpu), I guess I just close it for now
