### ISSUE TITLE
Is it possible to implement true speech to speech?

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#46]
What I mean by speech to speech is that, apart from having the reference voice as input, you could have another voice recording of your own as input, and then the output would match what you are saying with the reference voice, not only adhering to the words (otherwise it would be as simple as speech recognition with whisper in the middle), but also adhering to the intonation, timing, emotion, etc. ElevenLabs has a similar feature to this. 

Is it fundamentally possible to implement in this model architecture?

**Comment by SWivid** [comment]
Kind of depicting a process of voice cloning, thought it would be possible but with a modified training task (currently following Voicebox's in-filling task)
Something interesting with our ablation expr., see https://arxiv.org/pdf/2410.06885 Sec 5.2. Guess some way out there.

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.
