### ISSUE TITLE
bigvgan and vocos

### ISSUE THREAD

**Issue by 1750585724** [SWivid/F5-TTS#463]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Hello, I have an inference issue: With the same audio and text, the synthesized audio quality using "BigVGAN" is significantly worse compared to "Vocos". What could be the reason?

**Comment by ZhikangNiu** [comment]
seedtts eval | wer | sim |
|--|--|--|
16nfe en(bf16) | WER: 1.58%（1.89(vocos) → 1.58(bigvgan)） |  
32nfe en(bf16) | WER : 1.57%（1.83(vocos) → 1.57(bigvgan)） | SIM: 0.66（0.67(vocos)->0.66(bigvgan))
16nfe zh(bf16) | WER : 1.62%（1.74(vocos) → 1.62(bigvgan)） |  
32nfe zh(bf16) | WER : 1.52%（1.56(vocos) → 1.52(bigvgan)） | SIM: 0.74（0.76(vocos)->0.74(bigvgan)）

**Comment by 1750585724** [comment]
我是使用的infer_gradio.py去进行推理的，我想您可以听一下我合成音频的音质，谢谢
[wav.zip](https://github.com/user-attachments/files/17742357/wav.zip)

**Comment by ZhikangNiu** [comment]
> 我是使用的infer_gradio.py去进行推理的，我想您可以听一下我合成音频的音质，谢谢 [wav.zip](https://github.com/user-attachments/files/17742357/wav.zip)

我没有用过infer_gradio,所以里面可能有些东西没有适配，我的建议是是适用cli infer

**Comment by TomSuen** [comment]
为什么同样的文本和参考音频，使用cli的效果比gradio效果差呢？
