### ISSUE TITLE
Possible cast needed

### ISSUE THREAD

**Issue by RaduBolbo** [SWivid/F5-TTS#467]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Ubuntu LTS 24; Python 3.11.10

### Steps to Reproduce

1. Create a conda environment with Python 3.11.10
2. install requirements via `pip install -e .`
3. Download and unarchive Emilia dataset from EN-B000000 to EN-B000019 (so just the first 20 folders for English) and the first 10 from Chinese (ZH-B000000 to ZH-B000010). 
4. Run train/datasets/prepare_emmilia.py script to obtain the duration.json, raw.arrow and vocab.txt files (with a modification: account only for the included subset, not all Emilia)
5. Replace in the dataset directory vocab.txt with the pretrained model's vocab.txt
6. Run train/datasets/train.py with the default hyperparameters and modfiied:
- batch_size_per_gpu = 384 (batch_size_type = "frame").
- num_warmup_updates = 20 
- save_per_updates = 50
- last_per_steps = 50

### ✔️ Expected Behavior

Train

### ❌ Actual Behavior

After 49 batches, I get `TypeError: can only concatenate str (not "list") to str` at ` text=[text_inputs[0] + [" "] + text_inputs[0]]` in src/train/train.py

After inspecting the types, test_inputs[0] is a string and [""] is a list. Because so many succeeded training I guess that test_inputs[0] shouldn't actually be a string but a list.

Is this a problem with the dataset formatting?

**Comment by ZhikangNiu** [comment]
```python
text = [" ".join([text_inputs[0], text_inputs[0]])]
```

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
