### ISSUE TITLE
Hello bro!

### ISSUE THREAD

**Issue by Juranik** [SWivid/F5-TTS#47]
One question... WhY sO SeRious?!?! *beatboxing...*
Agh, alr..sry...

Will u add Russian language?... What specifications are needed for a computer to process everything quickly? On my laptop with a 3060 6GB, it takes a very long time to process. Will there be optimization for this in the future?

**Comment by XLED-bd** [comment]
Same problem: I need to train the model with 50k hours of English speech, and with a 3060 12 GB it takes 3 years... and then add 50k hours of Russian speech, which is another 3 years, for a total of 6 years 🤗

**Comment by SeraDreams** [comment]
I have a 1660ti with 6GB and I couldn't even start the training, it would be really cool if they added Russian

**Comment by ZhikangNiu** [comment]
We'll try our best to train on broader corpus! So, be patient！And our model was trained on A100 and you'd better train the model on > 24G machine.

**Comment by ZhikangNiu** [comment]
I'll close this issue, if you have other questions you can reopen this issue. @SeraDreams @Juranik @XLED-bd

**Comment by nitinmukesh** [comment]
@ZhikangNiu 

You have created an amazing tool like I mentioned in one of the earlier post.

Supporting more languages like e.g. Hindi, Russian will be very helpful for end users who don't know anything about code forget training.
