### ISSUE TITLE
Moving storage, but f5 still load from old location

### ISSUE THREAD

**Issue by AlpacaManAlpha** [SWivid/F5-TTS#471]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I cloned my f5 installation to a new drive (E:\ -> Y:\) and ran f5-tts_finetune-gradio from the new location.
Seems the path for my data checkpoints is still mapped to E:\. I need help to re-map, so I can delete the data on the source drive.

**Comment by SWivid** [comment]
`pip uninstall f5-tts`
Do `pip install -e .` at new path.

**Comment by AlpacaManAlpha** [comment]
This worked, thank you!
