### ISSUE TITLE
Suggestion for creating a discord server

### ISSUE THREAD

**Issue by Bubarinokk** [SWivid/F5-TTS#472]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

I didn't find anyone talking about the existence of a future server on discord. 

### 2. What is your suggested solution?

Have you thought about creating a discord server? It's a great idea for creating a community. Several people sharing results and helping others.

### 3. Additional context or comments

Here is the website discord.com

### 4. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by SWivid** [comment]
Hi @Bubarinokk , thanks for the idea

We mainly focus on GitHub issues and take Discussion boards as the place for sharing. Also we have added recently here a [more open way to share models](https://github.com/SWivid/F5-TTS#:~:text=Custom%20model%20inference%20(local%20only)). 

We are open to helpful PRs and are not against (even welcome) self-organized discord channels, 
e.g. at very early time pinokio has already very nice tutorials,
 and we heard the discord community there people helping others with F5 usage (we appreciate it~)

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
