### ISSUE TITLE
The word "natura" keeps being added randomly to generated speech

### ISSUE THREAD

**Issue by showgan** [SWivid/F5-TTS#474]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I was able to finetune the F5 model for a new language (Adyge). The quality is good in general, but there is one annoying issue: a word keep being synthesized and added occassionally even though this word is not in the input text.
Furthermore, this word is not even a word in the new language.
The word sounds like "natura" which I don't know if there is even such a word in English or in Chinese (which I assume are the original languages in the base model).

I checked my text pre-processing and I don't see this word getting added by mistake in the processed text.

My questions are:
1) Is this simply an indication that I just need a larger dataset? just to reiterate, I get a decent quality with the current dataset - except for this hallucination issue.

2) Is there a workaround that I can apply? maybe fill in spaces or other filler tokens in some places in the processed text in case this could be related to too short texts or to too long gaps/pauses?

Thanks.

**Comment by SWivid** [comment]
Hi @showgan , some guesses:
1. is there any punctuation interpreted to a sound like "natura"? e.g. you might provide the reference audio & text, used gen_text and generated result for us to help figure out where the issue typically exists
2. are there any watermarks in the audio samples of dataset you use to finetune like "natura", say, there exist some utterance like "natura" while no corresponding transcription text is in the data pair.

**Comment by showgan** [comment]
Hi @SWivid, thank you so much for the super quick response :)

I actually figured out the problem after you've mentioned the reference audio and refernce text.
I initially totally forgot about this - that I had to use reference audio and reference text in the new language.
I had planned to do this but forgot, so the inference code used the defaults defined in the exampel toml file which are in English.
After I provided new ones in the new language then the problem seems to have disappeared, based on a few samples that I have tested (and these samples did cause this issue before this change).

So, thanks again so much. You've been very helpful.

A quick follow-up question: when I train with a single speaker then it seems that multiple speaker voices in the base model are forgotten, and hence voice cloning doesn't actually work anymore - no matter what reference audio I use I always get the voice of the single speaker that I used for the finetuning. Is that the expected behavior?

**Comment by SWivid** [comment]
> A quick follow-up question: when I train with a single speaker then it seems that multiple speaker voices in the base model are forgotten, and hence voice cloning doesn't actually work anymore - no matter what reference audio I use I always get the voice of the single speaker that I used for the finetuning. Is that the expected behavior?

Yes, the commonly put question - catastrophic forgetting problem.
Having a mixed dataset to avoid/mitigate this. To be specific, if have multi-speaker dataset in Adyge, the best; or could mix in some English/Chinese multi-speaker data to help retain the diversity (if no confict with vocab, will work)

Glad that you got some nice result, feel free to share if once satisfied with future ckpt and of course if willing~
https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/infer/SHARED.md

**Comment by showgan** [comment]
Thanks again.
Sure, I will share once I reach a satisfactory quality, and I'll try to train a multi-speaker model first.
