### ISSUE TITLE
Install boto3 and botocore looping downloads; apple silicon, mps, mac device.

### ISSUE THREAD

**Issue by aboutmydreams** [SWivid/F5-TTS#475]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Apple M2 Ultra
python3.12

### Steps to Reproduce

git clone https://github.com/SWivid/F5-TTS.git
cd  F5-TTS
pip install -e .

### ✔️ Expected Behavior

Install boto3 and botocore normally without looping downloads

### ❌ Actual Behavior

Collecting botocore<1.35.0,>=1.34.11 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.11-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.10-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.10 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.10-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.9-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.9 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.9-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.8-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.8 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.8-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.7-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.7 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.7-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.6-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.6 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.6-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.5-py3-none-any.whl.metadata (6.6 kB)
Collecting s3transfer<0.10.0,>=0.9.0 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading s3transfer-0.9.0-py3-none-any.whl.metadata (1.7 kB)
Collecting botocore<1.35.0,>=1.34.5 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.5-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.4-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.4 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.4-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.3-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.3 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.3-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.2-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.2 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.2-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.1-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.1 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.1-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.34.0-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.35.0,>=1.34.0 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.34.0-py3-none-any.whl.metadata (5.6 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.13-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.13 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.13-py3-none-any.whl.metadata (6.1 kB)
Collecting s3transfer<0.9.0,>=0.8.2 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading s3transfer-0.8.2-py3-none-any.whl.metadata (1.8 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.12-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.12 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.12-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.11-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.11 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.11-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.10-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.10 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.10-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.9-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.9 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.9-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.8-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.8 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.8-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.7-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.7 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.7-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.6-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.6 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.6-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.5-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.5 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.5-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.4-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.4 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.4-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.3-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.3 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.3-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.2-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.2 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.2-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.1-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.1 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.1-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.33.0-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.34.0,>=1.33.0 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.33.0-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.29.7-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.33.0,>=1.32.7 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.32.7-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.29.6-py3-none-any.whl.metadata (6.7 kB)
Collecting s3transfer<0.8.0,>=0.7.0 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading s3transfer-0.7.0-py3-none-any.whl.metadata (1.8 kB)
Collecting botocore<1.33.0,>=1.32.6 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.32.6-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.29.5-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.33.0,>=1.32.5 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.32.5-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.29.4-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.33.0,>=1.32.4 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.32.4-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.29.3-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.33.0,>=1.32.3 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.32.3-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.29.2-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.33.0,>=1.32.2 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.32.2-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.29.1-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.33.0,>=1.32.1 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.32.1-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.29.0-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.33.0,>=1.32.0 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.32.0-py3-none-any.whl.metadata (6.1 kB)
Collecting boto3<2.0,>=1.0 (from cached-path->f5-tts==0.1.1)
  Downloading boto3-1.28.85-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.32.0,>=1.31.85 (from boto3<2.0,>=1.0->cached-path->f5-tts==0.1.1)
  Downloading botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)

**Comment by SWivid** [comment]
Hi @aboutmydreams ,try with a neat env to setup.
See the first step of installation
```
# Create a python 3.10 conda env (you could also use virtualenv)
conda create -n f5-tts python=3.10
conda activate f5-tts
```

**Comment by aboutmydreams** [comment]
> try with a neat env to setup.
> See the first step of installation


I find the reason, bitsandbytes is not suport on apple silicon

**Comment by SWivid** [comment]
With help of #477 , cb8ce3306d70dfbee0e7d2423cc7f06e1c2b9c60 to address.
Will close here~
