### ISSUE TITLE
the url to download the audio by the event_id is incorrect

### ISSUE THREAD

**Issue by liuhui881125** [SWivid/F5-TTS#484]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

whatever

### Steps to Reproduce

1. curl -X POST http://x.x.x.x:7860/call/basic_tts -s -H "Content-Type: application/json" -d '{
  "data": [
							{"path":"https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav"},
							"Hello!!",
							"Hello!!",
							true,
							0,
							0.3]}'
2. curl -N http://x.x.x.x:7860/call/basic_tts/$EVENT_ID

### ✔️ Expected Behavior

the url is incorrect, '/cal' should be remove.

![Uploading image.png…]()

### ❌ Actual Behavior

bug

**Comment by liuhui881125** [comment]
![image](https://github.com/user-attachments/assets/8ff03f8c-c1e2-4f02-9ac9-d8e2008fc349)

**Comment by SWivid** [comment]
Maybe elaborate more on the relationship with this repo?
Thanks in advance~

**Comment by liuhui881125** [comment]
This bug should be caused by Gradio. I saw in Gradio's repo that someone mentioned a similar [issue](https://github.com/gradio-app/gradio/issues/9317) in September, but it has not been resolved yet.
