### ISSUE TITLE
Error in training a Vietnamese voice model

### ISSUE THREAD

**Issue by ManH170** [SWivid/F5-TTS#486]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Win 11
 ### GPU Stats
GPU 0 Name: NVIDIA GeForce RTX 3070 Ti
Total GPU memory (GPU 0): 8.00 GB
Allocated GPU memory (GPU 0): 0.00 MB
Reserved GPU memory (GPU 0): 0.00 MB

### CPU Stats
CPU Usage: 3.10%
System Memory: 10103.20 MB used / 32527.68 MB total (31.1% used)
Process Priority (Nice value): 32
torch=2.3.0
python=3.12.7

### Steps to Reproduce

Training data like usual with vocab check and extend. Prepare data. Then train data, i dont use auto settings. And when i click train data it returns this error

### ✔️ Expected Behavior

I think it should work fine because i followed the instructions of Jarod Mica on youtube, installation instructions

### ❌ Actual Behavior

Traceback (most recent call last):
  File "C:\F5-TTS\src\f5_tts\train\finetune_cli.py", line 174, in <module>
    main()
  File "C:\F5-TTS\src\f5_tts\train\finetune_cli.py", line 167, in main
    trainer.train(
  File "C:\F5-TTS\src\f5_tts\model\trainer.py", line 257, in train
    start_step = self.load_checkpoint()
  File "C:\F5-TTS\src\f5_tts\model\trainer.py", line 172, in load_checkpoint
    self.ema_model.load_state_dict(checkpoint["ema_model_state_dict"])
  File "D:\conda\envs\f5-tts\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for EMA:
        size mismatch for ema_model.transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2546, 512]) from checkpoint, the shape in current model is torch.Size([2565, 512]).
Traceback (most recent call last):
  File "D:\conda\envs\f5-tts\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\conda\envs\f5-tts\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\conda\envs\f5-tts\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\conda\envs\f5-tts\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\conda\envs\f5-tts\lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "D:\conda\envs\f5-tts\lib\site-packages\accelerate\commands\launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\conda\\envs\\f5-tts\\python.exe', 'src/f5_tts/train/finetune_cli.py', '--exp_name', 'F5TTS_Base', '--learning_rate', '1e-05', '--batch_size_per_gpu', '1000', '--batch_size_type', 'frame', '--max_samples', '64', '--grad_accumulation_steps', '1', '--max_grad_norm', '1', '--epochs', '100', '--num_warmup_updates', '2', '--save_per_updates', '300', '--last_per_steps', '100', '--dataset_name', 'vivoice', '--finetune', 'True', '--tokenizer', 'char', '--log_samples', 'True', '--logger', 'tensorboard']' returned non-zero exit status 1.

**Comment by HuuHuy227** [comment]
You must extend emb size of pretrained ckpt (Finetune gradio can do it easily). Ensure vocab size equal to emb size of pretrained ckpt

**Comment by ManH170** [comment]
Hmmm as i follow this tutorial on ytb: https://www.youtube.com/watch?v=GmketyZW2c4&t=347s  im doing a brand new model so i dont use a pretrained one. Also please leave contact infoso we can exchange further

**Comment by ManH170** [comment]
hmm i think it is something wrong with the vocab.txt i have extend it with vietnamese missing words but it returns a mismatch here:
size mismatch for ema_model.transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2546, 512]) from checkpoint, the shape in current model is torch.Size([2565, 512]).
as the emelia file is only 2545 vocabs but my finetuned vietnamese voice model vocabs is 2565. Can someone help me with this?

**Comment by HuuHuy227** [comment]
I think your problem came from what you are trying to do here is training from scratch but you are using finetune script. In finetune script it try to load pretrained model weight so this lead to mismatch issue. To overcome this maybe you can try train.py script which using to train from scratch or can modify finetune script not to load pretrained model instead directly training a model with extended emb size equal to your vocab size from scratch.

**Comment by ManH170** [comment]
> I think your problem came from what you are trying to do here is training from scratch but you are using finetune script. In finetune script it try to load pretrained model weight so this lead to mismatch issue. To overcome this maybe you can try train.py script which using to train from scratch or can modify finetune script not to load pretrained model instead directly training a model with extended emb size equal to your vocab size from scratch.

tks haha silly me

**Comment by KaiKenju** [comment]
I'm currently training with my data for about 10 hours on Colab (I don't have strong GPU) with 3k4 steps. However, during the training process, System RAM takes up 90% (11.7/12.7GB) while GPU RAM takes up 50%. Is it true that during the training process, Device is set to = cpu?
