### ISSUE TITLE
Inference broken if prompt is in uppercase. 

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#49]
I'm not sure if this has been mentioned anywhere, but I realized that, if uppercased, the synthesized voice would try (and fail) to spell the words out loud instead of reading them. It would probably be best practice to convert all the prompt to lowercase before inference.

**Comment by jpgallegoar** [comment]
Example: "THIS IS A SIMPLE EXAMPLE": [Audio](https://jumpshare.com/s/jJFbDKG8J6P9H7kn5etO)

**Comment by jpgallegoar** [comment]
Related: If the Reference Text is written in uppercase, the model's quality is severely degraded

**Comment by SWivid** [comment]
Sure, it is exactly the case me met with LibriSpeech test-clean, an evalutaion test set for TTS.
We decide to keep it as someone may have the need for single character spelling. We will add some instruct on it in README.md ad descrpt in gradio interface.
Thanks~

**Comment by NickelKang** [comment]
Hello, I know this is closed.  But I'm curious how can I control this behavior?  In my use case for a voice chatbot with a LLama3.1.  Sometimes the LLM will "LIST TEXT IN ALL CAPS!".  And it sounds crazy.  I could probably filter and clean up the text output before sending to f5-tts for inferencing to prevent this.  But I'm trying to understand what is causing this and how I could tweak it for my use case?   Thanks!

**Comment by jpgallegoar** [comment]
@NickelKang Hey! Well the model was trained in the way that an uppercase text will be spelled out loud. For purely spoken text, you should do a to lowercase function before sending it to F5 (text.lower()).

**Comment by NickelKang** [comment]
@jpgallegoar Thanks for the reply!  That's what I ended up doing more or less.  I created a filter in my python chat script that would detect and correct uppercase sentences, but retain other single-word uppercase acronyms before sending to F5.  It makes sense that you would want some acronyms to be spoken in this way so I get it.  I appreciate it!
