### ISSUE TITLE
Hello, how many languages is native supported?

### ISSUE THREAD

**Issue by Rex-Liu1027** [SWivid/F5-TTS#490]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I can't find a list of natively supported languages, is it convenient for you? Thank you very much!

**Comment by ZhikangNiu** [comment]
Chinese and English

**Comment by SWivid** [comment]
@Rex-Liu1027 Hi, check [here the readme](https://github.com/SWivid/F5-TTS#:~:text=Custom%20model%20inference%20(local%20only)).

will close here, feel free to open if further questions

**Comment by Rex-Liu1027** [comment]
> @Rex-Liu1027 Hi, check [here the readme](https://github.com/SWivid/F5-TTS#:~:text=Custom%20model%20inference%20(local%20only)).
> 
> will close here, feel free to open if further questions

got it，thanks
