### ISSUE TITLE
long text generate bad result

### ISSUE THREAD

**Issue by wwbnjsace** [SWivid/F5-TTS#492]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

in my ubuntu cuda 4090 environment ,when i use a short gen_text , it generate a good result ;but when i use a long text ,>10 words ,it generate a very bad result ,why?the paper say long text also can generate a good result.

**Comment by SWivid** [comment]
Hi @wwbnjsace , maybe it suits for a help wanted issue template?
need more info to figure out~

will close here, feel free to open with a help wanted template and provide more info with actual problem (e.g. the prompt text and audio, used gen_text prompt etc.)
