### ISSUE TITLE
I there a way to change the langage ?

### ISSUE THREAD

**Issue by ksorah1** [SWivid/F5-TTS#495]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Hello,

I need it in french but I don't find the information.

**Comment by SWivid** [comment]
make sure you have read the readme as you have check on 
>I have thoroughly reviewed the project documentation and read the related paper(s).

https://github.com/SWivid/F5-TTS#:~:text=Custom%20model%20inference%20(local%20only)

**Comment by ksorah1** [comment]
Thanks for the link, that's was because the readme is bad, I didn't find "langage" into it.
