### ISSUE TITLE
Script generates single segement_0.wav file

### ISSUE THREAD

**Issue by Maxamed** [SWivid/F5-TTS#498]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Environment Details:
- OS: Debian GNU/Linux 11 (bullseye)
- Python: 3.10.15
- Torch: 2.3.0+cu118
- Gradio: 4.44.1

### Steps to Reproduce

Created a new conda environment.
Cloned the repository and installed as pip package.
Ran the command:  f5-tts_finetune-gradio --port 7860 --host 0.0.0.0
Loaded the project data with Arabic WAV files (100+ hours of audio).
Launched the transcription process through the GUI using the "Transcribe Data" tab.

### ✔️ Expected Behavior

I expected the script to segment the audio files into multiple smaller WAV files (e.g., segment_0.wav, segment_1.wav, etc.), process them continuously, and create a metadata file.
I verified the dataset folder contains WAV files with durations ranging from 30 minutes to several hours.
The issue persists with different projects (e.g., arabic_pinyin vs. ar_custom).
Renamed files to remove special characters, e.g., dots in filenames.
Tested with "Custom" tokenizer type for Arabic language.

### ❌ Actual Behavior

after waiting for over 20 mins only single segement_0.wav file is created and i got this message: [transcribe complete samples : 0
path : /home/jama/F5-TTS/src/f5_tts/../../data/arabic_pinyin/wavs
error files : 86284]

<img width="1487" alt="Screenshot 2024-11-20 at 14 31 20" src="https://github.com/user-attachments/assets/55b165a0-5758-4eec-bc88-5a4f829b96bc">

**Comment by SWivid** [comment]
not support VAD and ASR for long samples yet i thought, maybe write some scripts to leverage e.g. whisper to do vad and asr segmentation first

**Comment by Maxamed** [comment]
Thank you for getting back to me, what’s the maximum length it supports ?

**Comment by SWivid** [comment]
https://github.com/SWivid/F5-TTS/blob/ab2ad3b005ea839ab698493a819bde909761d96e/src/f5_tts/train/finetune_gradio.py#L803-L811

you could modify here but may not get segmented and separately saved samples, it will just leave the original audios

**Comment by Maxamed** [comment]
So what is your advise for the audio file length for training? What length
should be each audio file so it will be segmented ?

**Comment by Maxamed** [comment]
So to fine tune a new language, what’s the ideal length of the audio files?

I have 100 hours of Arabic audio in 50 files — how many minutes should be
each file to start training?

**Comment by Maxamed** [comment]
My friend I haven’t reached the training section yet I’m still in the
transcribe section in the gradio fine tune script.

The script is not generating the segments files and I’m trying to fix that
issue — not sure why it is not generating the segments as in my ticket
included

I thought you said in your earlier comment the reason was the audio file
size so if that’s the issue I was asking what would be the ideal file size

If that’s not the issue can you please advise me why it is not generating
the segments?

Thank you very much

**Comment by SWivid** [comment]
you need some background info about vad and asr, which are tools for your need

> up to your gpu mem

the longer segments you have, the more gpu mem you'll need in general

**Comment by Maxamed** [comment]
The VM has 4 GPU and plenty of memory but it’s still not generating the
segments

Did you had a chance to look at the information in my ticket? I just don’t
know where is the problem?

1. Is the problem the number of the files ? I’m using 100 files
2. Is the problem the size of each file?
3. Is the problem the length of the audio files i.e. 60 minutes+


I’m just trying to find out why the transcription and slicing runs for 20
mins but only outputs one single segment_O.was file and then throws the
error I put in the ticket above

Please can you advise ?

**Comment by SWivid** [comment]
thought i've already answered all your questions
your 60 minutes+ audio exceed the threshold of setting here, and we are not offering vad + asr feature currently in this repo (make sure you know what i am saying: VAD and ASR)

**Comment by Maxamed** [comment]
For future users that might have same problem : always install FFMPEG
Please add that requirement to the readme file

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
