### ISSUE TITLE
The first character in the prompt is not properly read out loud.

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#50]
I realized that all synthesized audios started off broken because the first character isn't being read out properly, making the first word gibberish and making the model mess up. This can be fixed by inserting a blank character (space) as the first character in the prompt, and audios start off much cleaner.

**Comment by jpgallegoar** [comment]
Example: "inference-time compute is the key to success": [Audio](https://jumpshare.com/s/F8rRWR3EYvn0SBmDTNrW)
" inference-time compute is the key to success": [Audio](https://jumpshare.com/s/V0b3VIbpAeL2K0cOtVBA)

**Comment by SWivid** [comment]
Sure, we'll fix it. Probably for missing end punctuation in ref_text.
If there exists a end punc, a blank will be automatically added in between
