### ISSUE TITLE
how to generate  multistype audio？

### ISSUE THREAD

**Issue by wwbnjsace** [SWivid/F5-TTS#502]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

i look the demo，i want to know how to generate multistype audio , and i look the infer_gudio.py , but it too complex , can you tell how to generate multi stype audios ?

**Comment by ZhikangNiu** [comment]
Thank you for your question! Could you clarify what you mean by 'multi-stype audio' and I think the gradio is the simplest way for you(If you're not a programmer

**Comment by wwbnjsace** [comment]
int the demo  [https://modelscope.cn/studios/modelscope/E2-F5-TTS](url) we can see Multiple Speech-Type Generation
![502](https://github.com/user-attachments/assets/a0bddbb9-3992-41b7-ac16-e6e125d10f4b)
we can add different speech type for example sad, angry, so we can generate multiple speech type audio ,the input text can be "{Regular} Hello, I'd like to order a sandwich please. {Surprised} What do you mean you're out of bread? {Sad} I really wanted a sandwich " ,thus the final audio will be added different emotion

**Comment by SWivid** [comment]
Yes that's it.
Each row for a style: the style name, the correspoinding reference audio for the style, (reference text is optional, refer to the transcription of ref_audio)

Have fun~

**Comment by DomoMKT** [comment]
you're looking for a way to generate multiple types of audio? i've got just the thing: [www.nemesyslabs.com](https://www.nemesyslabs.com) is where you can convert your text into high-quality speech with extremely low latency, no accounts needed!
