### ISSUE TITLE
Change download folder when generating audio in f5-tts_infer-gradio

### ISSUE THREAD

**Issue by AlpacaManAlpha** [SWivid/F5-TTS#506]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I want to change the export path, preferably for f5-tts_infer-gradio and f5-tts_finetune-gradio at the same time.

**Comment by SWivid** [comment]
will close here since `enhancement` or `help wanted` template better suit
