### ISSUE TITLE
Tensorboard, where is f5 saving logs I can use?

### ISSUE THREAD

**Issue by AlpacaManAlpha** [SWivid/F5-TTS#508]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Where is f5 keeping logs?

**Comment by SWivid** [comment]
it suits better a `help wanted` template

https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/train/train.py
https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/model/trainer.py
