### ISSUE TITLE
How to configure GPU use in Docker pulled from ghcr.io?

### ISSUE THREAD

**Issue by eglische** [SWivid/F5-TTS#514]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

I'm using the docker image f5-tts:main, the debug information in the gradio shows me correctly my gpu details.

In the inference, it does only do it with cpu and i can't find the option to either start it with gpu support (or deepseed if that is a thing here too)

i could only find multi-gpu flag for the training, and the `f5-tts_infer-gradio --help` command does not show me any options for this.
before i search further in the py files to find a way to do it, i wanted to ask: maybe i overlooked something?

apologies if i miss something obvious, i'm not the most versed when it comes to tts :-)

thank you
-yeti

### Steps to Reproduce

-loaded the docker image as per command
-started up said image with the -h 0.0.0.0 as host id (not documented)
-started gradio via the command in the instruction

### ✔️ Expected Behavior

-use of cuda gpu geforce4060

### ❌ Actual Behavior

-uses cpu only

**Comment by SWivid** [comment]
Hi @eglische , need to install a gpu version torch as readme put
```
# Install pytorch with your CUDA version, e.g.
pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
```
or any other version up to your need (e.g. 2.4.0+cu121

**Comment by eglische** [comment]
thank you for your reply

that will case in this constellation and in my case an error because of the incompatibility of TorchVision and PyTorch. Specifically, torch.library.register_fake

the fix was to install the correct version of torchvision, after uninstalling the incompatible one

`pip uninstall torchvision -y`

`pip install torchvision==0.16.0+cu121 --index-url https://download.pytorch.org/whl/cu121`

It seams to work now and is much faster :>

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions~
