### ISSUE TITLE
Protobuf downgrade required

### ISSUE THREAD

**Issue by WillRegister** [SWivid/F5-TTS#515]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Pop_OS! Deb. 22.04, CUDA 12.6, RTX 3040, Conda python 3.10, Jupyter Notebook VS Code. 

### Steps to Reproduce

Everything as instructed for cloning editable repo. and running the CLI inference, including 15 second wav refrence audio with accurate transcript.

### ✔️ Expected Behavior

Get tests/infer_cli_out.wav of voice

### ❌ Actual Behavior

First protobu and several package dependency mismatch with it. 
-Downgraded to protobuf==3.19.6

Then export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (As instructed, after several tries to find the right version) and got this 
____
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googleapis-common-protos 1.66.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.20.2, but you have protobuf 3.19.6 which is incompatible.
____

So I tried googleapis-common-protos-1.56.0 and then found the needed version 1.56.2

Not sure if anyone else needs help, and don't know where to goto ... post this... so here you go.

**Comment by SWivid** [comment]
```
### Installation
# Create a python 3.10 conda env (you could also use virtualenv)
conda create -n f5-tts python=3.10
conda activate f5-tts
```

might help

**Comment by ZhikangNiu** [comment]
Will close this issue, feel free to ask question.

**Comment by Vektor369** [comment]
Didn't work for me. I'm still getting "ImportError: cannot import name 'builder' from 'google.protobuf.internal'".
I did the following:
```
pip install protobuf==3.19.6
pip install googleapis-common-protos==1.56.0
```
