### ISSUE TITLE
Fine tuning on 24 Hours of Tamil Dataset

### ISSUE THREAD

**Issue by sam4muzix** [SWivid/F5-TTS#522]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I have attempted test training on Tamil dataset with some own patches with 24gb VRAM, 8192 Cuda Cores. 
And yes. it worked good with small amount of training and testing.
But my question and doubt is , 
1. is it ok that a dataset can contain multiple speakers (voices) in dataset ?
bcos getting a single speaker voice data set of 20+ hours is bit tough on my case.
2. Tamil script has 247 characters, 12 vowels, 18 consonants,1 special character. So can i add custom vocabs manually ?
Please help. TIA.

**Comment by ZhikangNiu** [comment]
1. I think you'd better keep one speaker in small dataset
2. if you train from scratch in tamil, you can build your vocab. But if you want to finetune the F5 Base version, it will mismatch in vocab size

**Comment by sam4muzix** [comment]
> 1. I think you'd better keep one speaker in small dataset
> 
> 2. if you train from scratch in tamil, you can build your vocab. But if you want to finetune the F5 Base version, it will mismatch in vocab size

How to train from scratch? Can u please guide ?

**Comment by ZhikangNiu** [comment]
> > 1. I think you'd better keep one speaker in small dataset
> > 2. if you train from scratch in tamil, you can build your vocab. But if you want to finetune the F5 Base version, it will mismatch in vocab size
> 
> How to train from scratch? Can u please guide ?

https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train

**Comment by sam4muzix** [comment]
> > > 1. I think you'd better keep one speaker in small dataset
> 
> > > 2. if you train from scratch in tamil, you can build your vocab. But if you want to finetune the F5 Base version, it will mismatch in vocab size
> 
> > 
> 
> > How to train from scratch? Can u please guide ?
> 
> 
> 
> https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train

Thanks.

**Comment by ZhikangNiu** [comment]
will close this issue and you can reopen this issue if you have question : )
