### ISSUE TITLE
Please i need to adjust speed when using cli

### ISSUE THREAD

**Issue by CGAlei** [SWivid/F5-TTS#523]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Python 3.10

# -------------------------------------------------#

### ✔️ Expected Behavior

is there a way to slow down the tts speed in chinese? when using the cli in python?

### ❌ Actual Behavior

Looking at the code, there are already speed control mechanisms in place. The speed parameter is used in several places. what are the relevant parts and how to adjust the speed:

**Comment by ZhikangNiu** [comment]
https://github.com/SWivid/F5-TTS/blob/c9b4d43a2bf192ed7541cee5b2cdb8e415b8a1b1/src/f5_tts/infer/infer_cli.py#L84-L89

**Comment by SmaugPool** [comment]
See the `--speed` argument:
```
$ f5-tts_infer-cli --help

--speed SPEED         Adjust the speed of the audio generation (default: 1.0)
```

**Comment by CGAlei** [comment]
Thanks mate!

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
