### ISSUE TITLE
How to use the API function

### ISSUE THREAD

**Issue by Jandown** [SWivid/F5-TTS#525]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Thank you to the author, a great project.
I have read the user manual, but it does not cover how to use the API. I hope you can add instructions on how to use the API. Thank you again

**Comment by SWivid** [comment]
this issue better suit for a "help wanted" template, will close here~
