### ISSUE TITLE
Suggestion to open discussions / poll for new language integration

### ISSUE THREAD

**Issue by nitefood** [SWivid/F5-TTS#53]
Hey @SWivid,

first of all, thanks for publicly releasing such a groundbreaking tool, F5-TTS is nothing short of incredible!

I've seen many closed issues where people is asking about new languages. From what I could gather, you [seem](https://github.com/SWivid/F5-TTS/issues/40#issuecomment-2409027035) [open ](https://github.com/SWivid/F5-TTS/issues/12#issuecomment-2407362300) to the idea of introducing more languages yourselves.

So I'm here to ask if it's possible to open the GitHub discussions space for this repo. That way you could have a poll there, to take the pulse of the community in regard to which languages are the most sought after - and thus unburdening the issues section from these type of requests (and more to come).

Thanks for the awesome work.

**Comment by SWivid** [comment]
Yes, we have just opened the discussion space ~
