### ISSUE TITLE
English Accents

### ISSUE THREAD

**Issue by trigsoft** [SWivid/F5-TTS#533]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

colab. Install as below:

!pip install -q condacolab
import condacolab
condacolab.install()

!conda create -n f5-tts python=3.10
!conda init bash
!conda activate f5-tts
!pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
!pip install git+https://github.com/SWivid/F5-TTS.git

### Steps to Reproduce

The enviroment was installed as above. 

Run it in the command line but the english accent is not correct. 

Is it possible for you to provide an email so that I can send the command line and audio file?

**Comment by SWivid** [comment]
Compressing to a zip file is fine for the uploading op with GitHub~

**Comment by trigsoft** [comment]
> Compressing to a zip file is fine for the uploading op with GitHub~

The reason is I don't want to share with other people. Can you do me the favor please?

**Comment by SWivid** [comment]
@trigsoft you can find my email in our paper, the first one
and you could elaborate more on the problem, e.g. what accent you want or you don't want

**Comment by trigsoft** [comment]
@SWivid Mail sent with the same title here.

**Comment by SWivid** [comment]
#542 report similar issue, we will try to figure out

**Comment by trigsoft** [comment]
> #542 report similar issue, we will try to figure out

Thanks.
