### ISSUE TITLE
The different of prepare_emilia.py and prepare_csv_wavs.py

### ISSUE THREAD

**Issue by CreepJoye** [SWivid/F5-TTS#537]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

python==3.10

### Steps to Reproduce

question

### ✔️ Expected Behavior

i follow the instruction of https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train.
firstly run prepare_emilia.py to preprocess my dataset(ESD data), and then i get a folder ESD_ZH_EN_pinyin with 3 files.
then i run python scripts/prepare_csv_wavs.py <path_to_your_dataset> <F5-TTS_repo_data_path>/<dataset_name>_pinyin,here i get 3 files in my<dataset_name>_pinyin.
i want to know what's the meaning of prepare_emilia.py if i don't use the files generated by it?

### ❌ Actual Behavior

question

**Comment by SWivid** [comment]
> i want to know what's the meaning of prepare_emilia.py if i don't use the files generated by it?

prepare_emilia.py is to Prepare the Emilia dataset

if using another dataset ESD, there is no need to run the original prepare_emilia.py
