### ISSUE TITLE
 local variable 'bigvgan' referenced before assignment

### ISSUE THREAD

**Issue by thesandi99** [SWivid/F5-TTS#539]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

# Environment Details

```
Python 3.10.12

### Steps to Reproduce

!git clone https://github.com/SWivid/F5-TTS.git
%cd F5-TTS
!pip install -e .
%cd ..
!pip install srt pydub
!pip install pysrt
```
--------------------------------------------------------------------
`!f5-tts_infer-cli -c src/f5_tts/infer/examples/multi/story.toml --vocoder_name "bigvgan" --load_vocoder_from_local --ckpt_file ckpts/F5TTS_Base_bigvgan/model_1250000.pt`
-------------------------------------------------------------------
`!f5-tts_infer-cli -c src/f5_tts/infer/examples/multi/story.toml ` and defualt vocoder is bigvgan

### ✔️ Expected Behavior

vocoder change to "bigvgan" and output ganareted

### ❌ Actual Behavior

`Traceback (most recent call last): File "/usr/local/bin/f5-tts_infer-cli", line 5, in <module> from f5_tts.infer.infer_cli import main File "/content/F5-TTS/src/f5_tts/infer/infer_cli.py", line 130, in <module> vocoder = load_vocoder(vocoder_name=mel_spec_type, is_local=args.load_vocoder_from_local, local_path=vocoder_local_path) File "/content/F5-TTS/src/f5_tts/infer/utils_infer.py", line 126, in load_vocoder vocoder = bigvgan.BigVGAN.from_pretrained(local_path, use_cuda_kernel=False) UnboundLocalError: local variable 'bigvgan' referenced before assignment`

how i deal this

im trying to use bigvgan and its got m this error im dwnload manualy and -c config but still not use

**Comment by SWivid** [comment]
> I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.

please follow the readme

> I have searched for existing issues, including closed ones, and couldn't find a solution.

#513
