### ISSUE TITLE
Can the 150M parameter small model handle multiple languages?

### ISSUE THREAD

**Issue by hamees-sayed** [SWivid/F5-TTS#540]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I am planning to train the 150M parameter small model and would like to know if it can handle multiple languages. Is it feasible to train this model for TTS tasks in two or more languages, or are there any limitations regarding multilingual support with this model size?

If anyone has experience or insights into training this model for multilingual tasks, your input would be greatly appreciated!

Thanks!

**Comment by ZhikangNiu** [comment]
Good question, maybe you can mix wenetspeech4tts premium and LibriTTS to test. The small model can perform well in each of them
