### ISSUE TITLE
Whats wrong with update?

### ISSUE THREAD

**Issue by ThankYouHeart** [SWivid/F5-TTS#542]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

https://huggingface.co/spaces/abidlabs/E2-F5-TTS  - demo that was updated 1 month ago
https://huggingface.co/spaces/mrfakename/E2-F5-TTS - a demo that is updated according to the repository

### Steps to Reproduce

Hi, i tested the demo that was updated 4 hour ago - and the sound is terrible, it looks like a robot voice from ancient TTS, I tested the demo that was updated 1 month ago and it sounds much better. I haven't checked the local version yet, but they answered me through the issue opened in the huggingface that it is updated in accordance with the repository. So i just wanted to clarify if this is a predictable experience?
![Screenshot_225](https://github.com/user-attachments/assets/dc4318ce-b203-4aad-951c-896f7566c483)
 Thanks for the most good clone voice model!

### ✔️ Expected Behavior

This is another demo, i set the same settings and chose the same audio file, the sound is almost perfect - https://voca.ro/1dmEndpE0X2K

### ❌ Actual Behavior

This is what the sound looks like from the demo linked to in this repository -  https://voca.ro/1nYc8QOsGbGE

**Comment by ThankYouHeart** [comment]
Hmm - I reviewed the files - the difference is not so catastrophic in the examples - although the difference is noticeable. Are these different vocoders?

**Comment by ThankYouHeart** [comment]
ok, i don't want to distract you so i'll check the difference between the vocoders locally tomorrow.

**Comment by SWivid** [comment]
We have checked locally the inference with both fp32 and fp16, and it seems all right locally

But the online demo (yes, it's synchronized with GitHub repo) indeed has a problem generating audio
It produces output with low quality every time.

Maybe you could help confirm whether if you could also make it right locally,
or if there is also problem with local inference there.

TIA~

**Comment by ThankYouHeart** [comment]
> We have checked locally the inference with both fp32 and fp16, and it seems all right locally
> 
> But the online demo (yes, it's synchronized with GitHub repo) indeed has a problem generating audio It produces output with low quality every time.
> 
> Maybe you could help confirm whether if you could also make it right locally, or if there is also problem with local inference there.
> 
> TIA~

Yes, the local code works fine, I don't see any such issues there, and by the way, bigvgan turned out to be better than vocos. 😎
