### ISSUE TITLE
issue training F5tts small model after new training code

### ISSUE THREAD

**Issue by danielw97** [SWivid/F5-TTS#545]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

python 3.10.12 (wsl)

### Steps to Reproduce

1. initialize training using the new config-based training code following the readme.
In my case I'm trying to train the f5tts small model and have modified the training config to point to my dataset.
I receive the following error:

```
Error executing job with overrides: []                                                                                  
Traceback (most recent call last):                                                                                      
  File "/home/daniel/F5-TTS/src/f5_tts/train/train.py", line 35, in main                                                
    model = CFM(                                                                                                        
  File "/home/daniel/F5-TTS/src/f5_tts/model/cfm.py", line 55, in __init__                                              
    self.mel_spec = default(mel_spec_module, MelSpec(**mel_spec_kwargs))                                                
TypeError: MelSpec.__init__() got an unexpected keyword argument 'is_local_vocoder'                                     
```
Another issue I'm experiencing when using the new prepare_ljspeech script and trying to train using that dataset with char is the following, let me know if I should use a different tokenizer in this senario though.

```
Traceback (most recent call last):                                                                                      
  File "/home/daniel/F5-TTS/src/f5_tts/train/train.py", line 26, in main                                                
    vocab_char_map, vocab_size = get_tokenizer(tokenizer_path, tokenizer)                                               
  File "/home/daniel/F5-TTS/src/f5_tts/model/utils.py", line 118, in get_tokenizer                                      
    assert vocab_char_map[" "] == 0, "make sure space is of idx 0 in vocab.txt, cuz 0 is used for unknown char"         
AssertionError: make sure space is of idx 0 in vocab.txt, cuz 0 is used for unknown char                                
```

Thanks for all of your work on these models.

### ✔️ Expected Behavior

model training should proceed.

### ❌ Actual Behavior

tracebacks as above, which I assume are related to the new training code.

**Comment by SWivid** [comment]
Hi @danielw97
Thanks for reporting the bug!
Check if it works now

**Comment by SWivid** [comment]
It would be fine with this issue, we will check for the LJSpeech vocab

**Comment by danielw97** [comment]
Thanks, in my tests I'm using ljspeech 1.1
If there's any more info you need, let me know.

**Comment by SWivid** [comment]
Hi @danielw97 
the second one is because the ljspeech has /n at end, which is not expected to include in the vocab
fixed with adding strip() during processing

**Comment by danielw97** [comment]
Thanks for the quick resolution, and explanation of my second issue.
