### ISSUE TITLE
Add functionality to the Transcription section

### ISSUE THREAD

**Issue by nikish3** [SWivid/F5-TTS#546]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

I can't upload a large volume of audio files in the "Transcription data" section to create a dataset through the audio file upload window, everything freezes. My file size is 20 GB

### 2. What is your suggested solution?

Can you add a window in "Gradio" in the "Transcription data" section where I can specify the path to the folder where the audio files are located, this will eliminate the freeze and make it possible to upload a large volume of files to create a dataset.

Thank you

### 4. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by danielw97** [comment]
I don't have the interface in front of me at the moment, but there is an audio from path checkbox in the gradio training interface if memory serves.
You can then place your files into the dataset subdirectory of your dataset.
i.e. if your dataset is called voice1, the directory would be voice1/dataset
Hope this helps a bit.

**Comment by nikish3** [comment]
Thank
