### ISSUE TITLE
Providing a reference audio longer than 20 seconds produces truncated output.

### ISSUE THREAD

**Issue by chigkim** [SWivid/F5-TTS#55]
First of all, great model!
If I provide a reference audio that's about 10-15 seconds long, it produces decent output.
I was hoping that providing longer audio reference would improve the output quality. However, if I provide a reference audio that's longer than 20 seconds, it produces an output with a lot of words missing from gen_text variable.

**Comment by chigkim** [comment]
I'm using the python script for single inference.

**Comment by AznamirWoW** [comment]
or instead of truncating it may just produce a greatly speed-up read

**Comment by SWivid** [comment]
Yes, indeed. As the model is trained with infilling task, which is masking out some part and letting model restore.
Currently support a total length of 30s (reference + to_generate), cuz the longest sampled met in training is 30s.

**Comment by chigkim** [comment]
Is this model's architecture limitation, or can you finetune with longer dataset? It would be amazing to be able to keep generating without time limitation. :)

**Comment by chigkim** [comment]
Thanks for pointing out the batch inference in Gradio app.
Also thanks for accepting #67 for CLI, modified from Gradio app.
