### ISSUE TITLE
polyphonetic characters pronounce wrong in Chinese 

### ISSUE THREAD

**Issue by teoking** [SWivid/F5-TTS#551]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

with the sentence "村民们各个神情专注地倾听",   the '地' pronounces 'di4' while 'de4' is correct
with the sentence "一个衣着简朴的讲述者正在中央", the '朴' prounouces 'piao2' while 'pu3' is correct

So is this a Chinese-to-Pinyin problem? how can I fix it ? e.g. replacing with another chinese-to-pinyin library or having a chance to correct the pinyin in inference

I did some researching with the paper but found no clues.

**Comment by teoking** [comment]
It seems pinyin converting issues in python-pinyin:
```python
from pypinyin import pinyin, lazy_pinyin, Style

strs = ['专注地倾听', '衣着简朴的讲述者']

for s in strs:
  result = pinyin(s, style=Style.TONE3, heteronym=True)
  print(s, result)
```
```
Output:
专注地倾听 [['zhuan1'], ['zhu4', 'zhou4'], ['di4', 'de'], ['qing1'], ['ting1', 'yin3', 'yi2']]
衣着简朴的讲述者 [['yi1'], ['zhuo2'], ['jian3'], ['piao2'], ['de', 'di1', 'di2', 'di4'], ['jiang3'], ['shu4'], ['zhe3']]
```

**Comment by ZhikangNiu** [comment]
@teoking please check this issue：https://github.com/mozillazg/python-pinyin/issues/249

**Comment by ZhikangNiu** [comment]
BTW, you can also try https://github.com/GitYCC/g2pW
