### ISSUE TITLE
EMA True ignores letters other than English letters.

### ISSUE THREAD

**Issue by Alykasym** [SWivid/F5-TTS#554]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows, RTX3070, Python 3.10, torch==2.3.0, cuda 11.8

### Steps to Reproduce

1. Clone the rep, and prepare env as in documentation.
2. Finetune a non-English model using gradle webui - `f5-tts_finetune-gradio`
3. In the finetune webui, in Test Model tab, check "Use EMA".
4. Select the latest or saved update of your non-English model.
5. Add reference audio and text that has letters that doesn't exist in English.
6. Click Infer button

### ✔️ Expected Behavior

Expecting the model to generate audio speaking non-english letters while EMA is turned on.

### ❌ Actual Behavior

The model skips non-english letters and generates without saying it.

For example, the words like "Ştraüs" is being transcribed as "tras".

When I turn off EMA, then it doesn't ignore and describes well. The issue happens only when I turn on EMA.
What might be the issue? Does EMA ignore the vocab?

**Comment by SWivid** [comment]
it is mainly because the finetuning process just goes few steps, ema weights still dominated by previous pretrained weight
if you just train few steps, turn ema off; if trained longer, could try with it
