### ISSUE TITLE
Multi Gen_text create at same time [Challenges and Attempts at Batch Generation]

### ISSUE THREAD

**Issue by thesandi99** [SWivid/F5-TTS#558]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

I tried modifying and testing every possible variation, but I can only generate 2 or 3 batches simultaneously. Here's what I attempted:

1.     I added logic to calculate the total batches using `i == nth batch number` and tried generating those batches concurrently, but it didn't work as expected.
2.     I incorporated Python multiprocessing with `workers=2`, but the results were not satisfactory.
3.     I also experimented `with concurrent.futures.ThreadPoolExecutor(max_workers=5) `but didn't achieve the desired outcome.

### 2. What is your suggested solution?

I’m not entirely sure how to approach this, but here’s my suggestion: `Instead of generating just 2 or 3 batches at a time, create containers. For example, design containers based on the total number of batches, where each container is responsible for generating a specific set of batches. Then, run these containers concurrently, leveraging CUDA cores for parallel execution. This might work, though I’m not certain`

### 3. Additional context or comments

It seems like the current attempts are limited by resource allocation or the way tasks are being distributed. It might help to rethink the approach entirely, focusing on GPU parallelism (if CUDA is available) or using a framework like Ray or Dask for optimized task distribution.

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by SWivid** [comment]
if you mean batch on single gpu, has already supported, by need to turn on the mask (for both transformer and convnext), and will probably has no speed up
we would recommand to use the current mode, or you could try tensorrt and stuff; welcome pr

if multi-gpu, you may refer to the script under eval/ directory

**Comment by thesandi99** [comment]
I mens when I'm config .toml file so it ganarate one by one ex. gen_text 0 it's ganarate then 2nd like this I mens if it's ganarate in multiple batches like ganarate 2 or 3 batches at same time batches mens gen_text 0 it's like confusing but in simpal : I mens ganarate multiple audio at same time

**Comment by SWivid** [comment]
emmm, not quite understood

my previous response has just mentioned two ways of generating batches at same time [single gpu] / [multi gpu]

**Comment by thesandi99** [comment]
Aaaa.. my english is pretty weak I also use gpt to ganarate hindi to english exit (1)

How it's possible to ganarate multiple audio at same time ?

**Comment by SWivid** [comment]
it's fine lol~

in eval we leverage accelerate to do so (multi-gpu parallel)
https://github.com/SWivid/F5-TTS/blob/c38dc25324c7f0cc07bffc51527def1c28a21173/src/f5_tts/eval/eval_infer_batch.py#L167

if single gpu, will need to turn on transformer mask and also mask for convolutional layers (so probably no speed up)
https://github.com/SWivid/F5-TTS/blob/c38dc25324c7f0cc07bffc51527def1c28a21173/src/f5_tts/model/cfm.py#L84-L88
you can see there is `b`, which is currently 1 (recommanded)
and you will need to turn on mask for `self.transformer` and also for `convnextv2` blocks

**Comment by thesandi99** [comment]
im quite counfusing the multiple batche create i mens createting a multiple ganarte audios at same time then how i use .toml to ganarate the multi chucks ?
1. im use ```
# Multi voice. See src/f5_tts/infer/README.md
f5-tts_infer-cli -c src/f5_tts/infer/examples/multi/story.toml
```
then its like garate one by one audio file ok 

but you refer me to use src/eval but in eval is not option to -c config toml file

**Comment by SWivid** [comment]
because it is of different usage, and will need a certain coding to realize what you want. 
current repo has not such function yet.

i mean, you can follow the way in eval (leverage accelerator.split_between_processes) and write some code to distribute the chunked text for each different gpu to do inference in parallel.

after these things (a certain coding), you could realize the thing you want (and the prerequisite is that you have multi gpu)

**Comment by SWivid** [comment]
yes just the way i have mentioned (and you need several gpu, it is the prerequisite)

**Comment by thesandi99** [comment]
undstood!! 

Done! what if I create this feature 

![images](https://github.com/user-attachments/assets/c4986ca6-9b9c-4f74-a231-2ed7bd236610)


:]

**Comment by SWivid** [comment]
![image](https://github.com/user-attachments/assets/141f40e7-6a39-4099-b94c-4f20675db0c7)
yeah it would be good, 
but probably the way of semi-streaming (i mean not truly streaming, but output a chunk when finished while continuing next chunk would be more useful in real world case, refer to #544 )

**Comment by thesandi99** [comment]
yes ! but its benifical who have ganarate multi more than 100 500 of voice (me) is not like want every one but say its improving f5-tts and i dont know why but im curus to result to ganarting 100 audio at same time is make me smile 

![uta](https://github.com/user-attachments/assets/ade7a612-be88-460a-8d36-e715f27dd2b4)

**Comment by thesandi99** [comment]
```
if gen_file and "voices" in config:
     with codecs.open(gen_file, "r", "utf-8") as f:
        gen_text = f.read()
    total_gen_text = {}
    for voice in config["voices"]:
        total_gen_text[voice] = ""
    reg1 = r"(?=\[\w+\])"
    chunks = re.split(reg1, gen_text)
    reg2 = r"\[(\w+)\]"
    for text in chunks:
        if not text.strip():
            continue
        match = re.match(reg2, text)
        if match:
            voice = match[1]
        else:
            voice = "main"
        if voice not in total_gen_text:
            voice = "main"
        text = re.sub(reg2, "", text)
        total_gen_text[voice] += text.strip() + " "
    for voice in total_gen_text:
        total_gen_text[voice] = total_gen_text[voice].strip()
    main_voice = {"ref_audio": ref_audio, "ref_text": ref_text}
    if "voices" not in config:
        voices = {"main": main_voice}
    else:
        voices = config["voices"]
        voices["main"] = main_voice
    for voice in voices:
        voices[voice]["ref_audio"], voices[voice]["ref_text"] = (
            preprocess_ref_audio_text(
                voices[voice]["ref_audio"], voices[voice]["ref_text"]
            )
        )
        print("Voice:", voice)
        print("Ref_audio:", voices[voice]["ref_audio"])
        print("Ref_text:", voices[voice]["ref_text"])

    generated_audio_segments = []
    for voice in total_gen_text:
        ref_audio = voices[voice]["ref_audio"]
        ref_text = voices[voice]["ref_text"]
        print(f"Voice: {voice}")
        audio, final_sample_rate, spectragram = infer_process(
            ref_audio,
            ref_text,
            total_gen_text[voice],
            model_obj,
            vocoder,
            mel_spec_type=mel_spec_type,
            speed=speed,
        )
        generated_audio_segments.append(audio)
```

ok so im add this logic but in this logic how i call  `total_gen_text `in `infer_process` sending multipul reqest like that

**Comment by lxianl455** [comment]
> 如果你指的是单个 gpu 上的批处理，已经支持，需要打开 mask（对于 transformer 和 convnext），并且可能不会加速， 我们建议使用当前模式，或者你可以尝试 tensorrt 和其他东西；欢迎 pr
> 
> 如果是多 GPU，可以参考 eval/ 目录下的脚本

Any Example? I did not see any script for the "mask".

**Comment by lxianl455** [comment]
> turn on mask for `self.transformer` and also for `convnextv2` blocks

What Means " turn on mask for self.transformer and also for convnextv2 blocks ".

**Comment by 912602337** [comment]
> it's fine lol~
> 
> in eval we leverage accelerate to do so (multi-gpu parallel)
> 
> [F5-TTS/src/f5_tts/eval/eval_infer_batch.py](https://github.com/SWivid/F5-TTS/blob/c38dc25324c7f0cc07bffc51527def1c28a21173/src/f5_tts/eval/eval_infer_batch.py#L167)
> 
> Line 167 in [c38dc25](/SWivid/F5-TTS/commit/c38dc25324c7f0cc07bffc51527def1c28a21173)
> 
>  with accelerator.split_between_processes(prompts_all) as prompts: 
> if single gpu, will need to turn on transformer mask and also mask for convolutional layers (so probably no speed up)
> 
> [F5-TTS/src/f5_tts/model/cfm.py](https://github.com/SWivid/F5-TTS/blob/c38dc25324c7f0cc07bffc51527def1c28a21173/src/f5_tts/model/cfm.py#L84-L88)
> 
> Lines 84 to 88 in [c38dc25](/SWivid/F5-TTS/commit/c38dc25324c7f0cc07bffc51527def1c28a21173)
> 
>  cond: float["b n d"] | float["b nw"],  # noqa: F722 
>  text: int["b nt"] | list[str],  # noqa: F722 
>  duration: int | int["b"],  # noqa: F821 
>  *, 
>  lens: int["b"] | None = None,  # noqa: F821 
> 
> you can see there is `b` (batch), which is currently 1 (recommanded)
> and you will need to turn on mask for `self.transformer` and also for `convnextv2` blocks

 if single gpu, will need to turn on transformer mask and also mask for convolutional layers (so probably no speed up),Do you have a demo？

**Comment by 912602337** [comment]
> it's fine lol~
> 
> in eval we leverage accelerate to do so (multi-gpu parallel)
> 
> [F5-TTS/src/f5_tts/eval/eval_infer_batch.py](https://github.com/SWivid/F5-TTS/blob/c38dc25324c7f0cc07bffc51527def1c28a21173/src/f5_tts/eval/eval_infer_batch.py#L167)
> 
> Line 167 in [c38dc25](/SWivid/F5-TTS/commit/c38dc25324c7f0cc07bffc51527def1c28a21173)
> 
>  with accelerator.split_between_processes(prompts_all) as prompts: 
> if single gpu, will need to turn on transformer mask and also mask for convolutional layers (so probably no speed up)
> 
> [F5-TTS/src/f5_tts/model/cfm.py](https://github.com/SWivid/F5-TTS/blob/c38dc25324c7f0cc07bffc51527def1c28a21173/src/f5_tts/model/cfm.py#L84-L88)
> 
> Lines 84 to 88 in [c38dc25](/SWivid/F5-TTS/commit/c38dc25324c7f0cc07bffc51527def1c28a21173)
> 
>  cond: float["b n d"] | float["b nw"],  # noqa: F722 
>  text: int["b nt"] | list[str],  # noqa: F722 
>  duration: int | int["b"],  # noqa: F821 
>  *, 
>  lens: int["b"] | None = None,  # noqa: F821 
> 
> you can see there is `b` (batch), which is currently 1 (recommanded)
> and you will need to turn on mask for `self.transformer` and also for `convnextv2` blocks

if single gpu, will need to turn on transformer mask and also mask for convolutional layers (so probably no speed up),Do you have a demo？
