### ISSUE TITLE
first time using f5, it wouldn't generate the audio at all

### ISSUE THREAD

**Issue by helprequiredthanks** [SWivid/F5-TTS#559]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

windows 10, 64 bit, most recent Python, downloaded miniconda as instructed
ALSO importantly the app wouldn't work at all until I further downloaded ffmpeg-7.1-full_build, from gyan, and then added the bin folder to PATH as ChatGpt advised me to when I consulted it on the error message showing on prompt
Now I have already downloaded the ffmpeg, the "actual behavior" happened well after this

### Steps to Reproduce

Sorry I have no experience in tech, I'm just trying to create audiobooks.

Installation I did as specified by 

# Create a python 3.10 conda env (you could also use virtualenv)
conda create -n f5-tts python=3.10
conda activate f5-tts
# Install pytorch with your CUDA version, e.g.
pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

Then within a folder in my C file I opened command and did as specified by

git clone https://github.com/SWivid/F5-TTS.git
cd F5-TTS
pip install -e .

Then I used the line specified for launching the app
f5-tts_infer-gradio

Then I opened http://127.0.0.1:7860/

Then I uploaded a brief audio clip
and put in a brief text passage. See actual behavior pictures.

### ✔️ Expected Behavior

It was a brief audio reference, and a brief text passage, couldn't be simpler.

### ❌ Actual Behavior

It just won't generate the audio result. Also, when "generating", the computer case started getting very loud - only getting quiet when I terminated the program.

![Screenshot (14)](https://github.com/user-attachments/assets/3e5c943c-801a-4521-88b2-402e2fcda5f2)
![Screenshot (15)](https://github.com/user-attachments/assets/5f4c3573-e772-43b2-8041-999aabfcb14c)
![Screenshot (16)](https://github.com/user-attachments/assets/aafd9de6-64bd-4ab9-bc46-cdd5b458c19d)

**Comment by SWivid** [comment]
there are two possible reasons:
1. check if you have used gpu to do inference
2. make sure not to click on the cmd inferface, otherwise there could be unintentionally pause command passed in

commonly, after getting to the phase you have got to, there is nothing blocking the inference process
also, if you succeed in generating samples but receive no intelligible output, consider upgrading torch to 2.4.0+cu121 or to order the dtype in infer_utils.py as fp32 (make it fixed)

thanks for providing detailed info, hope would help

**Comment by helprequiredthanks** [comment]
Thanks. Could my internet connection be at fault somehow? I just tried a similar thing in literally the online try section https://f5tts.org/playground

And 200 seconds later, nothing

That was bizarre

![Screenshot_20241201-145916_Chrome](https://github.com/user-attachments/assets/0bbe5421-888a-4e3c-8c1a-051227cfd808)

**Comment by SWivid** [comment]
this is an unofficial fake website, has no relationship with us!

you can just follow the readme we have provide, where there **are** online demos!
![1733036866552](https://github.com/user-attachments/assets/d3867a74-657b-4bcb-bff2-f147ad134e78)

**Comment by helprequiredthanks** [comment]
> this is an unofficial fake website, has no relationship with us!
> 
> you can just follow the readme we have provide, where there **are** online demos! ![1733036866552](https://private-user-images.githubusercontent.com/45333109/391312068-d3867a74-657b-4bcb-bff2-f147ad134e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjY3OTUsIm5iZiI6MTczMzA2NjQ5NSwicGF0aCI6Ii80NTMzMzEwOS8zOTEzMTIwNjgtZDM4NjdhNzQtNjU3Yi00YmNiLWJmZjItZjE0N2FkMTM0ZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE1MjEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOWM4NWY3ZDdlZmMwN2U0N2U4NGIwYzkwMjE3N2ZjNTg5MDRmZDQzMzE4OWNiNDM0MmY0MzQ2ZDRiMGE4MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LHpYXmbtb0Y7MzLqzgzxzwSGQT6TqnoXWHvi6Yv7aG4)

Thank you, you are right, the official demos from your website are the correct ones.
I'll maybe try Pinokio later, seems much easier platform to use apps on. Thanks for replying to my queries.

**Comment by SWivid** [comment]
glad could help

will close this issue, feel free to open if further questions~
