### ISSUE TITLE
How to train a 48khz model

### ISSUE THREAD

**Issue by ILG2021** [SWivid/F5-TTS#560]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

The default output sample rate is 24k, which is too low quality, I want to train a 48k model, anyone can gives a guide?

**Comment by SWivid** [comment]
1. use 48khz dataset
2. set the target_sample_rate to 48khz
3. use trained 48khz model and a 48khz vocoder
