### ISSUE TITLE
The output content may be mixed with other content

### ISSUE THREAD

**Issue by zyq-zzz** [SWivid/F5-TTS#562]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

This model has failed to generate speech according to Text to Generate multiple times, and it will automatically add some other content. What is the reason for this and is there any solution

**Comment by hequnbai** [comment]
I have the same issue. I use mandarin, sometimes it generates unexpected replica of some words, sometimes skips a few ones. Not very stable. I also finetuned using private dataset, the timbre and prosody and speaking style get really close to the training and reference set, but still the error remains, and becomes even worse. 

Anyone has a clue of the issue and give some solutions ? ...
