### ISSUE TITLE
Bad synthesis results when reading phone numbers（读取电话号码时合成结果不佳）

### ISSUE THREAD

**Issue by WGS-note** [SWivid/F5-TTS#563]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

torch                         2.3.0
torchaudio                    2.3.0

### Steps to Reproduce

When there is a phone number in `gen_text`, there is an undesirable pause in the synthesized result, hopefully the phone number should be concatenated.

当 `gen_text` 中有电话号码的时候，合成结果中会出现不应该有的停顿，希望的是电话号码应该是连起来读的

```shell
! python inference-cli.py \
--model "F5-TTS" \
--ref_audio "tests/lyn-f5tts_test.wav" \
--ref_text "那到时候再给你打电话，麻烦你注意接听" \
--gen_text "你好，我这边是XXX的工作人员，请问你的号码是幺幺幺八八八七三三七七吗？" \
--ckpt_file "/home/repository/audio/F5TTS_Base/model_1200000.safetensors" \
--output_dir "tests/lyn_out.wav"
```

### ✔️ Expected Behavior

Smooth reading of phone numbers

流畅的读电话号码

### ❌ Actual Behavior

Phone numbers are not synthesized well and there are unwanted pauses

电话号码合成效果不好，会出现不应该有的停顿

**Comment by SWivid** [comment]
Yes, the problem exists. finetuning will help or train with more phone number reading data
the model still lacks these practices.

是的，电话号码模型还不太6，需要在相关数据上再训下微调啥的
