### ISSUE TITLE
How to make output exactly length as prompt wav lenght?

### ISSUE THREAD

**Issue by MonolithFoundation** [SWivid/F5-TTS#568]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

How to make output exactly length as prompt wav lenght?

In the scenario of wav translation into another language.

**Comment by SWivid** [comment]
https://github.com/SWivid/F5-TTS/blob/eea65de823daa37c9d5b565cc01254d0c94bcc58/src/f5_tts/infer/utils_infer.py#L437-L443
