### ISSUE TITLE
Can reasoning be accelerated?

### ISSUE THREAD

**Issue by WGS-note** [SWivid/F5-TTS#569]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I synthesized the following text:

`这点请您放心，估计是我的号码被标记了，请问您是沈沈吗？`

It takes 3 seconds to reason.

Can millisecond-level reasoning be achieved?

Very much looking forward to hearing back from the author team!

**Comment by SWivid** [comment]
you can do some engineering optimization to boost speed (will surely speed up in magnitude
and welcome pr
