### ISSUE TITLE
Can you specify polyphonic words when you encounter them in your reasoning?

### ISSUE THREAD

**Issue by WGS-note** [SWivid/F5-TTS#572]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

If there is a polyphonic word in the given text, can the pronunciation of this word be fixed while reasoning?

**Comment by SWivid** [comment]
> I have searched for existing issues, including closed ones, no similar questions.

you can refer to previous issue

polyphonic 多音字 etc.
