### ISSUE TITLE
Words control the tone and emotion

### ISSUE THREAD

**Issue by luokeke-web** [SWivid/F5-TTS#575]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

window10
cudnn: 90100
torch: 2.4.1+cu118
cuda: 11.8
gpu:True

### Steps to Reproduce

The project is running without any issues.

### ✔️ Expected Behavior

I want to mark the emotional tone control words in the text so that they can control the tone and emotion without being read aloud directly.

### ❌ Actual Behavior

How can I mark the emotional tone words in the text? I find that I can't control its tone with these words, and they get read out directly.

**Comment by SWivid** [comment]
hi @luokeke-web 
each tag need to with a prompt audio, currently not support emotional tone words as token to control
the tag in {} needs to be place before the sentence you want to make use of the prompt
![image](https://github.com/user-attachments/assets/903aa2a3-7c96-4c39-9eb5-c272823a274c)
