### ISSUE TITLE
Whisper Model

### ISSUE THREAD

**Issue by nikish3** [SWivid/F5-TTS#577]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

Audio file-to-text recognition doesn't work correctly, so the dataset turns out to be of poor quality.Here's an example. 

segment_1038 / kill! kill!
segment_1039|kill, kill!
segment_1040|кааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа
segment_1041 / subtitles were created by dimatorzok
segment_1042|no, no.

although these segments (segment_1040, segment_1041) should have text I checked 
I used to create a dataset for segments and transcription via Whisper Model large-v3, it became much better, there are no errors, and speech recognition improved, as did training.

### 2. What is your suggested solution?

Add Whisper Model large-v3 as a choice or replace it completely. 

### 3. Additional context or comments

Thank you you are the best )))

### 4. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by SWivid** [comment]
many thanks for reporting this~

currently could temporarily replace here
https://github.com/SWivid/F5-TTS/blob/eea65de823daa37c9d5b565cc01254d0c94bcc58/src/f5_tts/infer/utils_infer.py#L146
