### ISSUE TITLE
Audio prompt is repeated at the start

### ISSUE THREAD

**Issue by tammam1998** [SWivid/F5-TTS#58]
Thanks for open sourcing this model, it seems very promising.

The model seems to regenerate the last part of the reference audio at the beginning of the generated audio. It also seems like the last part of the generated audio is always better than the first part. Any ideas why is that, how to fix?

**Comment by SWivid** [comment]
Generally because we just simply estimate the duration rather than a delicate duration predictor.

1. Consider fix duration
3. If long silence at start and end of prompt audio, do a pre-cut would help

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.
