### ISSUE TITLE
Sound model preservation

### ISSUE THREAD

**Issue by land007** [SWivid/F5-TTS#580]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

Tone model saving refers to recording key intermediate results or parameters during tone processing for later use, eliminating the need to start from scratch each time with the original audio. Simply put, during tone generation or transformation, parts of the model's "intermediate outcomes" can be saved as files or stored in a database. This allows for direct loading when needed, improving efficiency and ensuring consistency in the generated tones. 

### 2. What is your suggested solution?

How can I access this feature? Are there any documents or APIs available for reference?

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by SWivid** [comment]
maybe you could elaborate on the `intermediate outcomes`, not quite get yet
do you mean kvcache (no idea about how to apply on f5) or the convnext output of ref_text part (will also need to consider the overlap part with gen_text), or something else
welcome pr

**Comment by land007** [comment]
https://www.youtube.com/watch?v=GkAGIRSIhr4
I hope to understand the API for saving and using the timbre model mentioned here

**Comment by land007** [comment]
cfm.py中的sample方法可以支持直接传入梅尔图谱吗，我不是很确定，求证。

**Comment by SWivid** [comment]
> cfm.py中的sample方法可以支持直接传入梅尔图谱吗，我不是很确定，求证。

https://github.com/SWivid/F5-TTS/blob/7f7fd29675d8fbc31c3333d8ed916d1267f17854/src/f5_tts/model/cfm.py#L103-L106

yes, support directly passing in mel spec
if dim is 2, the input is raw wav; then it will be convert to mel
so if you just pass in mel, will skip this

**Comment by SWivid** [comment]
我先暂时关闭这个issue了，有具体问题可以问下相关博主（因为他们也花费精力和心思做的优化）
如果有其他优化思路，或者模型上的问题，欢迎新开issue探讨和提交PR~

**Comment by land007** [comment]
收到，谢谢你的回答，我修改了一些代码，差不多也能掌握了。
