### ISSUE TITLE
Training longer vs more NFE steps

### ISSUE THREAD

**Issue by kmn1024** [SWivid/F5-TTS#581]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

From the paper, training longer (figure 2) and using more NFE steps (table 2) both improve inference output WER and SIM-o. I am wondering if training for much longer (for example, several million steps on a single language) will allow us to reduce NFE steps significantly, which will help inference speed.

Table 2 seems to be saying that more NFE steps are crucial for MOS subjective evaluations. Does this mean longer training can never fully replace having a high number of NFE steps?

**Comment by SWivid** [comment]
number of updates and nfe steps are different and no conflict with each other

training too long will overfit;
samely too large nfe will have marginal effect

nfe steps is basically for efficiency trade-off (speed / performance)
