### ISSUE TITLE
No gradio and no requirements txt

### ISSUE THREAD

**Issue by Hellboy0319** [SWivid/F5-TTS#584]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

following along with this vid to try and get this to work on my set up https://www.youtube.com/watch?v=JBGrhIsCyks&t=20s the only issues I'm running into are with the github page I haven't found the gradio app in the github anywhere as well as the requirements txt? if you go to 18:27 in the vid you'll see what I mean I'm trying to run it but cant is there somewhere else I need to be pulling these from?

### Steps to Reproduce

1 ran python gradio_app.py to run it via gradio its not there?

### ✔️ Expected Behavior

for gradio app to be there as well as requirements txt?

### ❌ Actual Behavior

its not there?

**Comment by SWivid** [comment]
> * [x] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
> * [x]  I have searched for existing issues, including closed ones, and couldn't find a solution.

[README.md](https://github.com/SWivid/F5-TTS/blob/main/README.md)
