### ISSUE TITLE
fix_duration is not working

### ISSUE THREAD

**Issue by lucasjinreal** [SWivid/F5-TTS#585]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

I set fix_duration to some like 3.2 value, the resulted wav is 0 length, why?

### Steps to Reproduce

simple run the gerate, but just set fix_duration.

### ✔️ Expected Behavior

shoud be in 3.2s

### ❌ Actual Behavior

0

**Comment by SWivid** [comment]
[README.md](https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/infer/README.md)
