### ISSUE TITLE
Some short sentences cannot be synthesized.

### ISSUE THREAD

**Issue by lucasjinreal** [SWivid/F5-TTS#586]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

`Unit 1`

This sentecen can not work, why? 

Does there a way to make it work?

**Comment by SWivid** [comment]
the duration is simply linearly estimated, so not that accurate for extremely short sentences
#460 would help, for try fix duration (the total length of ref_audio + gen_audio in second)
