### ISSUE TITLE
accelerate inference with Tensorrt-LLM

### ISSUE THREAD

**Issue by Bigfishering** [SWivid/F5-TTS#588]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

i've accelerate the inference of F5-TTS successfully, inference time cost less 0.5s to produce 6s audio, is the performance ok?

**Comment by ZhikangNiu** [comment]
I think the RTF performance is ok and we hope you can make a pull request about Tensorrt

**Comment by MithrilMan** [comment]
@ZhikangNiu has this acceleration been merged somehow?

**Comment by Bigfishering** [comment]
> I think the RTF performance is ok and we hope you can make a pull request about Tensorrt

I'll get the code together next week and release it.

**Comment by ZhikangNiu** [comment]
> > I think the RTF performance is ok and we hope you can make a pull request about Tensorrt
> 
> I'll get the code together next week and release it.

Oh thank you and I will re-open this issue

**Comment by ZhikangNiu** [comment]
> @ZhikangNiu has this acceleration been merged somehow?

nope

**Comment by lxianl455** [comment]
Looking forward to your update!

> > @ZhikangNiu has this acceleration been merged somehow?
> 
> nope

**Comment by lxianl455** [comment]
> > I think the RTF performance is ok and we hope you can make a pull request about Tensorrt
> 
> I'll get the code together next week and release it.

Looking forward to your update!

**Comment by Bigfishering** [comment]
> > I think the RTF performance is ok and we hope you can make a pull request about Tensorrt
> 
> I'll get the code together next week and release it.

https://github.com/[Bigfishering/f5-tts-trtllm](https://github.com/Bigfishering/f5-tts-trtllm)

**Comment by Bigfishering** [comment]
> I think the RTF performance is ok and we hope you can make a pull request about Tensorrt

https://github.com/Bigfishering/f5-tts-trtllm

**Comment by Bigfishering** [comment]
> > > I think the RTF performance is ok and we hope you can make a pull request about Tensorrt
> > 
> > 
> > I'll get the code together next week and release it.
> 
> Looking forward to your update!

https://github.com/Bigfishering/f5-tts-trtllm

**Comment by lxianl455** [comment]
> > > > I think the RTF performance is ok and we hope you can make a pull request about Tensorrt
> > > 
> > > 
> > > I'll get the code together next week and release it.
> > 
> > 
> > Looking forward to your update!
> 
> https://github.com/Bigfishering/f5-tts-trtllm

Thank you for this amazing project!

**Comment by Bigfishering** [comment]
> Thank you @Bigfishering !
> 
> I'm curious, did you compare your performance versus Pytorch on a Nvidia GPU? Or did you try only some other processor?

Performance is compared and accuracy is aligned
