### ISSUE TITLE
Unable to Load Custom trained model

### ISSUE THREAD

**Issue by sam4muzix** [SWivid/F5-TTS#589]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

I have successfully trained my custom language model. Its been saved as model_1200000.pt with a settings.json.
But im confused how to use this for testing and inferencing. 

### 2. What is your suggested solution?

An option to load the newly trained model directly in the inference.

### 4. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by SWivid** [comment]
have you already tried the way in infer_gradio?

**Comment by sam4muzix** [comment]
> have you already tried the way in infer_gradio?

Yes .. but i couldn't load the trained model . And it doesn't shows my trained model ib infer_gradio. FYI: i trained via train.py as it was a training from scratch.

**Comment by SWivid** [comment]
maybe you could provide a screenshot of the path filled in for custom ckpt path and vocab

**Comment by sam4muzix** [comment]
![Screenshot 2024-12-05 221203](https://github.com/user-attachments/assets/ba3bf4c3-c55d-4e9c-8fe1-60c119f7c35c)
![Screenshot 2024-12-05 221438](https://github.com/user-attachments/assets/96c1d907-8c29-49b9-ae49-886461776727)
attached my trained model folder ss and infer ss

**Comment by SWivid** [comment]
oh, you need to change the path
delete this default ones, and type (fill in) you local paths into there

**Comment by sam4muzix** [comment]
ok . i will try it.. thankyou so much.

**Comment by bioheater** [comment]
> oh, you need to change the path delete this default ones, and type (fill in) you local paths into there

Hey,
Where do I change these default paths? Cause I put my "custom" model in the Ckpt folder and it won't show it as an option

**Comment by SWivid** [comment]
@bioheater need to **type** your path (fill in the blank)

**Comment by SWivid** [comment]
will close here, feel free to open if further questions.
