### ISSUE TITLE
A reminder for using numpy<2.x，部署的时候python最好选择3.10以下，不包括310

### ISSUE THREAD

**Issue by hotdogarea** [SWivid/F5-TTS#59]
提醒一下，部署的时候python最好选择3.10以下，不包括310，numpy不支持2.x

**Comment by SWivid** [comment]
我们具体有使用过
Python 3.10.14

numpy 1.22.0
numpy 1.26.4

torch 2.3.0+cu118
torch 2.4.0+cu121

应该在比较广泛的版本都可用，感谢提醒 numpy<2.x

**Comment by hotdogarea** [comment]
确实，降级python之后
python gradio_app.py
Traceback (most recent call last):
  File "H:\AIaudio_Live\F5-TTS\gradio_app.py", line 11, in <module>
    from model import CFM, UNetT, DiT, MMDiT
  File "H:\AIaudio_Live\F5-TTS\model\__init__.py", line 7, in <module>
    from model.trainer import Trainer
  File "H:\AIaudio_Live\F5-TTS\model\trainer.py", line 22, in <module>
    from model.dataset import DynamicBatchSampler, collate_fn
  File "H:\AIaudio_Live\F5-TTS\model\dataset.py", line 191, in <module>
    ) -> CustomDataset | HFDataset:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

而这个特性又只能在3.10以上运行。。作者应该在文档里将成功运行的python版本和numpy版本写出来。。。已经部署两次了。。。

**Comment by SWivid** [comment]
感谢指出 在408075fa58d80a63ee6bc426c2480f63df9e8bd1中添加了关于python版本和numpy的说明
如果有另外问题 随时欢迎open issue~

**Comment by nitinmukesh** [comment]
> As a reminder, when deploying, it is best to choose Python 3.10 or below, excluding 310, and numpy does not support 2.x

Python 3.10 is supported with lower numpy version.
