### ISSUE TITLE
Can I use my own language IPA for getting perfect model ?

### ISSUE THREAD

**Issue by RifatMamayusupov** [SWivid/F5-TTS#590]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I trained my dataset for about 40 hours with a single speaker using F5 for 35 epochs. My model synthesizes short words well, but when synthesizing longer text, it produces speech with a different accent. For example, Uzbek is similar to Turkish, so sometimes my model synthesizes Uzbek text with a Turkish accent. Additionally, there is some noise at the end of the output audio.

How can I resolve this issue?

**Comment by Mustaphajudi** [comment]
Bigger dataset,and longer audio samples

**Comment by RifatMamayusupov** [comment]
@Mustaphajudi can you tell me length of audio ? such as 10s or 15 s ?
and total 50 hours dataset is enough ?

**Comment by ZhikangNiu** [comment]
> @Mustaphajudi can you tell me length of audio ? such as 10s or 15 s ? and total 50 hours dataset is enough ?

I think the setting is ok
