### ISSUE TITLE
Does the vocabulary size impact the amount of data required for training?

### ISSUE THREAD

**Issue by DrBrule** [SWivid/F5-TTS#594]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I've been experimenting with this recently, there seems to be some great potential here.  It does clearly take a lot of data to work well.  I was wondering then, if it would train more quickly or with less data if the vocab.txt file is smaller?  Has anyone tried this out?  I realize it would reduce the multi-language capability of the resultant model.

**Comment by SWivid** [comment]
no idea,
thought the hard part is to learn speech-text alignment but word embed seems no conflict with that
and if we use big vocab size but just use part of it, the gradient will just go for the used ones, thus the only bad thing is wasted params and sparse weights (low utilization rate)?

**Comment by DrBrule** [comment]
That's clear, thank you!  Seems like it wouldn't make much of a difference in practice.
