### ISSUE TITLE
Extrem short prompt wav can not be generated

### ISSUE THREAD

**Issue by MonolithFoundation** [SWivid/F5-TTS#595]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

I found it maybe a bug or might my processing was not right. 

Here is the problem:

- Extrem short prompt wav, less than 1s, can not be generate, even thought it has more than 2 words;
vgfbv

### Steps to Reproduce

fev

### ✔️ Expected Behavior

[20241206_154831_115.7_116.2.wav.webm](https://github.com/user-attachments/assets/89ae2385-6ea3-480c-bf83-c764773d145a)

th
[20241206_154831_115.7_116.2_output.wav.webm](https://github.com/user-attachments/assets/3630c93e-950a-48ea-9926-75f87f265fe8)
e

the promt wav have prompt text: 走一个

and the target text set to `go one`

but this siutation actully can not produce anything. Other situation is normal.

What should do it?

### ❌ Actual Behavior

fregtfeg

**Comment by OrphBean** [comment]
Set the speed for the generation much lower when generating short sentences - like 0.3
