### ISSUE TITLE
在推理的时候，能将这个人的音色记录下来，并且不断推理吗？

### ISSUE THREAD

**Issue by 23332323** [SWivid/F5-TTS#596]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

能将这个人的音色记录下来，并且不断推理吗？

### 2. What is your suggested solution?

直接克隆下来

### 3. Additional context or comments

1

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by SWivid** [comment]
请看一下这个模板里Checks的内容以及4里面的内容

传的参考音频是什么样，就克隆什么样

**Comment by 23332323** [comment]
您好，您的邮件已收到，谢谢！  余清
