### ISSUE TITLE
生成的语音开头有噪音，人生比较快。

### ISSUE THREAD

**Issue by dttlgotv** [SWivid/F5-TTS#597]
### Checks

- [ ] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [ ] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

RTX 3090

### Steps to Reproduce

1. 最新的代码
2. f5-tts_infer-cli \
--model "F5-TTS" \
--ref_audio "test.wav" \
--ref_text "大家都准备好了吗？大可大可，咱们开始上课吧。" \
--gen_text "面条是一种形状细长的面食。面条可以很短，如使头发，也可以又长又粗，如荞麦面，还可以同样长但更细，如意大利面，或极细，如玻璃面。无论是哪种形状和形态的面条，都是用某种面粉，小麦粉、大米粉、大豆粉、豌豆粉等）制作而成，不加发酵剂。面条在世界各地的许多菜系中都有制作，但主要是在东亚和地中海菜系中。四千年前在中国青海省发现的面条化石被认为是世界上最古老的面条，研究表明最早的面条是在中国新石器时代发展起来的。面条有新鲜的和干的两种，是多种菜肴的基础。特别值得一提的是汤面，它几乎广泛存在于世界各地的所有文化中。"

### ✔️ Expected Behavior

能够修复这个问题

### ❌ Actual Behavior

开头有噪音。有了人声后 速度比较快。

**Comment by SWivid** [comment]
please review the **Checks**

use a better reference audio, (~10s good quality)

**Comment by dttlgotv** [comment]
> please review the **Checks**
> 
> use a better reference audio, (~10s good quality)

多谢，有效果。

如果我的生成文本是这个， 合成的语音挺好。

--gen_text "面条是一种形状细长的面食。面条可以很短，如使头发，也可以又长又粗，如荞麦面，还可以同样长但更细，如意大利面，或极细，如玻璃面。无论是哪种形状和形态的面条，都是用某种面粉，小麦粉、大米粉、大豆粉、豌豆粉等）制作而成，不加发酵剂。"

但是如果我的生成文本是上面文本的两次重复（如下），合成的声音就不清晰，且有快进的感觉。
--gen_text "面条是一种形状细长的面食。面条可以很短，如使头发，也可以又长又粗，如荞麦面，还可以同样长但更细，如意大利面，或极细，如玻璃面。无论是哪种形状和形态的面条，都是用某种面粉，小麦粉、大米粉、大豆粉、豌豆粉等）制作而成，不加发酵剂。面条是一种形状细长的面食。面条可以很短，如使头发，也可以又长又粗，如荞麦面，还可以同样长但更细，如意大利面，或极细，如玻璃面。无论是哪种形状和形态的面条，都是用某种面粉，小麦粉、大米粉、大豆粉、豌豆粉等）制作而成，不加发酵剂。"

**Comment by SWivid** [comment]
长的文本会被自动切分，所以可能会切到不理想的断句导致语速不均匀。

**Comment by dttlgotv** [comment]
> 长的文本会被自动切分，所以可能会切到不理想的断句导致语速不均匀。



> 长的文本会被自动切分，所以可能会切到不理想的断句导致语速不均匀。

哦，还以为是按照标点符号来断句的，没看那么仔细。

**Comment by SWivid** [comment]
是按照标点切的，但double之后可能会切到逗号，如果整句很长
