### ISSUE TITLE
Multiple GPUs training

### ISSUE THREAD

**Issue by TheMattBin** [SWivid/F5-TTS#598]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

May I know if the training script supports multiple GPUs training or parallel running? Or I can just use torchrun for multiple training? Thanks!

**Comment by SWivid** [comment]
yes, with `accelerate`
[README.md](https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/train/README.md)

**Comment by JohnHerry** [comment]
Is there any example with torchrun?  the accelerate forces so much unfamiliar choices， makes headack
