### ISSUE TITLE
Can it be used to edit speech?

### ISSUE THREAD

**Issue by chenht2021** [SWivid/F5-TTS#6]
Can this model to be used to edit speech?

It follow VoiceBox, but why E2-TTS do not mention its ability of redact speech, or it just can not. Or, I missed some thing?

**Comment by SWivid** [comment]
As it was trained with in-filling task, editing ability should be inherited.
Simply mask out the part for edit, synthesize and replace into this part.

I'll try it out and if it works I'll add it to the script.

**Comment by SWivid** [comment]
@chenht2021 It works well
see `python test_infer_single_edit.py`
have fun~

**Comment by chenht2021** [comment]
Thanks, I figure out I made a mistake sending wrong mask to model.
Thanks for open source this model. Nice work!
