### ISSUE TITLE
生成的音频文件存大小只有几百b， 无法正常播放

### ISSUE THREAD

**Issue by pengyong94** [SWivid/F5-TTS#60]
我使用 /F5-TTS/test_infer_single.py 脚本，利用其他的音频文件作为参考（原本是mp3，格式我直接改掉后缀为wav ,不知道对于参考音频文件的是否有要求， 文件见下面的链接）， 然后指定生成的文本文本内容（2k字符）。执行过程没有报错，约28s推理完成，但是生成的wav文件大小机会为0,无法播放。
[audio.zip](https://github.com/user-attachments/files/17359331/audio.zip)
![image](https://github.com/user-attachments/assets/2fdd7c7a-ba07-43f5-b7a9-7975bde9c3d7)

**Comment by SWivid** [comment]
有以下可能：

1. fix_duraion小于参考音频长度，需要注意 参考音频 和 需要生成 的总长需要小于30秒确保正常生成。
2. 2k字符可能超出了模型单次支持的范围。可以考虑使用仓库里的本地Gradio APP来做切分生成再拼接。

**Comment by pengyong94** [comment]
好的，感谢。后面对文本做切分处理后再将生成的音频进行拼接处理。

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.
