### ISSUE TITLE
Russian language support for f5 tts

### ISSUE THREAD

**Issue by mikhail2013ru** [SWivid/F5-TTS#600]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Will there be Russian language support for cloning and training your own model on f5 and when? Can you do an f5 launch on colab?

**Comment by SWivid** [comment]
pls read the issue template:

> I have thoroughly reviewed the project documentation and read the related paper(s).

already support finetuning

> I have searched for existing issues, including closed ones, no similar questions.

there are issue for colab usage, you can just search `colab`
