### ISSUE TITLE
Please include Custom Vocab maker Or Custom Vocab Option.

### ISSUE THREAD

**Issue by sam4muzix** [SWivid/F5-TTS#604]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

I find much complications while implementing custom
Vocab. Even though changing paths, the vocab mismatch error arises while training from scratch. Please help.

### 2. What is your suggested solution?

Including a custom vocab path modifier 

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by SWivid** [comment]
thought already there?
both cli and local gradio
