### ISSUE TITLE
Can we train based on float16?

### ISSUE THREAD

**Issue by xwan07017** [SWivid/F5-TTS#605]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

We train based on dtype=float32  4*NVIDIA A100 80GB， 330h english voice datasets， 1 weeks，190k steps。
If we train on dtype=float16 ,Will it affect the effectiveness of training?

**Comment by ZhikangNiu** [comment]
Our vocos-based F5TTS checkpoint is trained on A100 80GB with fp16
