### ISSUE TITLE
does F5-TTS support loading pre trained voice models then using them by giving them text?

### ISSUE THREAD

**Issue by linuarM** [SWivid/F5-TTS#607]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

i dont really understand how to use the F5-TTS but as i got i cant drop and drag my voice models to places in web gui. im wondering how can i use my voice models in F5-TTS.
i could not find a source to understand, either trying and messing with gui is not working.

**Comment by SWivid** [comment]
you can follow the readme, the installation and inference.
what do you mean by your voice models, have you trained your own model weight using the model structure here or else
and here gradio ui is used, what is the web gui you mentioned

you may provide more info about what you have tried, and where failed to continue

**Comment by linuarM** [comment]
> you can follow the readme, the installation and inference. what do you mean by your voice models, have you trained your own model weight using the model structure here or else and here gradio ui is used, what is the web gui you mentioned
> 
> you may provide more info about what you have tried, and where failed to continue



> you can follow the readme, the installation and inference. what do you mean by your voice models, have you trained your own model weight using the model structure here or else and here gradio ui is used, what is the web gui you mentioned
> 
> you may provide more info about what you have tried, and where failed to continue

hi, first of all i checked the reamde but i cant seem to find a interface explanation in there.
by saying my voice model i meant a model i downlodad from internet. a voice of somebody. this voice file is a zip and comes with .index and .pth files. 

by web gui i wanted to mean the gradio ui and i tried to somehow use my voice file.
so i tried it in batched TTS, reference audio by dragging files. but it said its invalid file format.
so i checked voice chat but i cant find a way to do it. 
thats the case.

**Comment by SWivid** [comment]
@linuarM yep, understood a bit.
so you are using another project's model checkpoint here, but actually the ckpt weights of one project cannot be used for another, vice versa.

> so i tried it in batched TTS, reference audio by dragging files. but it said its invalid file format.

for reference audio, you can simply use your micro to record something, or click and upload an audio file (not .index or .pth)

> first of all i checked the readme but i cant seem to find a interface explanation in there.

everything is there in readme, i wouldn't take over 10 minutes to get through.
simply put: after install the torch according to your gpu driver (i.e. torch version upon cuda version; e.g. `pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`
then you do `pip install git+https://github.com/SWivid/F5-TTS.git`
then run `f5-tts_infer-gradio` (👈, this is the same as online space demo
![{D4251075-9EEA-4184-ADF6-8B4A01ECB252}](https://github.com/user-attachments/assets/9a46e392-ced9-4e5a-a102-ae656a2cf659)
)

**Comment by linuarM** [comment]
closing comment
