### ISSUE TITLE
Gradio app subsequent gens don't redo the transcribing correctly

### ISSUE THREAD

**Issue by bbecausereasonss** [SWivid/F5-TTS#608]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Win11

### Steps to Reproduce

Latest git pull, 
Use Gradio,
Try different voices (without transcription), get app to auto-transcribe,
App messes up transacriptions on new audio clips,
Have to refresh window in (chrome) in order for it to reset

### ✔️ Expected Behavior

Should transcribe audio each new clip you put in, and clear the cache

**Comment by SWivid** [comment]
as suggested by this template
any detailed info, e.g. screenshots?

**Comment by bbecausereasonss** [comment]
My bad, I didn't realize I was adding the text to the wrong window.
