### ISSUE TITLE
Audio  degrading when using Transcribe Data

### ISSUE THREAD

**Issue by AlpacaManAlpha** [SWivid/F5-TTS#609]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 10, RTX 3060, Python 3.11.9, torch==2.3.0+cu118, cuda 12.1

### Steps to Reproduce

Launch f5-tts_finetune-gradio
Create new project
Put either separate audio clips or full lengh audio file, either .wav or .mp3 into the data folder
Transcribe on the Trascribe Data page
Check the prept audio in the wavs folder and compare to original

### ✔️ Expected Behavior

Audio keeps the same
No quality loss

### ❌ Actual Behavior

Quality loss

But only sometimes... 2/6 projects are fine.

**Comment by AlpacaManAlpha** [comment]
Audio sound like the base was dialed up a bit. Slightly hazy.

**Comment by SWivid** [comment]
maybe because slicer or stuff, feel free to check; or try use dataset/ scripts to prepare and use train.py
