### ISSUE TITLE
Could this be used for singing ?

### ISSUE THREAD

**Issue by davidseroussi** [SWivid/F5-TTS#61]
Hi, awesome work! 
I was wondering if we could use this method to have a powerful singing model as well ?
Either text-to-singing or direct voice conversion ?
Thanks

**Comment by SWivid** [comment]
SVC is also a specialized research topic. I may not be that professional to answer this question.
Just hope our work could help in some minor aspects.

**Comment by leoiania** [comment]
Ciao, I would like to help in case you start a project to fine-tune these models for text-to-singing task.
@jpgallegoar @davidseroussi

**Comment by jpgallegoar** [comment]
@leoiania Best to wait until LORAs are supported :)

**Comment by leoiania** [comment]
@jpgallegoar  don't you think that fine-tuning can help? Especially by using english and chinese singing datasets only ?

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
