### ISSUE TITLE
fail to train with 1k hours

### ISSUE THREAD

**Issue by didadida-r** [SWivid/F5-TTS#616]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

torch                   2.4.1
torchaudio              2.4.1

### Steps to Reproduce

hi, i train the model from flatstart using 1k hours data from wenet tts corpus, but the model  fail to align and get result after training, the loss curve is shown below.

### ✔️ Expected Behavior

the model fail to produce good result

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/2221a908-f7dc-4de1-b41d-d63540037cad)

**Comment by SWivid** [comment]
pls be patient and take some time to read our paper released (include all details you want here
<3
