### ISSUE TITLE
Numeric digits can only be pronounced using Chinese pronunciation, not English pronunciation.

### ISSUE THREAD

**Issue by likangkao** [SWivid/F5-TTS#618]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

When synthesizing numeric digits from an English text, these digits can only be pronounced using Chinese pronunciation, not English pronunciation. Date texts (e.g., Mar. 12, 2024) also have a similar problem.

### 2. What is your suggested solution?

Since I am using the API, I need a parameter like language="en" and language="ch" to identify how to pronounce the numeric digits.

### 3. Additional context or comments

no.

### 4. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by ZhikangNiu** [comment]
you need to transform the numeric digits into english words, it can works well

**Comment by likangkao** [comment]
Ok. Thanks for your reply.
