### ISSUE TITLE
preparing dataset for finetune

### ISSUE THREAD

**Issue by kunci115** [SWivid/F5-TTS#62]
hi, i know you have scripts/prepare_emilia.py

my question is how if i have my own dataset? what format should i provide? what is the structure needed to finetuned? the docs is not that clear

**Comment by SWivid** [comment]
Everything needed for preparing dataset is in https://github.com/SWivid/F5-TTS/blob/408075fa58d80a63ee6bc426c2480f63df9e8bd1/scripts/prepare_emilia.py#L59
It's possible to modify from existing script or draft your own ~

**Comment by lpscr** [comment]
@SWivid thank you for the amazing repo ! 

@kunci115 i create simple script prepate dataset to use  with format csv

```
my_data/
│
├── wavs/
│   ├── audio1.wav
│   └── audio2.wav
│
└── metadata.csv

```

**metadata.csv** you seperate with **"|"**
```
audio1|text1
audio2|text2
audio3|text3
```

the only you change 
```
finetune=True # when finetune false create new vocab.txt 
name_project="myspeak" # name project save in data
path_dataset = r"C:\PythonApps\f5tts\my_data" # full path data
```

```
import sys, os
sys.path.append(os.getcwd())

import pandas as pd
import torchaudio
import os,json
from datasets import Dataset
from model.utils import convert_char_to_pinyin
from tqdm import tqdm
import shutil

finetune=True # when finetune false create new vocab.txt 
name_project="myspeak" # name project save in data
path_dataset = r"C:\PythonApps\f5tts\my_data" # full path data

path_wav = os.path.join(path_dataset,"wavs")
file_metadata=os.path.join(path_dataset,"metadata.csv")

df = pd.read_csv(file_metadata, sep='|', header=None, names=['filename', 'text', 'normalized'])

def get_audio_duration(audio_path):
    audio, sample_rate = torchaudio.load(audio_path)
    num_channels = audio.shape[0]  
    return audio.shape[1] / (sample_rate * num_channels)

#change what you need 
def clear_text(text):
    return text.lower().strip()

def fix_path(filename):
    return os.path.join(path_wav, filename + ".wav")

df['audio_path'] = df['filename'].apply(fix_path)
df['duration'] = df['audio_path'].apply(get_audio_duration)
df['text_clear'] = df['text'].apply(clear_text)

audio_path_list=list(df["audio_path"])
text_list=list(df["text_clear"])
duration_list=list(df["duration"])

tokenizer="pinyin"
polyphone=True
if tokenizer=="pinyin":
   text_list = [convert_char_to_pinyin([text], polyphone = polyphone)[0] for text in text_list]

path_raw=os.path.join("data",name_project+"_pinyin","raw")
file_duraction = os.path.join("data",name_project+"_pinyin","duration.json")
file_vocab = os.path.join("data",name_project+"_pinyin","vocab.txt")
os.makedirs(path_raw,exist_ok=True)

dataset = Dataset.from_dict({"audio_path": audio_path_list, "text": text_list, "duration": duration_list})
dataset.save_to_disk(path_raw, max_shard_size="2GB")  # arrow format

with open(file_duraction, 'w', encoding='utf-8') as f:
    json.dump({"duration": duration_list}, f, ensure_ascii=False)  # dup a json separately saving duration in case for DynamicBatchSampler ease

if finetune==False:
   text_vocab_set = set()
   for text in tqdm(text_list):
       text_vocab_set.update(list(text))
   
   with open(file_vocab, "w") as f:
       for vocab in sorted(text_vocab_set):
           f.write(vocab + "\n")
else:
   file_vocab_finetune = "data/Emilia_ZH_EN_pinyin/vocab.txt"    
   shutil.copy2(file_vocab_finetune,file_vocab)

print(f"sample count: {len(text_list)}")
print("finetune : ",finetune)
if finetune==False:
   print(f"vocab size is: {len(text_vocab_set)}\n")
```

**Comment by ahmetkca** [comment]
how much data would be enough to fine tune for a better result?

**Comment by jamestaksha** [comment]
what should be the max duration of a audio sample for training?

**Comment by lpscr** [comment]
> what should be the max duration of a audio sample for training?

if i am right i think 30 sec max audio can take

**Comment by SWivid** [comment]
any length is fine, as long as the gpu memory is sufficient
see https://github.com/SWivid/F5-TTS/blob/bd16a8c2811b1a43b386bea7c85caf9bee0bfc84/model/dataset.py#L107
tailor to your need

**Comment by kunci115** [comment]
> @SWivid thank you for the amazing repo !
> 
> @kunci115 i create simple script prepare dataset to use with format csv local
> 
> ```
> my_data/
> │
> ├── wavs/
> │   ├── audio1.wav
> │   └── audio2.wav
> │
> └── metadata.csv
> ```
> 
> **metadata.csv** you seperate with **"|"**
> 
> ```
> audio1|text1
> audio2|text2
> audio3|text3
> ```
> 
> the only you need change its t
> 
> ```
> finetune=True # when finetune false create new vocab.txt 
> name_project="myspeak" # name project save in data
> path_dataset = r"C:\PythonApps\f5tts\my_data" # full path data
> 
> and the clear_text in case you want your clear text
> ```
> 
> `pip install pandas `
> 
> ```
> import sys, os
> sys.path.append(os.getcwd())
> 
> import pandas as pd
> import torchaudio
> import os,json
> from datasets import Dataset
> from model.utils import convert_char_to_pinyin
> from tqdm import tqdm
> import shutil
> 
> finetune=True # when finetune false create new vocab.txt 
> name_project="myspeak" # name project save in data
> path_dataset = r"C:\PythonApps\f5tts\my_data" # full path data
> 
> path_wav = os.path.join(path_dataset,"wavs")
> file_metadata=os.path.join(path_dataset,"metadata.csv")
> 
> df = pd.read_csv(file_metadata, sep='|', header=None, names=['filename', 'text', 'normalized'])
> 
> def get_audio_duration(audio_path):
>     audio, sample_rate = torchaudio.load(audio_path)
>     num_channels = audio.shape[0]  
>     return audio.shape[1] / (sample_rate * num_channels)
> 
> #change what you need 
> def clear_text(text):
>     return text.lower().strip()
> 
> def fix_path(filename):
>     return os.path.join(path_wav, filename + ".wav")
> 
> df['audio_path'] = df['filename'].apply(fix_path)
> df['duration'] = df['audio_path'].apply(get_audio_duration)
> df['text_clear'] = df['text'].apply(clear_text)
> 
> audio_path_list=list(df["audio_path"])
> text_list=list(df["text_clear"])
> duration_list=list(df["duration"])
> 
> tokenizer="pinyin"
> polyphone=True
> if tokenizer=="pinyin":
>    text_list = [convert_char_to_pinyin([text], polyphone = polyphone)[0] for text in text_list]
> 
> path_raw=os.path.join("data",name_project+"_pinyin","raw")
> file_duraction = os.path.join("data",name_project+"_pinyin","duration.json")
> file_vocab = os.path.join("data",name_project+"_pinyin","vocab.txt")
> os.makedirs(path_raw,exist_ok=True)
> 
> dataset = Dataset.from_dict({"audio_path": audio_path_list, "text": text_list, "duration": duration_list})
> dataset.save_to_disk(path_raw, max_shard_size="2GB")  # arrow format
> 
> with open(file_duraction, 'w', encoding='utf-8') as f:
>     json.dump({"duration": duration_list}, f, ensure_ascii=False)  # dup a json separately saving duration in case for DynamicBatchSampler ease
> 
> if finetune==False:
>    text_vocab_set = set()
>    for text in tqdm(text_list):
>        text_vocab_set.update(list(text))
>    
>    with open(file_vocab, "w") as f:
>        for vocab in sorted(text_vocab_set):
>            f.write(vocab + "\n")
> else:
>    file_vocab_finetune = "data/Emilia_ZH_EN_pinyin/vocab.txt"    
>    shutil.copy2(file_vocab_finetune,file_vocab)
> 
> print(f"sample count: {len(text_list)}")
> print("finetune : ",finetune)
> if finetune==False:
>    print(f"vocab size is: {len(text_vocab_set)}\n")
> ```

this is working, would be really helpful for everyone if its pushed inside the repo for more clear instruction(finetune)
