### ISSUE TITLE
请教cfg训练相关问题

### ISSUE THREAD

**Issue by splinter21** [SWivid/F5-TTS#629]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

注意到cfg训练参数audio_drop_prob=0.3,cond_drop_prob=0.2,
但是推理audio和text dropout是同时为true的https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/model/cfm.py#L174
于是有2个问题
1、mel_condition的dropout概率比text dropout大一点，二者的dropout概率调参，有什么讲究和方法论吗？
2、为什么训练二者no condition，是分开来dropout，而不是同时dropout？

**Comment by SWivid** [comment]
我先暂时关掉这个issue，因为self checks里说明了最好用英文

**Comment by SWivid** [comment]
这是个挺细节的问题，确实有很多人复现会忽略（包括我在一开始的时候）
如果你仔细看Voicebox的paper，可以看到我们这么设置的来源；voicebox是先0.3drop 然后70~100mask掉的，所以和我们此处是同样的setting，但是我们个人觉得称为two-stage cfg更合适

关于为什么分开，其实就是你在1里说的，让mel cond被drop的概率更大，即：让仅依赖text训练模型生成语音的情况更多。
在早期对比中，这种设置确实让语音和文本对齐学得更快些（即在更早的update ckpt就能听到infer结果有对齐）
