### ISSUE TITLE
Checkpoint saving differences

### ISSUE THREAD

**Issue by lumpidu** [SWivid/F5-TTS#630]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

When having `grad_accumulation_steps` set to a different value than `1`, the checkpoint saving is a bit unexpected:

In `trainer.py` for setting `save_per_updates`:

```python
if global_step % (self.save_per_updates * self.grad_accumulation_steps) == 0:
    self.save_checkpoint(global_step)
```

for setting `last_per_steps`:

```python
if global_step % self.last_per_steps == 0:
    self.save_checkpoint(global_step, last=True)
```

Consequently, for my global batch-size of `19200*8` the value of `save_per_updates` needs to be divided by `8` to be comparable to the setting of `last_per_steps` and the overall variable `global_step` shown via `tqdm`.

Is this intended ?

**Comment by SWivid** [comment]
yes, intended
step and update are different stuffs
