### ISSUE TITLE
EMA Update independently from `grad_accumulation_steps`

### ISSUE THREAD

**Issue by lumpidu** [SWivid/F5-TTS#631]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

In `trainer.py` EMA is updated for each step independently from the setting of `grad_accumulation_steps`.

As an example, in the [diffusors](https://github.com/huggingface/diffusers/blob/main/examples/unconditional_image_generation/train_unconditional.py#L590) project, this is only done at gradient accumulation time.

What is the intuition behind this ?

**Comment by SWivid** [comment]
thanks for pointing out this
there's no intuition here, just a bug lol

we haven't use grad_accum since very early experiments after using torch native flash atten (which save lots gpu mem then)

will be handled with #628
