### ISSUE TITLE
包含阿拉伯数字会输出语音会异常

### ISSUE THREAD

**Issue by alants56** [SWivid/F5-TTS#64]
非常棒的项目，但我发现了一个问题，就是文本中包含阿拉伯数字的话，输出的语音会异常？所以是必须将阿拉伯数字预处理成对应的中文或英文吗。

**Comment by SWivid** [comment]
我们的文本前端还比较简陋，我建议将阿拉伯数字进行预处理
虽然模型能够一定程度上对阿拉伯数字进行生成，但是转化成中文或英文来明确指定读法会更稳定

**Comment by alants56** [comment]
明白了，感谢您的回复

**Comment by lkj7b226** [comment]
一些车型都是英文，没法转成中文啊，这个怎么处理呢？比如M9,  X3 这种就读的奇奇怪怪的
