### ISSUE TITLE
Do you have to set ref_text

### ISSUE THREAD

**Issue by jxaujunjun** [SWivid/F5-TTS#643]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

Do you have to set ref_text? It's so troublesome. Can the program automatically recognize the corresponding subtitles? Thank you

**Comment by ZhikangNiu** [comment]
You can add an ASR model to recognize the corresponding subtitles automatically by yourself.
