### ISSUE TITLE
Not User uploaded 

### ISSUE THREAD

**Issue by Jumao-OC** [SWivid/F5-TTS#651]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

to the gradio cache dir because it was not uploaded by a user.<= An error message is reported in the console. im use this api=>curl -X POST http://192.168.254.10:7860/gradio_api/call/basic_tts -s -H "Content-Type: application/json" -d '{
  "data": [
							{"path":"https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav"},
							"Hello!!",
							"Hello!!",
							true,
							0,
							4,
							0.3
]}' \
  | awk -F'"' '{ print $4}'  \
  | read EVENT_ID; curl -N http://192.168.254.10:7860/gradio_api/call/basic_tts/$EVENT_ID*************************=> this my         // 构建请求数据
        Map<String, Object> requestData = new HashMap<>();
        Map<String, Object> fileData = new HashMap<>();
        // 使用 HashMap 创建 meta 数据
        Map<String, String> metaData = new HashMap<>();

        metaData.put("_type", "gradio.FileData");

        fileData.put("path", fileToSave.getAbsolutePath());//这里需要将文件存到本地 然后拿到这个路径
        System.out.println(fileToSave.getAbsolutePath() + "=======");
        fileData.put("orig_name", originalFilename);
        fileData.put("size", size);
        fileData.put("mime_type", mimeType);
        fileData.put("meta", metaData);

// 将 fileData 和 additionalData 添加到 requestData
        requestData.put("data", new Object[]{
                fileData,
                samplesText,
                genTextInput,
                true,
                0.15,
                32,
                1});

        // 设置请求头
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);

        // 创建请求实体
        HttpEntity<Map<String, Object>> requestEntity = new HttpEntity<>(requestData, headers);

        // 发送 POST 请求并获取 eventId
        ResponseEntity<Map> response = restTemplate.exchange(
                "http://192.168.254.10:7860/gradio_api/call/basic_tts",
                HttpMethod.POST,
                requestEntity,
                Map.class
        ); im want know why

**Comment by SWivid** [comment]
will be discussed in #652
