### ISSUE TITLE
情感克隆

### ISSUE THREAD

**Issue by WGS-note** [SWivid/F5-TTS#655]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

作者团队好！感谢回复！

我在 https://modelscope.cn/studios/modelscope/E2-F5-TTS 以及 https://huggingface.co/spaces/mrfakename/E2-F5-TTS 当中，看到了能够情感克隆，请问我在代码里该怎么调用？

**Comment by WGS-note** [comment]
我知道了，打扰了，感谢！

**Comment by SWivid** [comment]
可以参考这个example
https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/infer/examples/multi

**Comment by WGS-note** [comment]
@SWivid 你好，非常感谢回复！

[town.flac](https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/infer/examples/multi/town.flac)

这个就是情感的音色吗？`town` 不是城市的意思吗？

**Comment by SWivid** [comment]
只是用不同的参考音频指定，并不是说给了个tag就可以直接控制的
