### ISSUE TITLE
Leaving the ref_text blank via the cli doesn't use whisper ASR anymore

### ISSUE THREAD

**Issue by justinjohn0306** [SWivid/F5-TTS#658]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 11, RTX 3090

### Steps to Reproduce

Run the inference using the ``5-tts_infer-cli`` command with the ``--ref_text`` argument left blank.

### ✔️ Expected Behavior

Leaving ``--ref_text`` blank should invoke the Whisper ASR to transcribe the reference audio automatically.

### ❌ Actual Behavior

With the recent updates, the CLI inference script appears to be broken. Leaving ``--ref_text`` blank no longer triggers Whisper ASR for transcription of the reference audio, as it previously did.

**Comment by SWivid** [comment]
thanks for report, fixed
