### ISSUE TITLE
Batch Size Issue with RTX 6000 24GB GPU when fine-tuning

### ISSUE THREAD

**Issue by fkarimi97** [SWivid/F5-TTS#663]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

In the fine_tune_cli.py script, lines 22 to 26, you mentioned that a 24GB GPU can handle a batch size of 3200 samples. However, I am using an RTX 6000 24GB GPU, and it crashes when running fine_tune_cli.py with a batch size of 3200. I have to set the batch size very small for the code to run without any issues. What could be the problem?

**Comment by ZhikangNiu** [comment]
> ### Checks
> * [x]  This template is only for question, not feature requests or bug reports.
> * [x]  I have thoroughly reviewed the project documentation and read the related paper(s).
> * [x]  I have searched for existing issues, including closed ones, no similar questions.
> * [x]  I confirm that I am using English to submit this report in order to facilitate communication.
> 
> ### Question details
> In the fine_tune_cli.py script, lines 22 to 26, you mentioned that a 24GB GPU can handle a batch size of 3200 samples. However, I am using an RTX 6000 24GB GPU, and it crashes when running fine_tune_cli.py with a batch size of 3200. I have to set the batch size very small for the code to run without any issues. What could be the problem?

https://github.com/SWivid/F5-TTS/blob/3e73553bd991835979263968fc82fdf1a1022630/src/f5_tts/model/backbones/dit.py#L108
you can set checkpoint_activations=True to save memory, but it will cost more time
