### ISSUE TITLE
target_sample_rate must be 24000?

### ISSUE THREAD

**Issue by YTWeng176** [SWivid/F5-TTS#666]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

I try to change the target_sample_rate to 16000, and then the audio would be distorted. So can I use the model to produce audio with 24000 sample rate rather then convert the generated audio？

**Comment by SWivid** [comment]
> I try to change the target_sample_rate to 16000, and then the audio would be distorted. So can I use the model to produce audio with 24000 sample rate rather then convert the generated audio？

as you have mentioned, you can first generate with 24khz then resample to 16khz
or you could train from scratch new model checkpoints set up with 16khz the hyper param
