### ISSUE TITLE
多语言版本大概什么时候出来呀

### ISSUE THREAD

**Issue by wchuan163** [SWivid/F5-TTS#668]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

多语言版本大概什么时候出来呀

**Comment by ZhikangNiu** [comment]
现在支持中英双语，我们会尽快放出来支持更多语言的版本
