### ISSUE TITLE
Custom pronunciation?

### ISSUE THREAD

**Issue by GUUser91** [SWivid/F5-TTS#68]
This link states that E2 TTS can explicitly specify the pronunciation of the word (IE sake spelled as (S AA1 K EH0)). How do I do that?
https://www.microsoft.com/en-us/research/project/e2-tts/

**Comment by SWivid** [comment]
Sry that this feature is not supported currently. 
It requires to train with a random replacement of words to phonemes, and need force-align to take care of the data.
