### ISSUE TITLE
输出的音频出现反反复复穿插念叨同一句话，四十秒音频中出现五次文字中未出现的内容

### ISSUE THREAD

**Issue by qiqi0308** [SWivid/F5-TTS#682]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

windows

### Steps to Reproduce

无

### ✔️ Expected Behavior

我无法上传我的音频

**Comment by SWivid** [comment]
不是哥们。。。先看下这个template
 > I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
 I have searched for existing issues, including closed ones, and couldn't find a solution.
 I confirm that I am using English to submit this report in order to facilitate communication.
 
 然后
![image](https://github.com/user-attachments/assets/6ac0ef27-9f45-42b8-bfa2-e80fd3a394dd)
是想让大伙儿虚空打靶猜怎么解决吗

> 我无法上传我的音频

可以打包zip 可以用传在线音频的网站然后给短链接 可以mail 等等
这么多issue里都有人能传音频，能放短链接的。您真看过**existing issues**吗

> 输出的音频出现反反复复穿插念叨同一句话，四十秒音频中出现五次文字中未出现的内容

同一句话是什么话？文字中未出现的内容是什么内容？
你的 参考音频 转录文本 参考文本 生成文本 毛都没说让大伙儿怎么解决？
这些在这个issue template里难道没说吗？

**Comment by qiqi0308** [comment]
> 不是哥们。。。先看下这个template
> 
> > I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
> > I have searched for existing issues, including closed ones, and couldn't find a solution.
> > I confirm that I am using English to submit this report in order to facilitate communication.
> 
> 然后 ![image](https://private-user-images.githubusercontent.com/45333109/399447878-6ac0ef27-9f45-42b8-bfa2-e80fd3a394dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzkwNTEsIm5iZiI6MTczNTYzODc1MSwicGF0aCI6Ii80NTMzMzEwOS8zOTk0NDc4NzgtNmFjMGVmMjctOWY0NS00MmI4LWJmYTItZTgwZmQzYTM5NGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA5NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYzg3Y2RlMDM0NmM1MjVjZWNjNjRhMmNhNjA2OTBmOGE1M2M5MDA2YTZkZTJjOGY2YWFkODY0MTU5MWY2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i6VJqX5a3HrbKs2Qm9Pzmz077j3udWdomjWq-qRD-II) 是想让大伙儿虚空打靶猜怎么解决吗
> 
> > 我无法上传我的音频
> 
> 可以打包zip 可以用传在线音频的网站然后给短链接 可以mail 等等 这么多issue里都有人能传音频，能放短链接的。您真看过**existing issues**吗
> 
> > 输出的音频出现反反复复穿插念叨同一句话，四十秒音频中出现五次文字中未出现的内容
> 
> 同一句话是什么话？文字中未出现的内容是什么内容？ 你的 参考音频 转录文本 参考文本 生成文本 毛都没说让大伙儿怎么解决？ 这些在这个issue template里难道没说吗？

别生气别生气，我刚刚有点急，不好意思唉

**Comment by qiqi0308** [comment]
> 不是哥们。。。先看下这个template
> 
> > I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
> > I have searched for existing issues, including closed ones, and couldn't find a solution.
> > I confirm that I am using English to submit this report in order to facilitate communication.
> 
> 然后 ![image](https://private-user-images.githubusercontent.com/45333109/399447878-6ac0ef27-9f45-42b8-bfa2-e80fd3a394dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzkwNTEsIm5iZiI6MTczNTYzODc1MSwicGF0aCI6Ii80NTMzMzEwOS8zOTk0NDc4NzgtNmFjMGVmMjctOWY0NS00MmI4LWJmYTItZTgwZmQzYTM5NGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA5NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYzg3Y2RlMDM0NmM1MjVjZWNjNjRhMmNhNjA2OTBmOGE1M2M5MDA2YTZkZTJjOGY2YWFkODY0MTU5MWY2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i6VJqX5a3HrbKs2Qm9Pzmz077j3udWdomjWq-qRD-II) 是想让大伙儿虚空打靶猜怎么解决吗
> 
> > 我无法上传我的音频
> 
> 可以打包zip 可以用传在线音频的网站然后给短链接 可以mail 等等 这么多issue里都有人能传音频，能放短链接的。您真看过**existing issues**吗
> 
> > 输出的音频出现反反复复穿插念叨同一句话，四十秒音频中出现五次文字中未出现的内容
> 
> 同一句话是什么话？文字中未出现的内容是什么内容？ 你的 参考音频 转录文本 参考文本 生成文本 毛都没说让大伙儿怎么解决？ 这些在这个issue template里难道没说吗？

我删掉重新编辑，真的不好意思，别因为我生气傲

**Comment by SWivid** [comment]
没事 你用正常template格式 带上具体信息重新开个issue吧

**Comment by qiqi0308** [comment]
> 没事 你用正常template格式 带上具体信息重新开个issue吧

好嘟，谢谢您嘞
