### ISSUE TITLE
Questions about the baseline models in the paper

### ISSUE THREAD

**Issue by WangHelin1997** [SWivid/F5-TTS#7]
Hi,

Thanks for your nice work and open source!
Can I ask how did you get the results of baseline models in your paper, like VALL-E 2, MELLE, Voicebox and NaturalSpeech 3 in Table 1? You mentioned the score reported in baseline papers were from different subsets for evaluation. When I came to the VALL-E 2 paper, I did not see the corresponding results listed in their paper. Could you please explain more about the details of the baselines? Thanks!

**Comment by SWivid** [comment]
Yes, we have mentioned in Appendix-A Baseline Details.
e.g. for VALL-E 2, we compared with results reported in [29], which is MELLE paper
