### ISSUE TITLE
Will not work without reference text.

### ISSUE THREAD

**Issue by KungFuFurniture** [SWivid/F5-TTS#70]
Any time I try to generate audio without a reference text (using gradio) I get the following message:

You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.

And that's it we live here now, until we shutdown.   Not really a big deal to give it reference text, but cleary it is intended to work without.  

Windows 10, AMD 5700xt, python 3.10.6

**Comment by jpgallegoar** [comment]
I don't get this error. Please try deleting and re-cloning the repository.

**Comment by KungFuFurniture** [comment]
Just tried complete re-clone, re-install, no difference...  Below is the full warning/error message. 

D:\Games\F5\F5-TTS\env\lib\site-packages\transformers\models\whisper\generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.

I am more than happy to try any ideas.

**Comment by SWivid** [comment]
As it seems like a warning rather than error, could you get a proper generation result or fail with it

**Comment by KungFuFurniture** [comment]
What I pasted in the last message is it.  That's all it says.  Big generation fail, it will just stay on that message forever.  Gradio still thinks its working, but it never does work.  The pc is not working, nothing.  Again, if I supply the reference text, it seems to work. Takes a min or 2 on cpu but it works.

**Comment by chrisbward** [comment]
Also got the same issue, the warning comes up and then "segmentation fault", the program exits.

If I add the transcribed text, it works - some other issues arise with the generated audio though

**Comment by KungFuFurniture** [comment]
> Also got the same issue, the warning comes up and then "segmentation fault", the program exits.
> 
> If I add the transcribed text, it works - some other issues arise with the generated audio though

What other issues are you getting.  I also noticed with transcribed text, the F5 model gets to a point where it says converting from fp32 to fp16 and never moves on.  The E5 model does great with transcribed audio, however if I use a full 15 seconds, and matching text, the audio is quite fast, it slows down a bit at 12 seconds of source audio.  

I also installed pinikio cause I saw this was on there.  Installed this through Pinikio as well, got the exact same results.

**Comment by jpgallegoar** [comment]
Hello, are you still getting the same issues?

**Comment by KungFuFurniture** [comment]
> Hello, are you still getting the same issues?

Yes, as you ask, I did a git pull, and tried again. (Not the pinikio version I mentioned), and still the same result.  
```
generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
```
once here there is no cpu/gpu usage at all.  We are just hanging.

**Comment by jpgallegoar** [comment]
Maybe there is a problem with the whisper model, did you try deleting it and letting the apo redownload it? The model is in another folder so it doesnt get deleted when you redownload the repo

**Comment by KungFuFurniture** [comment]
Where would I find that model?

**Comment by jpgallegoar** [comment]
In my computer it's at:

C:\Users\thega\.cache\huggingface\hub

**Comment by KungFuFurniture** [comment]
That's exactly where mine was,  Why do you have my user name...  Just kidding.  It was there, started fresh, same exact results.   However, as I started fresh I got all sorts of dependency issues.  The version of faster-whisper recomended requires a lower version of tokenizers. (0.15.2) but the the app won't even start with that version of tokenizers, and the up to date version of transformers won't work with 0.15.2.  I am not sure how far back in transformers we need to go.  I gave up after a few tries before I broke everything.  Transfomers installs the tokenizers it needs, but each of my attempts was the wrong tokenizer.   If someone else thinks I am down the right rabbit hole I'll keep trying.  But, it feels like I might be making a bigger mess than is actually present.

**Comment by jpgallegoar** [comment]
OMG that sounds painful. The easiest method is to factory reset your pc. jk lol. This is my pip list in case you need it.

**Comment by KungFuFurniture** [comment]
So I think the issue is cuda and whisper.  Note I am AMD (Old AMD)  So my torch is different, and I am willing to believe that is the issue.   I can get faster whisper to work without cuda (I have in my own program project, but abandoned it for a faster smaller implementation) In your case you have torch cu124   which is not an option for my system.   There is a way to move faster-whisper to cpu, but I don't recall the process.  And that would take some diving into these scripts, calling it, etc.    And if I am being totally honest, the max 15 sec of audio sample, is not asking for a whole bunch of manual transcribing.  I can't truly say it's worth that much effort (because I do not know what I am doing).   I'll install your pip list (less torch) and update any major events.   If you have anything you want me to try, I am happy to.

**Comment by jpgallegoar** [comment]
If you can get any version of whisper running and that's your only thing holding you back, it's an easy fix!

**Comment by SWivid** [comment]
will close this issue, if further questions feel free to open

**Comment by TrevorAj** [comment]
Saved me a lot of trouble
