### ISSUE TITLE
Audio splitting is broken since the "minor fix" commit.

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#74]
The changes made in the "minor fix" commit have broken the audio splitting for batch processing. Now small prompt get split up in lots of batches, ruining inference quality.

**Comment by SWivid** [comment]
Ah yes, mistaken the sampling rate.
will it be fine with the lastest pull?

**Comment by jpgallegoar** [comment]
Yes, it is solved :D
