### ISSUE TITLE
Problems caused by loading the Vocos model

### ISSUE THREAD

**Issue by zhuojun1024** [SWivid/F5-TTS#75]
When the text is relatively long, it will be divided into several segments for inference, and each inference segment will pause for a long time. The inference time for 169 characters using the NVIDIA 2080Ti graphics card is over 2 minutes, and most of the time the GPU is not working.

I observed that in the 247 line code of gradio_app.py, the vocos model is loaded from huggingface.co, and this line of code is in a for statement. I tried to move this line of code to below 43 lines of code, and the problem was solved, with inference taking only 25 seconds.

The reason for this problem is that my local network cannot directly access huggingface. co, which results in waiting for timeout before executing segmentation inference.

![image](https://github.com/user-attachments/assets/583e4f88-5465-4a4d-be08-58f12b06b13a)
![image](https://github.com/user-attachments/assets/e505be54-3865-4918-86f5-612ebeac3c29)

**Comment by SWivid** [comment]
Thanks a lot, fix in f2b892a61bf7b1fef7f72892b853c26d2bb139f7
