### ISSUE TITLE
Numpy version

### ISSUE THREAD

**Issue by AWAS666** [SWivid/F5-TTS#76]
Why isn't the numpy version set to 1.23.5 in the requirements?
1.22.0 is mentioned in the readme, but the one that seems compatible is 1.23.5

Also prolly better to install torch first, then the requirements, as they will install torch as well but likely the wrong version

**Comment by SWivid** [comment]
Thanks for mentioning.
torch installation instruct placed to first now.
not sure if numpy==1.23.5 compatible for everyone, as may exist other pkg conflicts
