### ISSUE TITLE
Weird Voice Change

### ISSUE THREAD

**Issue by imomin** [SWivid/F5-TTS#78]
Any idea why the pitch/voice changes for the following sentence? It works fine with everything else. 

```
python inference-cli.py \
--model "F5-TTS" \
--ref_audio "tests/ref_audio/test_en_1_ref_short.wav" \
--ref_text "Some call me nature, others call me mother nature." \
--gen_text "Thanks for having me\!"
```

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.

**Comment by imomin** [comment]
@SWivid any idea, if the model needs to be fine-tuned for the above phase with a better audio?

**Comment by SWivid** [comment]
if you mean high resolution audio or a tailored speaker style, yes.
