### ISSUE TITLE
Inference speed (RTF)

### ISSUE THREAD

**Issue by AldoKacorri** [SWivid/F5-TTS#81]
Hi,

What is the Real-time factor of the F5-TTS model? I have tested it on the demo provided and get close to RTF = 3.0. 

Is the model already optimized for inference or are there still steps to do to bring the RTF down?

Thank you and great work!

**Comment by ScottishFold007** [comment]
> Hi,
> 
> What is the Real-time factor of the F5-TTS model? I have tested it on the demo provided and get close to RTF = 3.0.
> 
> Is the model already optimized for inference or are there still steps to do to bring the RTF down?
> 
> Thank you and great work!
What hardware?

My, 1 H800 80G， RTF = 1.7

**Comment by SWivid** [comment]
@AldoKacorri the RTF counts for model inference time, while it takes some time to load ckpts and stuffs.
the RTF reported in our paper is a avg of 200 runs

**Comment by AldoKacorri** [comment]
Thank you!

**Comment by sunnnnnnnny** [comment]
@SWivid Amazing work. but I test it using a 10 times loop and use latest code.RTF equal 0.63 and it is not matching the paper's declare.

**Comment by SWivid** [comment]
@sunnnnnnnny were you using nfe=16 or 32

**Comment by sunnnnnnnny** [comment]
> @sunnnnnnnny were you using nfe=16 or 32 and also on which gpu

yes use gpu and nfe=32. use default settings.

**Comment by SWivid** [comment]
> > @sunnnnnnnny were you using nfe=16 or 32 and also on which gpu
> 
> yes use gpu and nfe=32. use default settings.

you may refer to tab.1 5 & 6 in our paper
rtf=0.15 is with euler ode solver, nfe16, and generating a 10s audio (the way voicebox do mesurement on inference time)

**Comment by sunnnnnnnny** [comment]
> > > @sunnnnnnnny were you using nfe=16 or 32 and also on which gpu
> > 
> > 
> > yes use gpu and nfe=32. use default settings.
> 
> you may refer to tab.1 5 & 6 in our paper rtf=0.15 is f5 with euler ode solver, nfe16, and generating a 10s audio (the way voicebox do mesurement on inference time)
> 
> i just test again with 200 times, seems matched with previous results just in case you miss the script in inital commit: https://github.com/SWivid/F5-TTS/blob/074881635d2cbe63f33282d632144732d89b7107/test_infer_single.py

I know.I set nfe with 16, ode with euler.with a loop 100 times;every times generate a 10s audio.prompt audio duration is 4s; rtf's  rtf greater than 0.7. What graphics card are you using?

**Comment by SWivid** [comment]
> every times generate a 10s audio.prompt audio duration is 4s; rtf's rtf greater than 0.7.

We are using RTX3090 24G for RTF test.
It's weird if you got 0.63 for 32NFE and >0.7 for 16NFE, should just be half with 16NFE compared to 32NFE

**Comment by sunnnnnnnny** [comment]
> > every times generate a 10s audio.prompt audio duration is 4s; rtf's rtf greater than 0.7.
> 
> We are using RTX3090 24G for RTF test. It's weird if you got 0.63 for 32NFE and >0.7 for 16NFE, should just be half with 16NFE compared to 32NFE

Not surprising.Becase the lengths of the two test texts are different.It seems to be a graphics card model issue.
