### ISSUE TITLE
how reduse the train model for 5GB to 1.3GB ?

### ISSUE THREAD

**Issue by lpscr** [SWivid/F5-TTS#84]
Hi! When the model is trained, the checkpoint can be quite large, around 5 GB. Once it's done, you can easily reduce the size using this function, and now the model is only 1.3 GB. Is this correct? I’m new to this stuff. like i see working fine

```
import torch

def extract_and_save_ema_model(checkpoint_path: str, new_checkpoint_path: str) -> None:
    try:
        checkpoint = torch.load(checkpoint_path)
        print("Original Checkpoint Keys:", checkpoint.keys())
        
        ema_model_state_dict = checkpoint.get('ema_model_state_dict', None)

        if ema_model_state_dict is not None:
            new_checkpoint = {'ema_model_state_dict': ema_model_state_dict}
            torch.save(new_checkpoint, new_checkpoint_path)
            print(f"New checkpoint saved at: {new_checkpoint_path}")
        else:
            print("No 'ema_model_state_dict' found in the checkpoint.")

    except Exception as e:
        print(f"An error occurred: {e}")
```

**extract_and_save_ema_model(checkpoint_path, new_checkpoint_path)**

**Comment by thunn** [comment]
Generally, a training checkpoint might contain the model + optimizer weights. At inference time we only need the model weights, so the inference checkpoint is usually smaller. 

Additionally, this code uses a method called Exponential Moving Average ([see the pytorch library here](https://github.com/lucidrains/ema-pytorch)) which creates a copy of the model which is only updated based on the EMA of the original model.

In the EMA case, the training checkpoint would be something like model + ema_model + optimizers. And inference uses just the model so we would expect it to be smaller

**Comment by lpscr** [comment]
@thunn  Thank you for the clarification! I appreciate the explanation

**Comment by JarodMica** [comment]
It would seem that you can distill it down by just keeping the ema dict, there's a little discussion here that I had with the author https://github.com/SWivid/F5-TTS/issues/27

Finetuning the distilled model takes the ema dict values and uses them for model dict values so I assume that as long as your distilled model is working in inference, you should be good to go.
