### ISSUE TITLE
Generate a harsh sound！！！

### ISSUE THREAD

**Issue by wen0320** [SWivid/F5-TTS#93]
你好，非常感谢你开源这么棒的项目。在测试的过程中发现生成的大多数语音都存在爆音（刺耳声）。尤其是拼音‘s’和‘sh’存在的时候。请问这种情况怎么进行优化呢？
Hello, thank you very much for the great open source project. Most of the sounds generated by the process of testing are explosive. Especially when the pinyin s' and sh' exist. How do you optimize this situation?

**Comment by ZhikangNiu** [comment]
您可以提供使用的示例吗？（包括合成的语音，合成的文本和给定的音频prompt

**Comment by wen0320** [comment]
[harsh sound.zip](https://github.com/user-attachments/files/17374357/harsh.sound.zip)

**Comment by SWivid** [comment]
> [harsh sound.zip](https://github.com/user-attachments/files/17374357/harsh.sound.zip)

might for used trainset, we found current Emilia actually cut all audio to 11.2khz, though saved in 24khz or 32khz
try with re-rank, or use smaller cfg strength e.g. 1.5 https://github.com/SWivid/F5-TTS/blob/2d26fba7bf981d95e3f0b84f9db5b78ae5da9789/inference-cli.py#L119
probably better if finetune on high quality audio, we'll consider it in future training

**Comment by wen0320** [comment]
> might for used trainset, we found current Emilia actually cut all audio to 11.2khz, though saved in 24khz or 32khz try with re-rank, or use smaller cfg strength e.g. 1.5

Thanks for your reply. Setting  cfg_strength to 1.5 still does not solve this problem, so it seems that you can only fine-tune it with high-quality data. Does the F5-TTS support 32KHz speech generation? I tried it and could generate it, but the generated speech was far less stable than generating 24KHz speech.

**Comment by SWivid** [comment]
> Does the F5-TTS support 32KHz speech generation?

as it is train on 24khz (all resampled to 24khz), 32khz not supported

**Comment by taalua** [comment]
@SWivid what are the architecture modifications which are necessary to train/generate for a higher sampling rate?

**Comment by SWivid** [comment]
> @SWivid what are the architecture modifications which are necessary to train/generate for a higher sampling rate?

simply change to a higher one, note that the audio sequence with higher sampling rate will be longer, so maybe smaller batchsize to avoid training oom
https://github.com/SWivid/F5-TTS/blob/ab78265b4d6e4c512374baaea56d7c46a35cb61b/train.py#L8
