### ISSUE TITLE
这简直就是一个学术造假。

### ISSUE THREAD

**Issue by dnlzsy** [SWivid/F5-TTS#98]
放出来的模型和论文的例子就是两个东西。要么是没有开源，要么就是造假。
丢交大的脸啊。

**Comment by SWivid** [comment]
确实 看看你的😀

**Comment by SWivid** [comment]
Closing this issue as it is consuming resources that could be better utilized elsewhere.

**Comment by heiway** [comment]
假在哪里，效果相当不错，生成速度也很快。感谢作者分享
